### ISSUE TITLE
Full Form Availability 

### ISSUE THREAD

**Issue by Suengyr** [Zarel/Pokemon-Showdown#1119]
Suggestion to include all in-game existing formes.  
Resolute Forme Keldeo has no stat changes, so I do wonder at the lack of Gastrodon, Furfrou, and etc.   Considering slots are already in creation for as-of-yet -unreleased Pokemon, I would like to see Showdown be a more vibrant place, especially since the models are already available for most (Furfrou being one lacking on most resource sites).

Among other reasons, having a Cynthia team with an West Sea instead of a her green-blue East Sea Gastrodon is off-putting, and soon we'll be seeing more alternate formes in Pikachu as well.  If Pikachu can wear a dress, a Furfrou should have a top hat.

**Comment by Zarel** [comment]
This is nearly done at: Zarel/Pokemon-Showdown-Client#704

**Comment by Zarel** [comment]
Zarel/Pokemon-Showdown-Client#704 is done

**Comment by Slayer95** [comment]
@Zarel, we didn't get the Furfrous yet, did we?

**Comment by Zarel** [comment]
well, we should probably deal with that in the client issue
