### ISSUE TITLE
Add missing fail messages.

### ISSUE THREAD

**Issue by DanUgore** [Zarel/Pokemon-Showdown#1190]
For example: Turn 10 http://replay.pokemonshowdown.com/fairyfaceoff-159849556

**Comment by TheImmortal** [comment]
I think this is fixed now. Right @Marty-D?

**Comment by Zarel** [comment]
Yeah, I added most of them back in recently.

**Comment by Marty-D** [comment]
I don't know about past gens, but it's fixed for Gen 5 and 6 at least. We can deal with other issues if/as they come up.
