### ISSUE TITLE
Preset battles & feedback to external target

### ISSUE THREAD

**Issue by Katemare** [Zarel/Pokemon-Showdown#1194]
I run a Pokemon gaming website akin to Global Pokedex Plus, on a PHP/MySQL platform. We often hold tournaments via Pokemon Showdown, but we have to limit ourselves to only drawing species, genders and levels from the on-site game - they are the parameters that can be verified by sight. We can't use natures or stats from the on-site game because they can't be verified, so a player can really set anything he or she wants.

We would benefit hugely from a capability for admins to view all pokemon parameters (in battles where the admin is on a player), live or in replay. Or, ideally, a feature of preset battles loaded from a file, URL or another source (editable by admins or provided, say, by a website mechanism) and tied to players' accounts. Another feature that would be extremely useful is a feedback from PS into an external file or another target with battle's outcome and log, for the website to read, parse and apply

Maybe these features are already there? I didn't find mentions of them, but still. And if not, maybe in time I could contribute them (I only began studying Node.js, but your code looks so slick and clear that I feel it's possible). However, if someone more experienced will implement those features, they will have the deepest gratitude of our hundred+ players!

**Comment by Joimer** [comment]
Update to this: Challenge battles are now logged if specified.
What could be cool is a feature to limit Pokémon in a tournament, maybe.

**Comment by Zarel** [comment]
It looks like everything relevant to this issue is now done.
