### ISSUE TITLE
Format-specific timer options

### ISSUE THREAD

**Issue by DanUgore** [Zarel/Pokemon-Showdown#1205]
Ideally before VGC 2015 rules are announced we should be able to replicate to an extent the in-game timer. Although lag definitely sucks I'm sure we can provide some slight leeway for that server-side somehow. We could also have some form of confirmation sent from the server that it received the moves.

On a tangent from that, we will look into interest in removing the option to cancel a move in VGC, If it's a popular opinion/desire then look into working on that as well and implementing if it's not that invasive.

**Comment by Zarel** [comment]
We should be refactoring timer code from `rooms.js` to `simulator.js`... this is on my to-do list.

**Comment by panpawn** [comment]
blah blah discussion about moving simulator bits of PS into a node stream blah blah

I guess it would be better to wait for that refactor than to go about this, maybe

**Comment by Zarel** [comment]
Well, "simulator bits" here refers to `battle-engine.js`. `simulator.js` is reasonably isolated from that.

**Comment by panpawn** [comment]
^how did that just happen

**Comment by acz13** [comment]
@panpawn Some weird shit with having 2 people assigned maybe?

**Comment by asingh04** [comment]
can someone help me out here. I do see the `room.js` file, but I couldn't find the `simulator.js` file. And I think simply copy & paste is not a solution here.

**Comment by acz13** [comment]
@asingh04 `simulator.js` was renamed to [`room-battle.js`](https://github.com/Zarel/Pokemon-Showdown/blob/master/room-battle.js)

**Comment by TheImmortal** [comment]
I guess this is done now? @Zarel

**Comment by Slayer95** [comment]
In VGC, we must call ``BattleSide#chooseDefault()`` (or whatever it's called now) when the turn timer expires instead of forfeiting.

Though maybe we should still autoforfeit if a player is AFK for 3+ decisions?

**Comment by Zarel** [comment]
`chooseDefault` just chooses the first move; I was under the impression that VGC chooses a random move?

**Comment by Slayer95** [comment]
It chooses the first move, and likewise for switches. The only disagreement is in Team Preview, where the current algorithm involves team order swap for GUI convenience, whereas in VGC it's lineal.

**Comment by Zarel** [comment]
?

**Comment by Zarel** [comment]
I don't understand how the team preview distance affects `chooseDefault`?

**Comment by Slayer95** [comment]
Not sure what you mean by "distance", but the issue I mentioned only happens when the user has sent only a part of his team order decision by the time their turn ends. Supporting that circumnstance is not critical at this point, so ``chooseDefault()`` should work just fine.

**Comment by Zarel** [comment]
Oh, I understand now.

**Comment by Slayer95** [comment]
Fixed in 73f7c998823 and 9bc83e897b, among other follow-up commits.
