### ISSUE TITLE
Explosion shouldn't ignore burn

### ISSUE THREAD

**Issue by scalarmotion** [Zarel/Pokemon-Showdown#1287]
http://replay.pokemonshowdown.com/uberssuspecttest-176906632

252+ Atk Life Orb burned Landorus-T Explosion vs. 0 HP / 0 Def Arceus-Ground: 179-212 (46.9 - 55.6%) -- 75% chance to 2HKO

The opposing Landorus-Therian used Explosion!
overrated pony lost 93.9% of its health!

**Comment by ascriptmaster** [comment]
https://github.com/Zarel/Pokemon-Showdown/commit/ba426e0a73023ab9ac01d8a36a0997aeda04dfb8 should have fixed this, right?

**Comment by Slayer95** [comment]
Yup
