### ISSUE TITLE
Add relevant formes for Vivillon

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#1318]
Poké Ball Vivillon can't know Rage Powder (egg move), for being event-only.
Fancy Vivillon is the only pattern that can know Hold Hands, again for being event-only.

**Comment by Layell** [comment]
I'm going to assume this isn't relevant. If there is a need for VIvillon formes that have positive gains rather than negative ones let me know as well.

**Comment by Slayer95** [comment]
I don't get it... This seems about as important as having both Keldeo and Keldeo-Resolute.

When I see a Keldeo, it may have or may not have Secret Sword, while when I see a Keldeo-Resolute I immediately know that it <i>has/<i> that move.
Similarly, when I see any Vivillon (except Poké Ball), it may or may not have Rage Powder, while when I see a Poké Ball one I immediately know that it <i>doesn't have</i> that move.

**Comment by Zarel** [comment]
It's mildly important, I guess. Keldeo-R isn't that important either; we just have it because there are people who like how it looks and Keldeo is high OU. If enough people like certain Vivillon formes, we could, but I wouldn't consider it a higher priority than anything else.

**Comment by Zarel** [comment]
I think @Layell's recent sprite update included Vivillon formes? Can we merge this yet?

**Comment by Zarel** [comment]
Wait, this isn't a pullreq. I swear there was a pullreq about the Vivillon formes somewhere...

**Comment by ascriptmaster** [comment]
@Zarel, it's #2262

**Comment by Slayer95** [comment]
Closed by #2262 and #2560
