### ISSUE TITLE
Properly validate IVs

### ISSUE THREAD

**Issue by DanielCranham** [Zarel/Pokemon-Showdown#1342]
As how  low priority as it sounds due to how inviable hidden power fighting is, due to the Mechanics of obtaining legends in game from X/Y/ORAS hidden power fighting should not be legal on some pokemon, thus effectivily making it an illegal combo.

Xerneas, Yveltal, Zygarde, Diancie, Darkrai + phantom force Jirachi + moonblast, Celebi +hold back (from the events) must have at least 3 31ivs when obtained in game and they are always produced with at least these number of IVS. The best hidden fighting combo 31/31/30/30/30/30 is unobtainable on these pokemon through normal gameplay and therefore should be considered illegal on the simulator.

**Comment by Zarel** [comment]
So correct me if I'm wrong, but a mon with fewer than 3 perfect IVs must be either gen-5-or-earlier or not be in the Undiscovered egg group? Does that adequately describe the conditions for this?

**Comment by TheImmortal** [comment]
As I said in ae9363ae906ac1215d597bd805a2728423b4acd0, Undiscovered egg group Pokemon caught in the wild in gen 6 must have at least 3 perfect IVs.

So, yes, your conditions are correct. But I'd add the word "caught" to it: must be caught either gen-5-or-earlier.

**Comment by Marty-D** [comment]
I just checked a Happiny and a few Unown caught in Mirage Spots, and they have one or zero perfect IVs. ORAS seems to have done away with the non-legendary portion of the Undiscovered egg group having 3 guaranteed perfect IVs, presumably because the DexNav exists.

**Comment by TheImmortal** [comment]
Oh...

**Comment by DanUgore** [comment]
That's GF for you, never consistent.

**Comment by Zarel** [comment]
Okay, so we need to start explicitly flagging legendaries now?
