### ISSUE TITLE
Ads and slow (stuck) battles

### ISSUE THREAD

**Issue by trplbackflip** [Zarel/Pokemon-Showdown#1414]
Ad: 
<div id="addiv" class="adDiv" style="visibility: visible; cursor: pointer;" dir="ltr">
        <a class="adsTitle" id="ttl" href="#">
            <div id="ttldiv" class="adsRegFont">Make $Money$ Online !</div>
            <div id="desc" class="description">Be your own boss Spend more time with family !</div>
            <div id="disp" class="disp" style="visibility: hidden;">directon.me</div>
        </a>
    </div>

<div class="scrollFixIt" style="color:#B1B193; font-family:Arial; font-size:12px; padding:5px 5px;height:10px"><a href="javascript:void(0);" style="color:#000; float:right; text-decoration:none;background-color:white;">Close(X)</a><span>&nbsp;</span></div>

<iframe name="rhfrm_TICAREX_26991_3" id="rhfrm_TICAREX_26991_3" frameborder="0" src="http://rhtag.com/adServe/20150101imgBanner/1421041855111_010235612_image-banner.cib?tid=TICAREX_26991_3&amp;num=1&amp;w=728&amp;h=90&amp;orig_url=http%3A//play.pokemonshowdown.com/&amp;ref_url=&amp;keywords=Showdown%21" scrolling="no" htmlname="20150101imgBanner/1421041855111_010235612_image-banner.cib" cid="TICAREX_26991_3" w="728" h="90" allowtransparency="allowtransparency" hid="rhtag.com" style="width: 728px; height: 90px; border: none;"></iframe>
Found when I inspected the ad in Chrome.

**Comment by Zarel** [comment]
You have a virus, run a virus scan and never again use any open-source project's issue tracker for tech support.
