### ISSUE TITLE
Killing the Server leaves dead processes

### ISSUE THREAD

**Issue by Freigeist** [Zarel/Pokemon-Showdown#1507]
Using /lockdown and then /kill leaves "dead" process on the server, i noticed this today, since the RAM and Swap were occupied by this kind of processes:

![Screen 1](http://puu.sh/fr84v/26b0f3ed6a.png)
![Screen 2](http://puu.sh/fr7TR/d0fdaaa694.png)

Some system informations:

```
root@vps1:~# cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

root@vps1:~# uname -a
Linux vps1 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@vps1:~# node --version
v0.10.25
```

**Comment by kotarou3** [comment]
Are you running any server modifications? Especially with regards to the multi process code

**Comment by Freigeist** [comment]
To make sure I cloned a clean copy from here, same results

**Comment by Zarel** [comment]
@kotarou3, do you get the same problem?

**Comment by kotarou3** [comment]
I just tested and got this problem. Ubuntu 14.04.1 here as well

I usually just SIGINT my servers to kill them though, so I would have never noticed this problem.

**Comment by Zarel** [comment]
Can you see if replacing `process.exit()` with `process.kill(process.pid, 'SIGINT')` fixes it?

**Comment by Freigeist** [comment]
Replaced the `process.exit()`in lines 1480, 1486, 1492 (should be all relevant lines or?) with `process.kill(process.pid, 'SIGINT')` this does not fix the issue. Manually kill the server with `SIGINT` results in the same issue, leaving three dead processes

**Comment by Zarel** [comment]
I can reproduce with OS X 10.9 and iojs.

**Comment by Zarel** [comment]
Man, `child_process` is horribly documented, so this took a while to fix.

**Comment by Zarel** [comment]
Specifically, how the `process` global variable changes in a child process is not documented in any one specific place. Instead, there are just some places that mention "Oh, by the way, you can use `process.blah` in the child process".

The fact that the child process even has a `disconnect` event was incredibly unclear to me, but after a ton of Googling I've finally discovered that that's what I'm supposed to be listening to. :|
