### ISSUE TITLE
Hyperspace Hole/Fury reacting strange on other Pokemon

### ISSUE THREAD

**Issue by ih8ih8sn0w** [Zarel/Pokemon-Showdown#1532]
Not sure if this is a bug or if Hyperspace Fury/Hole is supposed to act this way but...
<a href=http://replay.pokemonshowdown.com/customgame-211320581> Replay of testing </a>

<ul>
<li>The Hoopa has Hyperspace Fury/Hole, just to make sure those were working correctly</li>

<li>The Floette had those moves and Light of Ruin just to be able to kill something if needed for whatever reason</li>

<li>The Sunkern had the same moves as the Floette</li>
</ul>
Hoopa's moves functioned as expected but Hyperspace Fury failed when used. However Hyperspace Hole functioned normally.

**Comment by ascriptmaster** [comment]
It's a feature, not a bug. Only Hoopa can use Hyperspace Fury, and only when it is in the Unbound forme. Not even Hoopa's Confined forme (the default forme) can use the move. It's the only move that works this way.

**Comment by ascriptmaster** [comment]
Also, use our bug report thread on Smogon for things relating to move mechanics next time.

http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/

**Comment by Slayer95** [comment]
And never, never, NEVER, open issues that you are not sure about.
Yea, I should definitely write the <code>CONTRIBUTING.md</code>...

**Comment by Zarel** [comment]
How likely are people to read `CONTRIBUTING.md`? Does it show up when people try to fork/pullreq?

**Comment by Zarel** [comment]
In context, more importantly: does it show up when people try to create an issue?

**Comment by ascriptmaster** [comment]
https://github.com/blog/1184-contributing-guidelines

> ... we will add a link to your file when a contributor **creates an Issue** or **opens a Pull Request**.
