### ISSUE TITLE
Hello where are the battle animations ?

### ISSUE THREAD

**Issue by MonsterMMORPG** [Zarel/Pokemon-Showdown#1697]
I can not find any png file when i download the whole code where are they ? In which files animations are designed ?

**Comment by kotarou3** [comment]
That is not a bug. Please keep such questions off the bug tracker.

To answer your question, battle animations are [here](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/data/graphics.js)

**Comment by sirDonovan** [comment]
The code in this repository is what runs behind-the-scenes on the server. Code for anything that is seen in a browser when accessing the server can be found in the <a href="https://github.com/Zarel/Pokemon-Showdown-Client">client repository</a>. The .png files that you're looking for are in the 'fx' folder.
