### ISSUE TITLE
Users cannot link directly to hidden or private rooms with modjoin

### ISSUE THREAD

**Issue by ascriptmaster** [Zarel/Pokemon-Showdown#1787]
Taking note of this here so other people can see this and maybe have a solution.

When someone goes to play.pokemonshowdown.com/roomname, the join request will complete before the `/trn` request has been sent back to the server. This means that since the user is not counted as "logged in" at the moment, they have no auth or roomauth to check, and therefore the server will pretend that the user does not exist.

**Comment by ascriptmaster** [comment]
@Joimer says that we should use a purely client-side fix where if a user has a logged-in cookie, it should wait until `/trn` is sent before attempting to send any `/join` commands.

**Comment by Zarel** [comment]
The client currently already auto-retries joining private rooms after logging in. It should be a simple change to make it auto-retry joining modjoin rooms, too (i.e. rooms that don't exist) as well.

**Comment by ascriptmaster** [comment]
So have the server send namerequired on all modjoin rooms (plus nonexistent rooms to prevent leaks) if it detects a user is not logged in?

**Comment by kotarou3** [comment]
Or just try to join the room listed in the URI again, and if it fails, just ignore the error

**Comment by Zarel** [comment]
> So have the server send namerequired

No, have the client interpret nonexistent rooms the same way it currently interprets namerequired

**Comment by Slayer95** [comment]
Fixed by https://github.com/Zarel/Pokemon-Showdown/commit/39d2715ddb0d0a1142d0f1c235b01c4e7e3538ab
