### ISSUE TITLE
Storm Throw vs Battle Armor

### ISSUE THREAD

**Issue by DialaceStarvy** [Zarel/Pokemon-Showdown#1846]
A Storm Throw managed to crit my Battle Armor Drapion when it shouldn't have. I haven't tested them, but I'm assuming there's similar bugs relating to Frost Breath, Shell Armor and perhaps Lucky Chant.

**Comment by Marty-D** [comment]
Four of the five Pokemon that learn Storm Throw can also have Mold Breaker. I'm assuming it wasn't a Smeargle using it, so this isn't a bug. Please do not open issues here for bug reports, especially when they aren't actually bugs.

**Comment by DialaceStarvy** [comment]
Sorry, I was unaware of the Bug Reports thread (and didn't notice Mold Breaker).
