### ISSUE TITLE
Forcing the target to switch out will still show the switched-out Pokemon as "Active" on hover over

### ISSUE THREAD

**Issue by JsKingBoo** [Zarel/Pokemon-Showdown#1872]
This lasts for 1 turn

http://i.imgur.com/IiRf6Vt.png

**Comment by Rhythms88** [comment]
It does this because the next turn hasn't started yet iirc

**Comment by gamut-was-taken** [comment]
This is a [client][1] issue. I think the sidebar should be updated whenever a Pokemon gets dragged in, but currently that doesn't happen.

 [1]: https://github.com/Zarel/Pokemon-Showdown-Client

**Comment by JsKingBoo** [comment]
Alright, I'll try to close this issue and instead post it on the client issues page.

I've noticed some other oddities as well concerning the sidebar, though ;p

**Comment by Slayer95** [comment]
Fixed by https://github.com/kubetz/Pokemon-Showdown-Client/commit/001ea68fdd6d3acb03325e974be8fc14f2ed2ac2
