### ISSUE TITLE
[Feature Suggestion] Make the site compatible with the new 3dsxl browser

### ISSUE THREAD

**Issue by atommarvel** [Zarel/Pokemon-Showdown#1873]
Might be an interesting undertaking.

**Comment by Rhythms88** [comment]
and you couldnt put this in the smogon thread because...?

this isn't an issue
just wasted space

**Comment by kotarou3** [comment]
Feature suggestions also belongs in the issues section, so this is fine

**Comment by Zarel** [comment]
@Rhythms88, please don't insult people who are trying to help.

**Comment by Rhythms88** [comment]
At the time I thought I was just being responsive, but now, I see what you mean. Sorry @atommarvel and @Zarel :/

**Comment by Slayer95** [comment]
Apparently 3dsxl's browser has a good support of Canvas, but it's lacking in the EcmaScript department.

**Comment by atommarvel** [comment]
No problem @Rhythms88. Yeah I don't have a smogon account. I was playing around with the new 3ds's canvas capabilities and have been brain storming projects for it. [It runs this raycasting canvas demo surprisingly well! (use d-pad to move around)](http://3ds.atommarvel.com)

I've also had a lot of success with socket.io on it. 

I may take a look at what a 3ds-based pokemon showdown could be like for kicks some time.

**Comment by Zarel** [comment]
Looks like this is kind of dead. I don't really think enough people care about 3DS browser enough to investigate PS support for it specifically, so closing.
