### ISSUE TITLE
Update CSS sanitizer

### ISSUE THREAD

**Issue by xVeNoMiiz** [Zarel/Pokemon-Showdown#1903]
Many, if not all, CSS3 elements are not supported by the current sanitizer for registered servers. If the sanitizer could be updated to allow CSS3 elements that would be awesome. Some examples of unusable CSS3 elements are text-shadow, background-size: cover, transitions, and custom cursors.

**Comment by xVeNoMiiz** [comment]
oops, i might have posted this in the wrong place :(

**Comment by sirDonovan** [comment]
This belongs in the client repo, but it's already been reported https://github.com/Zarel/Pokemon-Showdown-Client/issues/248.
