### ISSUE TITLE
BW replays don't load BW animation sizes

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown#1905]
http://replay.pokemonshowdown.com/smogtours-gen5ou-62801

Most obvious with any flying mon.

I swore this was working fine before.

**Comment by Layell** [comment]
Just thought I'd post a bit more

http://replay.pokemonshowdown.com/gen5ou-261435204

this is a replay only bug, works fine in battle. If this should be moved to client let me know.

**Comment by Slayer95** [comment]
If you could close this issue here and reopen it in the client repository it would be great, @Layell
