### ISSUE TITLE
What database uses this project?

### ISSUE THREAD

**Issue by CoericK** [Zarel/Pokemon-Showdown#1916]
Hey i just met this project and i would like to test it by my self, what kind of data storage system is used in this project? 

Thanks in advance.

**Comment by kotarou3** [comment]
Flat file, mainly in CSV and JSON formats

**Comment by Zarel** [comment]
I would not like it to use `redis` and `mongodb` without detailed rationale. Flat files have plenty of advantages.

Also note that the login server uses MySQL.

**Comment by Zarel** [comment]
Also, this is not an issue. Issues are planned features, bugs, or implemented changes in need of review.

We have several other forms of contact: http://pokemonshowdown.com/contact

**Comment by kotarou3** [comment]
If we switch to something that isn't flat file, it would make the transition to a proper multiprocess server easier

**Comment by xfix** [comment]
I'm opposed to Redis and MongoDB myself. There is no reason to use them, really, and MongoDB is broken by design. If you are going to use database, let it be SQL other than MySQL, but the issue is that @Zarel wants Showdown to just work on Windows without needing to use Visual C++ (needed for SQLite) or installing additional software.

**Comment by kotarou3** [comment]
SQLite doesn't really play that well with simultaneous access from multiple processes, which is the main reason for switching to a database in the first place

**Comment by Zarel** [comment]
I actually don't care about Windows support _too_ much, but I'm not a huge fan of external dependencies in general, especially without a good reason.

I think an in-memory database might be useful for our in-memory text data, though. Would be a replacement for node.js/io.js's lack of a resizable buffer class. :|
