### ISSUE TITLE
Focus sash breaks from confusion damage

### ISSUE THREAD

**Issue by that4chanwolf** [Zarel/Pokemon-Showdown#1919]
As seen here in this test game: http://replay.pokemonshowdown.com/customgame-238107534
When my Deoxys-Attack was confused and hit itself, even though it was holding a focus sash, it still OHKO'd itself. Meanwhile, Bulbapedia says otherwise: 
![2015-06-04_429x255_scrot](https://cloud.githubusercontent.com/assets/1264392/7997718/c0e340de-0aff-11e5-93c4-17314e89d948.png)

While Bulbapedia might be wrong here as I have no real way to test this on cart, my guess is that Showdown gets this wrong. This is a scenario I discovered watching one of KyleCole's youtube videos (not sure which one) and decided to see if I could replicate it.

**Comment by ascriptmaster** [comment]
@Marty-D 

Anyways, can you find and link this KyleCole video you speak of?

**Comment by Marty-D** [comment]
Yeah this is true; I was working on fixing it months ago but then forgot about it. The recoil bit is wrong though.

**Comment by Zarel** [comment]
Yeah, I was sure Bulbapedia was wrong about recoil, but less sure about confusion damage.

**Comment by Zarel** [comment]
We should probably be implementing confusion damage as move damage.

**Comment by ascriptmaster** [comment]
So Sturdinja can't be stopped by confusion either? swell

**Comment by Zarel** [comment]
@Marty-D Is it hard to fix? Tell me what gens it affects and I can try to fix it myself.

**Comment by Marty-D** [comment]
@Zarel I can't seem to find the work I did on it, but I don't remember getting very far. If you'd like to fix it then by all means go for it! Implementing it as move damage sounds good, as long as subs don't take the damage for you, etc.

It affects all gens but 2. I tested Focus Band multiple times in Gen 2 with no success before checking the disassembly, and it appears that Focus Band only works when it's your opponent's turn, which is consistent with my results. (Focus Band does work on confusion damage in Gen 3-6 though.)

**Comment by Zarel** [comment]
Fixed.

**Comment by Zarel** [comment]
(in e656c83fbcb)

**Comment by Zarel** [comment]
Although, @ascriptmaster, do you want to write tests for this?

**Comment by ascriptmaster** [comment]
I might as well; I'm already thinking of rewriting part of Sturdy to allow Mold Breaker to not inherently block `Damage` events, thus allowing Magic Guard to work properly with Mold Breaker phazing.
