### ISSUE TITLE
Custom Game capping at 255 EV/stat

### ISSUE THREAD

**Issue by MandL27** [Zarel/Pokemon-Showdown#1933]
Me and a few others discussed on Showdown's IRC channel that Custom Game shouldn't still be capping EVs at 255 per stat, and when poking through the source code we noticed that said cap is native to the simulator, not the ruleset(s). Is it possible to move this to a ruleset?

**Comment by Slayer95** [comment]
Custom Game is Debug Mode. If the developer team gets a good case for allowing tests of in-game invalid EV spreads, we may eventually add it (read: it's possible), but there is no warranty either way.
