### ISSUE TITLE
Thousand Arrows crashes the /coverage command

### ISSUE THREAD

**Issue by KitKasai** [Zarel/Pokemon-Showdown#1998]
using /coverage thousand arrows causes the command to crash and display the 
"Pokemon Showdown crashed!
Don't worry, we're working on fixing it."
message.

**Comment by Slayer95** [comment]
Exactly

**Comment by Zarel** [comment]
Did you see the part that says "Don't worry, we're working on fixing it"? Don't report it, we're already working on fixing it. :|

To be specific, it's already fixed in this repository; the fix will the deployed as of the next restart tonight.

**Comment by KitKasai** [comment]
sorry for being rude
