### ISSUE TITLE
Visual bug with Trick and two Air Balloons

### ISSUE THREAD

**Issue by richardsun29** [Zarel/Pokemon-Showdown#2043]
Suppose a Pokemon is holding an Air Balloon and it gets popped. This Pokemon then uses Trick to take another Pokemon's Air Balloon. The second Pokemon still appears to have an Air Balloon, although the battle continues as if it doesn't have an item.
http://replay.pokemonshowdown.com/ou-247828762

**Comment by Zarel** [comment]
Sounds like a server issue, @ascriptmaster. We should probably be sending a blank item for the other Pokémon.

**Comment by augmt** [comment]
Given that the target is holding an item and the source Pokemon isn't, should the target undergo `-item` or `-enditem`?

**Comment by ascriptmaster** [comment]
Probably a client/server combination to handle blank items. I'll see what I can do.

**Comment by jrosa** [comment]
Hopefully PR #2247 fixes this

**Comment by Zarel** [comment]
Ugh, the fix I suggested would've worked fine. What's the problem with it?

**Comment by Zarel** [comment]
Blah, I just did it myself. fa7263eacdbe8
