### ISSUE TITLE
Pokémon Showdown doesn't use HTTPS

### ISSUE THREAD

**Issue by Ketsuban** [Zarel/Pokemon-Showdown#2052]
You can use HTTPS to visit the site itself, but that just means you get a mixed-content warning because everything is accessed through HTTP. From what little testing I did with HTTPS Everywhere (only the teambuilder) it's probably fully functional but it does have bugs.

* Bringing up a list of things (Pokémon, items, abilities, moves) and clicking an item in the list advances to the next screen as normal, but doesn't actually fill in the field.
* The only ability which is shown as legal is the one which is selected by default when selecting a Pokémon; to get another ability you have to specifically look for it by typing part of the name.
* The list will sometimes replace itself with the word "undefined" for no discernable reason. Generally adding or removing a letter in the name of the thing you're looking for brings it back again.

I'm not sure if this is only client-side bugs or if there's a server component, so I'll just report it here and let you do whatever with it.

**Comment by Zarel** [comment]
What browser is this? PS fully supports HTTPS on Chrome (which is incidentally a pain in the ass; did you know that Chrome doesn't fully support data URLs in HTTPS?)

The only mixed content we have is if a user puts an image into chat (mostly `<img>` in roomintros). Chrome gives a warning but allows them, since images aren't executable content and don't pose a security risk.

The issues you report seem unrelated to HTTPS. It's possible your internet connection failed to load a PS resource file. Does refreshing fix the issue?

**Comment by Ketsuban** [comment]
I'm using Firefox 39, which is also fine with mixed content like that—this is specifically using HTTPS Everywhere to force HTTPS even for HTTP resources, not just changing the protocol from http to https. End-to-end encryption is important anywhere that people engage in conversation for privacy.

**Comment by Zarel** [comment]
Turns out, this is because Firefox is giving the wrong error message:

http://stackoverflow.com/questions/24371734/firefox-cors-request-giving-cross-origin-request-blocked-despite-headers

Use Chrome for now, I'll look into updating the security certificate.

**Comment by Zarel** [comment]
Testing on Firefox 39: I can't reproduce any of your three bulleted issues, with or without HTTPS Everywhere installed. I continue to suspect a network issue unrelated to HTTPS.

**Comment by Zarel** [comment]
Nevermind, the issue I found while testing on Firefox didn't have to do with the security certificate, it was just an issue with my `/etc/hosts` file. I definitely can't reproduce in Firefox 39 in OS X, and @monsanto can't reproduce in Firefox 39 in Linux.

**Comment by monsanto** [comment]
@Ketsuban can you open the Network Inspector, reload the page, and pinpoint exactly which resource does not use HTTPS? as far as i can tell, every request is being made through HTTPS

**Comment by Zarel** [comment]
My leading hypothesis is that you have malware on your computer that's interfering with PS's HTTPS. You should probably do a malware scan.

**Comment by Ketsuban** [comment]
Yeah, I'm also not able to reproduce the issues I was having before. I can only assume uninstalling and reinstalling HTTPS Everywhere did the trick—I'm running Linux, so I'm reasonably certain there's no malware which could be interfering. Either way, thanks for prompt and thorough investigation.
