### ISSUE TITLE
Cloud Nine doesn't disable weather effects.

### ISSUE THREAD

**Issue by pranavanand123** [Zarel/Pokemon-Showdown#2076]
Tested with Sunny Day, the UI doesn't show anything to indicate that weather effects have been nullified when a pokemon with Cloud Nine is brought in. 

<img width="1057" alt="screen shot 2015-07-23 at 5 47 22 pm" src="https://cloud.githubusercontent.com/assets/6197214/8862993/f9a62812-3162-11e5-9413-c8d4b45c1ca1.png">

**Comment by ascriptmaster** [comment]
It disables weather effects, but doesn't show in the UI. Are you requesting us to add an indicator that the effects of weather are being suppressed?

**Comment by Slayer95** [comment]
We already give a lot of visual indicators for Air Lock being activated.
In-game, the weather visual effect is still active with Air Lock: https://www.youtube.com/watch?v=LZrhenGo1ZQ

**Comment by Zarel** [comment]
I think it might be nice to hide the visual weather effect, though. No reason for us not to be better than the games.

**Comment by Slayer95** [comment]
And what about keeping the effect as a reminder that there is an underlying weather? ;o

**Comment by Zarel** [comment]
Well, we still have the turn counter...
