### ISSUE TITLE
Lighting Rod / Storm Drain don't always redirect to the right Pokemon

### ISSUE THREAD

**Issue by ascriptmaster** [Zarel/Pokemon-Showdown#2083]
From @Marty-D's report, the order seems to be:

- Highest speed is targetted over any slower Pokemon
- If it's a speed tie, the first to enter the field is the one that is targetted

His report says that if the equal-speed Pokemon were all active for the same number of turns, the leftmost Pokemon is targetted or something.

**Comment by bumbadadabum** [comment]
Tried to fix this in PR #2154.
