### ISSUE TITLE
Implicit targets for chat commands

### ISSUE THREAD

**Issue by oopsies49** [Zarel/Pokemon-Showdown#2114]
While battling I often use the /data or /weakness commands to get more information about my own pokemon or the opponent.  It would make my experience much better if it was possible to have the targets be filled automatically to avoid having to type out the name of pokemon every time you want to use the command.

There could be some sort of alias system where @self or @opponent resolved to the pokemon currently on the field.

This could be extended further to have options like @self.abilities which would resolve to all the abilities your pokemon currently has.

**Comment by Slayer95** [comment]
I don't think this is needed... There are much better data features available on-screen via the UI.

We have a Suggestions thread in our forum btw.

**Comment by Zarel** [comment]
This is an interesting idea, but it might be a lot of work under PS's current architecture. Our mouseover menus cover most of the important stuff, and we're working on the rest.

**Comment by Zarel** [comment]
I'm going to close this because I don't think this will ever gets done, but if someone else wants to work on this, they can reopen it (or ask for a reopen, I don't know how permissions work on issues exactly).
