### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by snuggles08** [Zarel/Pokemon-Showdown#2131]
This might already be possible, but if not I would suggest adding it.

**Comment by Zarel** [comment]
You're going to need to be way more specific. What kind of whitelist?

**Comment by snuggles08** [comment]
User whitelist, only allow set registered users to join. Just realized *I* don't need it, but other people might.

**Comment by ascriptmaster** [comment]
`/modjoin` does the same thing, since you only need to room-voice the users on your "whitelist".

**Comment by Zarel** [comment]
We actually have built-in support for fine-grained versions of this. The config settings are:

- `Config.chatmodchat`
- `Config.battlemodchat`
- `Config.pmmodchat`

Which set the minimum ranks for each of these, at which point the voice rank can function as a whitelist.

**Comment by Zarel** [comment]
I suppose I should document this. pls hold

**Comment by snuggles08** [comment]
Update?

**Comment by Zarel** [comment]
pls continue holding

**Comment by snuggles08** [comment]
Still holding?

**Comment by Slayer95** [comment]
We will notify you.

**Comment by Zarel** [comment]
Done:

https://github.com/Zarel/Pokemon-Showdown/commit/165a667ec712e947c8935f3b45230ae902775867
