### ISSUE TITLE
pokemonshowdown.com/users/...

### ISSUE THREAD

**Issue by TheDiabolicGift** [Zarel/Pokemon-Showdown#2193]
Inaccurate authority, needs to be updated.

Examples: 
http://prntscr.com/8nc3ie
http://prntscr.com/8nc3wk
http://prntscr.com/8nc4a4

Thanks for reading!

**Comment by Slayer95** [comment]
Not sure what makes you think this is the place to report that, but fixed.

**Comment by TheDiabolicGift** [comment]
mb
