### ISSUE TITLE
Reject teams with incorrect shiny status rather than auto-changing

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown#2197]
This will prevent a lot of confusion

see: https://www.smogon.com/forums/members/zarel.102803/#profile-post-1830801

**Comment by Slayer95** [comment]
Anyone opposed?

**Comment by Zarel** [comment]
Not me.

**Comment by Layell** [comment]
Considering the amount of times I've been bothered by this now, it might be nice.
