### ISSUE TITLE
Staff are unable to unlock accounts

### ISSUE THREAD

**Issue by ChainsawPolice** [Zarel/Pokemon-Showdown#2215]
Recently, my account was locked, fairly and justly. This is not a unlocking appeal.
However, when a friend came to my place and tried to use the chatrooms in Showdown on his own account, he was promptly noted that his account was locked, assumedly due to him using his account on my internet connection and having it recognised as one of my alts.

Now, this friend's account was locked, and the lock would then travel with his username back to his home internet connection. So naturally, not wanting this to happen, I messaged a member of site staff, explaining the issue and asking for it to be rectified.

He mentioned that the system is not designed so that staff can remove associations between innocent usernames and guilty IP addresses, meaning that **my friend's account, on which no rules had been broken, had been locked simply due to accessing Showdown on my internet connection.**

Now, this is not acceptable. My friend would stay locked until the next server restart, despite doing nothing wrong at all – he's copping the flack for simply knowing me, more or less.

I guess this is a feature suggestion: add a feature allowing staff to remove associations between a set username and an IP.

The choice to write this system to ban all users on one connection **without prejudice** is absolutely insane and, frankly, is an incredibly poor design choice.

What about shared housing with one internet connection?
What about college campuses or school grounds?
What about dynamic IPs that get swapped around?

I understand that the problem occurs so little that it has flown under the radar for so long. But I assure you that it is affecting innocent users, and must be fixed ASAP.

**Comment by Slayer95** [comment]
Bad luck for your friend. This hasn't "flown under the radar".
It's on purpose and won't be changed.

**Comment by ChainsawPolice** [comment]
I understand it's on purpose. I'm saying that the system is incredibly poorly-designed if innocent users an get their account locked simply by being on the same internet connection as a currently-locked user, and the system should be changed.

**Comment by ChainsawPolice** [comment]
I understand it's on purpose. I'm saying that the system is incredibly poorly-designed if innocent users an get their account locked simply by being on the same internet connection as a currently-locked user, and the system should be changed.

**Comment by ChainsawPolice** [comment]
I understand it's on purpose. I'm saying that the system is incredibly poorly-designed if innocent users an get their account locked simply by being on the same internet connection as a currently-locked user, and the system should be changed.

**Comment by AustinXII** [comment]
@ChainsawPolice Changing that would be very unwise, if locks would just be stored on usernames people would be able to evade easier than it already is
