### ISSUE TITLE
Zoroark's event move (sludge bomb) is still shown as unlearnable.

### ISSUE THREAD

**Issue by memer5** [Zarel/Pokemon-Showdown#2250]
Basically the title. This applies both to the teambuilder and the !learn command.

**Comment by Slayer95** [comment]
Please don't open issues for Bug Reports.
Instead, refer to the PS bug reports thread in the Smogon Forums: www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/

**Comment by xfix** [comment]
Also, pretty sure the reason why it's not in !learn is that the server just wasn't updated for it.
