### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown#2269]
Please don't close this, we users can discuss how drible problems and make this possible.
My idea is to user can locally upload a theme for PS client. And any theme will be noticed of theme changes in PS code and will update. Too, PS can have a page for user download themes.
If this will happen, the initial themes I suggest is: Office 2016, iOS and Flat UI.

**Comment by Zarel** [comment]
Many people put themes on PS using Stylish.

We do not wish to officially support other themes, mostly because it hinders us during redesigns and adding features.

**Comment by Zarel** [comment]
I would say no to themes at this point, sorry.
