### ISSUE TITLE
Friends system

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown#2270]
My suggestion is to user can add friend and can see who friends are online. Too, can show images/videos on friend's private chat, and other semelhant features like Messenger/Whatsapp.

**Comment by AustinXII** [comment]
This is already under an open issue: https://github.com/Zarel/Pokemon-Showdown/issues/1736

**Comment by DaniellMesquita** [comment]
@AustinXII, please close this my issue as a duplicate.
