### ISSUE TITLE
Pokémon Showdown own Pastebin-like service

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown#2271]
Will be nice can upload a team or browse other uploaded teams directly from PS client.

**Comment by sirDonovan** [comment]
Please post your ideas in the suggestions thread in the <a href="http://www.smogon.com/forums/forums/pok%C3%A9mon-showdown.209/" target="_blank">Pokemon Showdown forum</a> instead of opening issues here.
