### ISSUE TITLE
Official support for clans

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown#2274]
Clan is a popular custom feature on some servers. The brazillian server http://indigo.psim.us is a example of server that uses this, and users appreciate very much. Clans are teams that battle against each other and earn scores. Will be nice if you can implement this feature on Pokémon Showdown officially.

**Comment by AustinXII** [comment]
You can use secondary servers for this, it has been stated many of times before that they do not want to have clan / league support.

**Comment by sirDonovan** [comment]
See https://github.com/Zarel/Pokemon-Showdown/issues/2271#issuecomment-156946190
