### ISSUE TITLE
Full/Offline client for platforms

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown#2275]
Some people (like me) have a poor connection with Internet, and can't download the client every time that want play. My suggestion is to make the platform-clients to work offline releasing full code, porting to NW.js/Cordova.
(At this present time this issue was wrote, the current version for Windows only uses an iframe to show the online Pokémon Showdown client).

**Comment by Zarel** [comment]
Technically, it's a WebView, not an iframe.

**Comment by Zarel** [comment]
For the most part, though, we update often enough that this feature isn't worth it.

For the things we don't update, caches exist. I'm not sure how much supplementing a browser's cache system can really do.
