### ISSUE TITLE
Certain combinations of past-gen egg moves are mistakenly considered legal

### ISSUE THREAD

**Issue by not-an-aardvark** [Zarel/Pokemon-Showdown#2287]
Example: In-game, it's impossible to legitimately obtain a Skarmory (in any generation) with the moves Defog, Brave Bird, Drill Peck, and Whirlwind. However, Showdown considers that combination to be legal.
- Skarmory can only learn Defog from the 4th-gen HM.
- The other three moves are 4th-gen egg moves, but they cannot be obtained together because nothing in Skarmory's egg group can legally know all three of these moves at the same time.

Note: The Murkrow/Honchkrow line has the same issue; it can learn Brave Bird, Drill Peck, and Whirlwind as egg moves in Gen 4, but it can't legimately know all of these moves simultaneously. It's possible that the Skarmory with these moves is considered legal because Showdown thinks that Murkrow is a valid parent, and vice versa, even though neither combination is legal.

**Comment by jakobw** [comment]
This is smilar to #2249. I tried to solve this in #2268 using the `rulesets.js` but it isn't really going forward. There was a suggestion to use the validator instead so maybe that's the way to go.

**Comment by Zarel** [comment]
I'm merging #2249 into here. The relevant observations from there:

> Eevee (to Sylveon) and Piloswine both evolve by knowing a certain move (any Fairy-type move and Ancient Power, respectively). This means they should only be able to pass on three other moves. However, this is not implemented in Pokémon Showdown.

> Relevant moves for Mamoswine are Tackle, Ice Shard, Flail, Amnesia and Fury Attack. The problematic moveset is Tackle, Ice Shard, Amnesia and Fury Attack. Icy wind is only an egg move in Gen5 where it is also a tutor move, so that's not an issue. Flail is only an egg move in Gen6 which we don't need to address.

> Relevant moves for Sylveon are Refresh, Bite, Growl, Take Down, Double-Edge, Trump Card, Baton Pass. If the three other moveslots are filled, then only one of Covet and Baby-Doll Eyes should be inherited.

> Theoretically, this could also apply to Ambipom, Lickilicky, Mr. Mime, Sudowoodo, Tangrowth and Yanmega, however, these Pokémon all have fewer than four moves exclusive to pre-evolutions.

**Comment by TheImmortal** [comment]
Another issue is with egg moves from Pokemon with baby prevos. For example, Pokemon with an egg move from Chansey and a level up move from Happiny is currently passing through the validator. The specific combo is Chansey with Seismic Toss and Charm. Thought you should know since you're working on this.

**Comment by Zarel** [comment]
Ah, yes, I have a list from Marty for the relevant mons: http://hastebin.com/raw/itukecovol

**Comment by Zarel** [comment]
Although n.b. I'm not working on this atm. As far as I know, it's not competitively relevant (Tackle Mamoswine?) so it's lower priority than the things on my to-do list.

**Comment by Marty-D** [comment]
Might as well put this here too: Shiftry with Leaf Blade + Sucker Punch currently passes but shouldn't. Leaf Blade is a level up move in ORAS for Nuzleaf only, while Sucker Punch is a Gen 4 tutor move for Shiftry only.

**Comment by TheImmortal** [comment]
@Zarel Another issue, ``7V`` moves in combination with future-gen pre-evo moves. Like aa331c2a73b83ea68c52a2e4838abaecdfc9cac2.

**Comment by Zarel** [comment]
I wrote a fix for prevo-only moves, but apparently it _only_ helps with NP/Surf Raichu. :/

**Comment by Zarel** [comment]
I'm also trying to think about making it easier to hardcode the weirdest of incompatibilities.

Currently, people are literally just adding them onto the banlists of various formats, which is just the worst way to do it. For one thing, it'll only affect one format, not all of them. At least put them on the `Pokemon` banlist. :\

**Comment by PlagueVonKarma** [comment]
Maybe make a general table for illegal combinations that people can add to, and then have it imported when checking for illegalities? It seems just as clunky as adding them into individual formats, but at least its all in one place and can be reviewed for every format instead. 

Not sure how else it can be done, though. Btw, sorry if I'm bad at explaining the idea. Never been my strong suit.

**Comment by Zarel** [comment]
Yeah, the "general table for illegal combinations" sounds like the best idea here. I'd probably just leave it in `team-validator.js`
