### ISSUE TITLE
Issue tracking: PS! edition

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown#2297]
I am working with Nineage to start thinking about creating an issue tracking system for PS! that would allow the average user to easily and effectively report bugs pertaining to relevant parts of PS!.  Here's the basics of what I was thinking along the lines of for the architecture:
``>user does /reportbug``
The client sends the user a popup with a form asking for information pertaining to the bug, such as...
- Title
- Description
- Category
- Evidence

After the user fills that information out, it will send this to the server, where the database of issues are stored. (TSV database like the existing local ladder system...?)

``>user does /viewbugs``
- A popup is displayed with all of the submitted bug reports.  The user has a drop down to sort by category.
- The user also has the option here to 'star' important and valid bug reports.
- Bug reports that have the most stars are sorted at the top of the list

And of course, there will be a certain rank that is able to delete reports based on the report number with ``/deletereport [report number]``

This is just a rough sketch on my idea of a issue tracking system, what does everyone else think?

**Comment by Zarel** [comment]
Do we currently support popup forms? I'd guess no. Imagine a popup form asking for someone's password... such phishing...

**Comment by Zarel** [comment]
Command-based just isn't a very good system...

**Comment by Slayer95** [comment]
Mandatory xkcd: https://imgs.xkcd.com/comics/standards.png

**Comment by Zarel** [comment]
tbh, we do need some sort of issue tracker... the biggest issue with existing ones is probably that they cost money, and I don't trust them not to have glaring vulnerabilities.

**Comment by panpawn** [comment]
Is it possible that this kind of form could only work client-sided?  That way, other servers cannot try to do another kind of popup form server-side?

**Comment by Zarel** [comment]
We could, but at that point we might want to write it entirely separate from PS or something.

One idea would be to host it outside of the main server, so vulnerabilities are less of an issue. My only issue with _that_ is that moderation/trolls could be an issue if it's disconnected from the PS login system.

**Comment by panpawn** [comment]
This is semi off topic, but did PS's old forums use PS login credentials?  I'm wondering if those could be optimized for bug reports...

Did those have a 'liking' or 'staring' feature by chance? (I don't remember)

**Comment by panpawn** [comment]
(I want to reemphasize how useful sorting reports by categories could also be very helpful)

**Comment by Zarel** [comment]
Yes, PS's old forums did. PS's old forums were also hacked. That's kind of why I said I don't really trust most third-party software these days.

**Comment by kotarou3** [comment]
bugzilla works fine for mozilla. No idea how well it works from a end-user perspective though.

**Comment by Zarel** [comment]
Now that we have #2367, we can just put approved mechanics bugs there. I'm fine with the current system for everything else.
