### ISSUE TITLE
Data/LogFiles of Every Battle in Pokemon Showdown

### ISSUE THREAD

**Issue by johnwu93** [Zarel/Pokemon-Showdown#2300]
Hi,

Is there a way to get a detailed description (i.e. the pokemon that each player selected, description of what happens in each turn) of all the battles that occur in the server? I would like to do do some analysis on this data.

**Comment by Slayer95** [comment]
We have a handy manifest file describing logging here https://github.com/Zarel/Pokemon-Showdown/blob/master/logs/logging.md

In the future, please ask questions in the thread for them in our forums https://www.smogon.com/forums/threads/3520646/, rather than in the issue tracker.

**Comment by Zarel** [comment]
I think he means on the official server, not on his own server.

In which case, Antar handles logging, and also please do not open issues here for that, GitHub is not a help service, it's an issue tracker.
