### ISSUE TITLE
Gen 3 should inherit data from Gen 4

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2304]

**Comment by Zarel** [comment]
Can we just update the inherit target, or does more need to be done?

**Comment by Slayer95** [comment]
Yes. The logic shared from Gen 5 <i>needs</i> to be removed. Ideally we would also remove the data duplicated with Gen 4.

**Comment by Zarel** [comment]
I don't understand. What logic shared from gen 5?

**Comment by Slayer95** [comment]
I updated the comment for clarity.

**Comment by Zarel** [comment]
Are you saying there exists logic shared between gen3 and gen5 that gen3 doesn't share with gen4? If yes, please clarify. If no, please clarify.

**Comment by Slayer95** [comment]
Yes. I don't know which things exactly. Otherwise I would have fixed this issue already :P

**Comment by Zarel** [comment]
We could just fix this and see what tests break and what bugs people report. Might be better than keeping this problematic long-term.

**Comment by Zarel** [comment]
Also, I don't need an answer immediately, but I do need an answer to this eventually:

https://github.com/Zarel/Pokemon-Showdown/commit/244f1700a0c168e27c67c5c83952644553815290#commitcomment-14726735

Since I need to know whether or not it's safe for me to revert.

**Comment by Slayer95** [comment]
I already answered that linking #649

**Comment by Slayer95** [comment]
Our current old-gen test suite isn't anything to rely on as a refactor guard :|

**Comment by Zarel** [comment]
I didn't see your link.

Hm, I guessssss we can keep doing it this way.

**Comment by Zarel** [comment]
Ugh, I want to fix this already. When does Smogon Tour end?

**Comment by Slayer95** [comment]
Fixed in https://github.com/Zarel/Pokemon-Showdown/commit/71249f48fe2b7440542f29f440c8e85a70e8854c
