### ISSUE TITLE
Genders can be hacked

### ISSUE THREAD

**Issue by TheImmortal** [Zarel/Pokemon-Showdown#2327]
It's possible to change any Pokemon's gender to male, female, or even genderless. The client (read: teambuilder) would also need to be updated to support this.

Definitely not important, but we might want to implement it eventually for the sake of following in-game limitations.

Proof: https://gyazo.com/5a6ae1f30ad090a52cdf1af2af8a1014

**Comment by Slayer95** [comment]
Should we default Pokémon to genderless?

**Comment by Zarel** [comment]
This isn't too hard to support, I think. Just stop validating gender in custom games.

**Comment by TheImmortal** [comment]
I think the current defaulting to random legal ability is fine, even in hackmons.

**Comment by hvk3** [comment]
Can I try and rectify this?

**Comment by Zarel** [comment]
Yes...

**Comment by TheImmortal** [comment]
This needs to be tested in previous gens. @Marty-D?

**Comment by Marty-D** [comment]
I assume it's possible to do in Gen 5, and maybe Gen 3 and 4 too, but if it is I don't know how to do it. What I do know is gender is tied to PID, and messing with it may have other effects on a Pokemon in past gens where the PID is used for more than just gender (such as Ability or shininess).

**Comment by Zarel** [comment]
This is now implemented for all gens.

Can you clarify re: gen 3-4? Presumably it's possible to generate random PIDs until you get one with the gender, ability, and shininess you want?

**Comment by Slayer95** [comment]
Closing. If specific information arises regarding past gens and PIDs, we shall deal with it then.
