### ISSUE TITLE
Make tournament players use the RoomGamePlayer API

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2331]
Refs https://github.com/Zarel/Pokemon-Showdown/commit/75e00170b47758071bd949a88722d75db0b793b4

Blocks #1826 (issue, not PR)

**Comment by Zarel** [comment]
Honestly, we can close #1826; this ticket tracks the only thing we have left to do for it.

**Comment by Slayer95** [comment]
I don't mind

**Comment by sirDonovan** [comment]
Done in https://github.com/Zarel/Pokemon-Showdown/commit/f9b5746c5e0842156659ed5f38906bddaeeecd25.

**Comment by Zarel** [comment]
I generally mention the PR if there's a PR: #2498
