### ISSUE TITLE
Pokemon sprite missing and can't select moves

### ISSUE THREAD

**Issue by Skyshayde** [Zarel/Pokemon-Showdown#2352]
I had just switched in Xerneas after Thundurus died and the sprite didn't show up.  I can't select a move or continue on either.  This just happened to someone I was battling earlier, but I didn't see it earlier today.  I posted the log below.  

http://play.pokemonshowdown.com/battle-vgc2016-312318026

I'm not really sure what else to say - I can offer more details if you need it.

**Comment by Slayer95** [comment]
What are your sprites and animations settings?

**Comment by Zarel** [comment]
Fixed.
