### ISSUE TITLE
Double Elimination tournaments having 2 'finals'

### ISSUE THREAD

**Issue by MaximeLemort** [Zarel/Pokemon-Showdown#2392]
Alright, I don't know if this is intended, or reported already (if this is, then all my apologizes.)

But when a Double Elimination tournament (for example, Ubers Double Elimination Tournament) happens, the tournament tree will run fine until the finals (aka, when the winner bracket and loser bracket join back), but then, the game will consider the finals to be a regular battle, and put the loser in a 'loser bracket', making the winner fight another game against the loser.

If my explanations aren't clear enough, maybe this screenshot of a tournament tree can show more detail.

Anyway, thanks for reading this, and I hope that it'll be corrected soon.

![tournament double elimination finals](https://cloud.githubusercontent.com/assets/14281111/12560925/8f1f8826-c39d-11e5-81b0-3c55b1ee619a.png)

**Comment by DanUgore** [comment]
It looks like it's working properly. BattleDomeGuy beat 1/8th in Winners Finals. 1/8th beat Enchidio in Losers Finals. 1/8th beat BattleDomeGuy in Grand Finals. This causes a "bracket reset" and they play the second set of Grand Finals.

That's what the bracket you linked looks like to me. If I'm wrong correct me but that is proper behavior.

**Comment by Zarel** [comment]
Yes, this is how double elimination is supposed to work. You are knocked out when you lose two games. So when the winners' and losers' brackets join up, the winners' bracket player needs to win once to win, but the losers' bracket player needs to win twice (since the first win just puts the other player into the losers' bracket).

**Comment by Zarel** [comment]
Please actually understand how doubles elimination works before reporting an issue.
