### ISSUE TITLE
/highlight doesn't seem to try to match certain special characters; instead acting like a regex.

### ISSUE THREAD

**Issue by Zazie-Lavender** [Zarel/Pokemon-Showdown#2408]
Noticed this when adding the string G+ to highlight list, would match 'g', 'gg' and any two letter combination beginning with 'g' would trigger the highlight.

**Comment by Zarel** [comment]
That's not a bug; `/highlight` takes a regex as its parameters.

Also this is the server repo, you were looking for the client repo.

**Comment by kotarou3** [comment]
Is the regex feature documented?

**Comment by Zarel** [comment]
Guess not. Maybe we should...
