### ISSUE TITLE
Victini Victory Star not working

### ISSUE THREAD

**Issue by josephjoestar** [Zarel/Pokemon-Showdown#2411]
The ability does not modifiy accuracy stat at all

This is the code in abilities.js

```
"victorystar": {
		shortDesc: "This Pokemon and its allies' moves have their accuracy multiplied by 1.1.",
		onAllyModifyMove: function (move) {
			if (typeof move.accuracy === 'number') {
				move.accuracy *= 1.1;
			}
		},
		id: "victorystar",
		name: "Victory Star",
		rating: 2.5,
		num: 162
	},
```

There is no onModifyMovePriority: in the code

**Comment by Slayer95** [comment]
Bugs are to be posted in the thread in our subforum in Smogon.

AFAIK, this issue is invalid. If your hace replay proof otherwise, please post it. (Hint: Victini must be active)
