### ISSUE TITLE
Custom Rules for Direct Challenges (Feature Request)

### ISSUE THREAD

**Issue by Ramanujamin** [Zarel/Pokemon-Showdown#2417]
The ability to add custom rules to random battles (eg. variable time between moves) when challenging other users directly would be nice. 

Willing to contribute for this.

**Comment by Zarel** [comment]
This has been planned for a while, but variable time between moves specifically seems weird. Just leave the timer off and keep track of time yourself, I'd suggest.

**Comment by TheImmortal** [comment]
I did this a while ago but Zarel never did the client bit https://github.com/TheImmortal/Pokemon-Showdown/commit/04bd89b008630337711430cd04f431912e4a5706

Feel free to update that whenever you get to it.

**Comment by Zarel** [comment]
You never pullreqqed the server bit. :|

**Comment by Zarel** [comment]
Are you saying it's done?

**Comment by TheImmortal** [comment]
Pretty sure I showed it to you when it was done. Yes, it was done according to your specifications.

> [22:03] ~Zarel: basically, it'll be a series of checkboxes
>[22:04] ~Zarel: team preview? enforce cartridge limitations? (checked = Hackmons) require legal pokemon? (checked = AG)
>[22:04] ~Zarel: which will be mapped onto a bitfield and converted to an integer
>[22:04] ~Zarel: team preview? 1; cartridge limitations? 1; legal pokemon? 0
>[22:04] ~Zarel: = 0b110 = 6
>[22:04] ~Zarel: so the format will be customgame6
>[22:11] ~Zarel: the hardest part is making sure you don't change other custom game formats that might be in progress
>[22:11] ~Zarel: i.e. you should make sure to clone objects rather than just copying the pointer

**Comment by Zarel** [comment]
Can you pullreq the server bit?

**Comment by TheImmortal** [comment]
#2420

**Comment by Zarel** [comment]
Superseded by #2420
