### ISSUE TITLE
Replay Weirdness

### ISSUE THREAD

**Issue by acz13** [Zarel/Pokemon-Showdown#2418]
The current replay code is really weird and a few things seem off:  

- Replay data contains exact HP, but only if the game is over. This is intentional (there's a comment in the code mentioning it). However, [the replay website](http://replay.pokemonshowdown.com/) doesn't have a way to view exact HP except for viewing the log directly and a very unobvious on-hover title on the percentage numbers. Is this not an information leak? It's pretty easy to find a team's EVs this way.  
- You can create replays in the middle of games. Isn't that just ridiculous?

**Comment by DanUgore** [comment]
Creating replays in the middle of the games is definitely an information leak.

**Comment by acz13** [comment]
Eh, the exact HP is not shown unless the replay is saved at the end of the game:  
```
if (room.battle.ended) {
	// If the battle is finished when /savereplay is used, include
	// exact HP in the replay log.
	logidx = 3;
}
```

**Comment by Slayer95** [comment]
> You can create replays in the middle of games. Isn't that just ridiculous?

No, it's not o_O

> Creating replays in the middle of the games is definitely an information leak. I don't see why the ability to do so is needed anyway.

The information is split, so there is no leak there...

> However, the replay website doesn't have a way to view exact HP except for viewing the log directly and a very unobvious on-hover title on the percentage numbers. Is this not an information leak? It's pretty easy to find a team's EVs this way.

There is no leak whatsoever regarding replays. If there is a leak there, it's regarding the percentages vs pixels issue, which doesn't concern this Issue Tracker, but Smogon Policy.

**Comment by acz13** [comment]
>>You can create replays in the middle of games. Isn't that just ridiculous?

>No, it's not o_O  

Why would you ever need to save a replay in the middle of a game?

**Comment by Slayer95** [comment]
For lots of reasons, and I have used that functionality more than the post-battle saves in the last year.

**Comment by Zarel** [comment]
> Why would you ever need to save a replay in the middle of a game?

The game could have crashed or experienced a bug preventing the game from ending. That's a pretty big reason to save a replay before the game ends.

> Is this not an information leak? It's pretty easy to find a team's EVs this way.

Do people not want their HP EVs known even after the game's ended? I suppose we could only save spectator-visible values instead of exact values, if enough people have a problem with this. Maybe we should poll it or something.

**Comment by acz13** [comment]
Sometimes it's not just the HP EVs but the amount of damage certain moves do. For example: I was playing a LC battle against a team I'd faced before. I purposely made a decision to switch because I knew the opposing Timburr had odd EVs and could KO my Lileep.

**Comment by DanUgore** [comment]
Ew this falls into another scouting issue. I guess if people have an issue
with it, it's definitely s point of interest. As long as no info is leaked
from the content of the current battle it's fine imo. Until we end up with
BoN tournaments in tournament mode anyway.
>
>

-- 
-- Hugh Gordon

**Comment by acz13** [comment]
Should this be moved to Policy Review?

**Comment by Zarel** [comment]
I don't think it needs to, I think we'll just remove exact HP information from replays.
