### ISSUE TITLE
listener sets ip as 0.0.0.0

### ISSUE THREAD

**Issue by AxeltheInferno** [Zarel/Pokemon-Showdown#2423]
Hello whenever I try to set up a server using the latest version the listener says the server is on 0.0.0.0:PORT  no matter what I do.

**Comment by kotarou3** [comment]
See `socket.js` on what config to change to set the bound address.

**Comment by Zarel** [comment]
This is an issue tracker, not tech support.

**Comment by Zarel** [comment]
We might want to document the bind address as `Config.bindaddress`, but I can't imagine anyone with a legitimate use for that setting being unable to describe their issue clearly. What exactly is the problem with listening on "0.0.0.0"?
