### ISSUE TITLE
[Feature Suggestion] Sort battles by Elo ratings

### ISSUE THREAD

**Issue by Mike766** [Zarel/Pokemon-Showdown#2428]
Elo ratings in "Watch a battle" list is a nice feature, but I want to see the battles with the highest Elo rating on top of the list.

I would highly appreciate if you could add a sort feature to the battle list, so that the battles with the highest Elo rating can be shown on the top.

**Comment by Zarel** [comment]
I've said many times that the problem is that instead of getting new battles, you get half-finished battles.

If you wanted to watch finished battles, the correct place to do that should be Replays, which is a feature I should probably build in, yes.

**Comment by Mike766** [comment]
Ok this would be great with replays, sorted by a combination of currency and highest rating. For example I would like to sort all replays higher than 1500 or 1600 by currency.

I think this would be a feature which is not only rather easy to implement but also very valuable for many users.

**Comment by Zarel** [comment]
A "filter" feature would be doable, yes. I might make such a feature.

**Comment by Mike766** [comment]
Thank you for your answers. Now I am sure that an ELO filter feature is exactly the right way to solve this problem!

This would be doable for both replays and current battles without violating the up-to-dateness principle.
