### ISSUE TITLE
Separate Validator into a separate module

### ISSUE THREAD

**Issue by Bardiches** [Zarel/Pokemon-Showdown#2448]
Since the class Validator in team-validator.js can act independently of the code around it, it would make sense to separate it out into its own file/module.

This would allow for the Validator to be able to be used more independently of the actual Showdown implementation and be especially useful in external projects seeking to leverage Showdown's team validator.

Should be an easy fix, I'm just not sure if there's a place in the repository structurally to put this besides making another file in the root.

**Comment by kotarou3** [comment]
The validator depends on the `Tools` class, which depends on the corresponding `data` files, so it's not as independent as you think

**Comment by Bardiches** [comment]
Yes but all of those can be used independently of Showdown's core functionality as a Showdown server. I've had great success using Tools/data without having weird dependency issues on "actual" Showdown code. The issue here is that using the team-validator.js module will always try to do very Showdown specific things, unlike tools.js or any of the data/ modules.

**Comment by Zarel** [comment]
Yes, I'm planning to make the process spawning opt-in, like I recently made sockets.
