### ISSUE TITLE
Volt Switch doesn't reveal properly on KO

### ISSUE THREAD

**Issue by Kuldr** [Zarel/Pokemon-Showdown#2568]
If you knock out with a volt switch it will not force the volt switch user to reveal their switch before the opponent switches their KO Pokemon in.

**Comment by Zarel** [comment]
What do you mean? I'm pretty sure PS doesn't do that...

**Comment by Kuldr** [comment]
I did it for me and a friend earlier in random battles.

**Comment by Kuldr** [comment]
I can test it tomorrow but I am not good at web stuff to fix it

**Comment by Zarel** [comment]
You have a replay link or something?

**Comment by Zarel** [comment]
This is the wrong place for such a vague bug, anyway; put it in http://psim.us/bugs

**Comment by Kuldr** [comment]
Sorry I will look into it and report back at the link
