### ISSUE TITLE
Ghost Pokemon Not Immune to Fighting

### ISSUE THREAD

**Issue by mimescd** [Zarel/Pokemon-Showdown#2570]
Didn't test it too extensively, but my gengar, drifblim, and dusknoir were getting hit by fighting moves.

**Comment by Marty-D** [comment]
[Scrappy](https://pokemonshowdown.com/dex/abilities/scrappy) exists. Please never open an issue here for things you didn't actually test or research thoroughly, and even then you should be posting them at http://psim.us/bugs instead (read the first two posts as well).

**Comment by mimescd** [comment]
I apologize sincerely!  I didn't think to check the forums.  First time
using the site today.  Thanks for the work!

On Sat, May 28, 2016 at 9:55 AM, Marty-D <notifications@github.com> wrote:

> Scrappy <https://pokemonshowdown.com/dex/abilities/scrappy> exists.
> Please never open an issue here for things you didn't actually test or
> research thoroughly, and even then you should be posting them at
> http://psim.us/bugs instead (read the first two posts as well).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Zarel/Pokemon-Showdown/issues/2570#issuecomment-222309790>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALe9eZEZ7P-jse6ysSjMOVn_k1JrYULAks5qGElDgaJpZM4IpE4s>
> .
>



-- 
Much Thanks,



Curtis D. Mimes
(513) 658 - 7123
