### ISSUE TITLE
Status damage doesn't show % of hp lost 

### ISSUE THREAD

**Issue by Ebinmaymayoverlord** [Zarel/Pokemon-Showdown#2579]
Unsure if it's working as intended, but I reckon that statuses show how much hp exactly you lost, since moves do it.

**Comment by Zarel** [comment]
You could ask instead of making an issue. :/

**Comment by Zarel** [comment]
Move damage are the only situation where percentage lost is shown in the game log.

In other cases, usually the percentage is already known, which makes the percentage lost redundant.

**Comment by Zarel** [comment]
blah misclick
