### ISSUE TITLE
Turns of status for toxic and sleep could be shown

### ISSUE THREAD

**Issue by 18vshanmugam** [Zarel/Pokemon-Showdown#2581]
As now, the client does not show turns for toxic and sleep. This information should be public, and thus shouldn't be an information leak; a human could count but it is an inconvenience. I believe past gens treat sleep differently, so it might change between gens. Additionally, it might be nice to see if sleep is rest-induced or not.

**Comment by Zarel** [comment]
Yeah, that's something we should probably do.

**Comment by acz13** [comment]
should this be calculated client side or served directly by the server?

**Comment by Zarel** [comment]
Calculated client-side. The server should never send anything not revealed by the games.

**Comment by acz13** [comment]
I'm having trouble thinking of a good mockup for this... perhaps it should be shown in the hover over pokemon window?

**Comment by QuiteQuiet** [comment]
I wasn't aware this issue existed, but should be done in https://github.com/Zarel/Pokemon-Showdown-Client/commit/36b409d9d98fa45ea0ce9949e66de3eb5b2cc993
