### ISSUE TITLE
Issues with partial trapping moves and Substitute in Generation 1

### ISSUE THREAD

**Issue by xCrystal** [Zarel/Pokemon-Showdown#2598]
Pointing these out here for whenever someone can get around fixing them. I don't recall 2. happening in the past so it might have been introduced recently.

1.
If an attack breaks a substitute, the damage dealt is effectively the damage that would've been dealt if there was no substitute up, rather than the damage actually dealt to the substitute. I noticed that it wasn't the case when I stumbled upon this:
![IMAGE](http://i.imgur.com/zRz2xvp.png)
Clamp should've kept dealing damage through the duration of the sequence as though the Substitute didn't exist. Instead, it kept doing damage equal to the HP the substitute had left.
I suspect this substitute damage error may extend to interactions with other moves such as Counter.

2.
I also had this happen. I used my last PP of clamp against a target, and then became locked into using Struggle until the sequence ended. It kept doing Clamp's first turn damage, but caused recoil and the wrong battle messages to be displayed. It can be seen in [this replay (turn 40)](http://replay.pokemonshowdown.com/gen1ou-391813905), but that's basically it. 

I think this second bug could be fixed by adding a separate check [here](https://github.com/Zarel/Pokemon-Showdown/blob/3acbe0a357e32ff0c98eff20064d755bddac17ec/battle-engine.js#L1612-L1616), where Struggle isn't assumed if generation == 1 AND user status is usingPartialTrappingMove. I think this would cover all scenarios and let the trapping move be continued properly but I'm by no means the expert here.

**Comment by scheibo** [comment]
This should now be fixed.
