### ISSUE TITLE
Modjoin should request confirmation when downgrading to default

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2614]
If modjoin is currently set to a certain specific level, usage of the raw ``/modjoin`` command will make it modchat-dependent, without feedback regarding this change.

**Comment by Zarel** [comment]
Done in cc942d440b1e06991338926eea0c91a2027aeed4

**Comment by Slayer95** [comment]
That fixes the common case shown as an example, but ``/modjoin on`` is still an unwarned downgrade if modchat is disabled.

I was thinking of something like the prevention of secret > hidden room downgrade:
``This room is a secret room. Use `/publicroom` to make it public, or `/hiddenroom force` to force hidden.``

Maybe I am overthinking it?

**Comment by Zarel** [comment]
We could rename `/modjoin on` to `/modjoin modchat` or something?

**Comment by Slayer95** [comment]
I like that.
Biggest issue with that would be players who often just ``/modjoin on`` in their ladder matches (or actually, just ``/modjoin``).

**Comment by Zarel** [comment]
they could do `/modjoin +`?
