### ISSUE TITLE
Generation mods should not contain data from any proceeding generations

### ISSUE THREAD

**Issue by taylor1791** [Zarel/Pokemon-Showdown#2642]
`mods/gen1/pokedex.js` includes many evolutions that do not exist in generation 1 alone. Take this an example of Electabuzz. It includes both his pre-evolution and his evolution, neither exist in gen1. Does the Pokémon showdown team consider this a bug, if so can I submit an MR to remove all of these [pre-]evolution from the generation 1 mod?

A quick inspection showed that this may affect the validator and a few other places. Is there anything I should be aware of before I dive in?

**Comment by Zarel** [comment]
I'm not sure if this is really a bug. It shouldn't affect the validator or anything I can think of.

**Comment by taylor1791** [comment]
Correcting these entries would open doors for other projects to use Pokemon-showdown as a library. I imagine that other projects could use Pokemon-showdown as the source of truth for the Pokemon and evolutions that exist. Since pokemon-showdown implements the differences between generations, it makes it possible to swap the battle rules mid-game to a different generation. That is pretty cool.

While fixing it does not remove a bug, I think the data would be "more correct" if it was fixed. This would facilitate broadening the use cases of pokemon-showdown.

I have no problem making an MR with the changes. I just want to be sure that my time will not be wasted.

**Comment by Zarel** [comment]
Okay, that's fair. I don't see any harm in removing them.

@Marty-D?

**Comment by Marty-D** [comment]
Technically every other generation does that as well, so there's no reason to do this unless they get their own `pokedex.js` file instead of inheriting from the gen above it. That's what *should* have been done here too, and not recreating the same data Gen 2 has while only changing 3 or so fields.

**Comment by taylor1791** [comment]
In an effort to make sure I do not miss anything, I am going to make a proposal. I suspect that I will be missing something or add unnecessary work. Please let me know if there is anything incorrect in this process. 

The process is divided in to 2 MRs. The first will address Marty-D comment as well reduce the amount of work involved in MR 2.


MR 1

1. Create `gen3/pokedex.js` where the only contents are `exports.BattlePokedex = {}` (and `'use strict'`).
2. Create `gen2/pokedex.js` where the only contents are `exports.BattlePokedex = {}` (and `'use strict'`).
3. Change `gen1/pokedex.js` use `inherit: true` to remove duplicate fields inherited from gens 2-6.

MR 2

1. Remove evolutions introduced in gen6 from `gen5/pokedex.js`
 1. Add an entry in `gen5/pokedex.js` for `eevee` using `inherit: true`, but changing `evos: ["vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],`
2. No changes to `gen4/pokedex.js`, since gen 5 introduced no cross-generation evolutions.
3. Remove evolutions introduced in gen4 from `gen3/pokedex.js`
  1. The entries for `magneton`, `lickitung`, `rhydon`, `tangela`, `electabuzz`, `magmar`, `porygon2`, `togetic`, `aipom`, `yanma`, `murkrow`, `misdreavus`, `gligar`, `sneasel`, `piloswine`, `nosepass`, `roselia`, `dusclops` will be `inherit: true, evos: []`.
   2. Add entry for `eevee`using `inherit: true` and `evos: ["vaporeon", "jolteon", "flareon", "espeon", "umbreon"]` 
   3. Add entry for `snorunt` and `kirlia` using `inherit: true` with `evos: ['glalie']` and `evos: ['gardevoir']` respectivly.
   4. Add entry of `prevo: null`, while using `inherit: true` for `chimecho`, `roselia`, `sudowoodo`, `chansey`, `mrmime`, `snorlax`, `mantine`
4. Remove evolutions introduced in gen3 from `gen2/pokedex.js`
 1. Add entry of `prevo: null`, while using `inherit: true` for `maril`, `wobbuffet`
5. Remove evolutions introduced in gen2 from `gen1/pokedex.js`
 1. Add entries for `golbat`, `onix`, `chansey`, `seadra`, `scyther`, `porygon` will be `inherit: true, evos: []`.
 2. Add entry for `eevee` using `inherit: true` and `evos: ["vaporeon", "jolteon", "flareon"]`
 3. Add entry for `gloom`, `poliwhirl`, and `slowpoke` using `inherit: true` and `evos: ["vileplume"]`, `evos: ["poliwrath"]`, and `evos: ["slowbro"]` respectivly.
 4. Add entry of `prevo: null`, while using `inherit: true` for `pikachu`, `clefairy`, `jynx`, `electabuzz`, `magmar`, `jigglypuff`, `hitmonchan`, `hitmontop`, `hitmonlee`

Remaining questions:

1. {Do, we need to do anything, Should we do something} to prevent lower generations from inheriting the actual pokémon from the next generation? For example, inheriting `heatran` in gen3, gen2, and gen1.
2. What kinds of tests do we expect for these changes?

**Comment by Marty-D** [comment]
Well, for Gen 4's `pokedex.js` you'd also need to remove every single Hidden Ability if I'm understanding your desire for fully accurate data correctly. Plus remove any Abilities introduced in Gen 4 from Gen 3, etc.
Either way, it just seems like a lot of work for little benefit since anyone using this database for another project would theoretically know everything you outlined already, and cherry-pick accordingly.

Ultimately though I don't have a preference which way it's done as long as everything still works. @Zarel can be the final judge here.

**Comment by taylor1791** [comment]
That is a good point that I overlooked. I have started to make a list, but I have yet to double check it. Just to give you an idea of the size of the list there are about 75 abilities that change from generation. Would you like this in MR 2 or as 3rd and seperate MR?

**Comment by taylor1791** [comment]
If you are still mulling my proposal over, I understand and encourage you to take your time. If you have made a decision, can you give me the go ahead to get started on MR 1?

**Comment by Zarel** [comment]
This isn't really necessary, you can autogenerate these things by e.g. removing every evolution that's in a future gen...

**Comment by Zarel** [comment]
PS doesn't have "pure" past-gen data anyway, it's all inherited down so I think people should already know to do that kind of auto-filtering if they want to extract past-gen data from PS...

**Comment by Zarel** [comment]
So I guess in the end, the answer is no. You have to post-process all PS past-gen data, asking someone to do `pokemon.evos.filter(pokemon => Tools.getTemplate(pokemon).gen === 1)` isn't very hard.
