### ISSUE TITLE
Separate Battle{,Side,Pokemon} and process communication

### ISSUE THREAD

**Issue by taylor1791** [Zarel/Pokemon-Showdown#2655]
`battle-engine.js` does two things. It defines `Battle`, `BattleSide`, and `BattlePokemon` factories and it also starts listening for messages from other processes. This makes it impossible for other projects to use the battle factories without 1) being on Node and 2) listening for IPC.

Would you accept a PR that splits `battle-engine.js` into two files? If so, do you have a preference for the file names?

**Comment by Zarel** [comment]
Yes, splitting it into two files is a good idea. Actually probably move the process stuff into `simulator.js`.

**Comment by taylor1791** [comment]
Currently, `battle-simulator.js` is spawned as a child process by `simulator.js`. I don't have a problem moving them into the same file, but I wanted to confirm that was your intention. If so, would you prefer I detect the child process by looking for `process.send` or spawn the child with an environment variable?

**Comment by Zarel** [comment]
Yes, it would work like all the other process managers.

**Comment by taylor1791** [comment]
Resolved by #2666
