### ISSUE TITLE
Error when doing "nodejs app.js"

### ISSUE THREAD

**Issue by miquelp** [Zarel/Pokemon-Showdown#2692]
Hi, I've tryied to set up the app on my Ubuntu system, but when I try to set the server up with nodejs after doing **npm install**, I get the following error:

> $: /pokemon-showdown/app.js:49
> const fs = require('fs');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3

My Nodejs version is v0.10.25. 
I sincerely don't know what's going wrong, since I barely touched Nodejs before, so I need some ideas on why I could be having this issue. Thanks in advance.

**Comment by Slayer95** [comment]
Node.js 0.10 is unsupported by the Pokemon Showdown project.
It's stated in the README

> (Requires Node.js 4+)

**Comment by miquelp** [comment]
Thanks, I missed that part. It's working now.
