### ISSUE TITLE
Inconsistent use of extension when `require`ing js files. 

### ISSUE THREAD

**Issue by taylor1791** [Zarel/Pokemon-Showdown#2722]
When examining `simulator.js`, we see that both `ProcessManager` and `BattleEngine` use require without specifying the extension. `const ProcessManager = require('./process-manager');` However, later on in the file, `crashlogger.js` is required with the `js` extension. This is inconsistent.

I think that it should be consistent across the project. If we chose to leave off the extension, individuals can take advantage of their tools resolution system to resolve the file differently. This allows developers to "override" files that highly dependent on the platform.

Suppose I want to use `battle-engine.js` in the browser and I have a webpack config that resolves `es6` files with higher priority than `js` files. I can now override `require('./crashlogger')` in `Battle.prototype.leave` to my own implementation as I choose. I can use a similar method to create a `tools.es6` that has all `this.data` built into it and define `global.Tools` for `battle-engine.js` to run in the browser. 

If the developers think this is a good idea, I am willing to make a PR with the changes.

**Comment by Zarel** [comment]
Sounds good.

**Comment by Morfent** [comment]
One note I want to add is that if you're making a require for a node script that also shares a name with a directory, node will attempt to require ``index.js`` within that directory first, then the node script iirc. I don't think PS has any directories like this though, so it should be fine.
