### ISSUE TITLE
CAP pokemon appearing in Doubles UU tier Team builder.

### ISSUE THREAD

**Issue by shivamshekhar** [Zarel/Pokemon-Showdown#2747]
I noticed this while making my DUU team. I chose the DUU format for my team and then proceeded to add the pokemons. Surprisingly, I found that pokemon from the CAP tier were also present, however they aren't allowed in DUU. So, kindly look into this. I don't think this is a big issue, but however, must be resolved to make it more precise.

**Comment by Zarel** [comment]
Fixed.
