### ISSUE TITLE
Follow user

### ISSUE THREAD

**Issue by d9h02f** [Zarel/Pokemon-Showdown#2762]
Would be great to be able to temporarily (until you close the tab or something) follow a certain user: as long as you're following them the view automatically switches sides so that you're on the side of the user you're following. Maybe add some kind of notification if they start a new battle as well, which immediately opens the new battle if you click on it (or even automatically open any new battles they start?). I think it makes sense to have it so you can only follow one user at a time.

Right now if you're trying to follow someone's battles you have to click on their username and then on the next battle they're in, and half of the time you have to click to switch sides as well, the proposed feature would make it easier to just sit back and enjoy the show.

**Comment by Antar1011** [comment]
This seems like an awesome tool to help facilitate harassment and ghosting.

**Comment by bumbadadabum** [comment]
I already get quite a lot of PMs with "someone is following me around and
revealing my sets to my opponent". I don't like this idea.

**Comment by d9h02f** [comment]
If moderators can't take care of stupid people, what are they doing?

**Comment by d9h02f** [comment]
Alternatively, this could be part of the buddy system (https://github.com/Zarel/Pokemon-Showdown/issues/1736) where you first need to add each other before this feature becomes available. This would be a second best option I think.

**Comment by Zarel** [comment]
Not a bad idea as a friends list feature.

Users already get creeped out about strangers following them enough that I don't want to make it any easier, though.
