### ISSUE TITLE
Polls no longer accept multiline arguments, specifically on Main

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown#2774]
<img src="http://image.prntscr.com/image/8846b84a589e4663bfcf7cb97a971373.png">

I can't reproduce this issue on other servers with the same multiline code. (of what's currently on GitHub, that is)

I'm not sure if this has to do with a commit that wasn't pushed yet, or what, but they're broken.

**Comment by panpawn** [comment]
Note: roomintro multiline arguments seems to be working fine, this seems specific to polls.

**Comment by Zarel** [comment]
Fixed; it was some broken code in `private.js` that override `poll new` to let the Dev room make HTML polls.

**Comment by panpawn** [comment]
This doesn't seem to be fixed to me.

**Comment by Zarel** [comment]
Apparently it was fixed but not hotpatched; it worked fine after hotpatching.
