### ISSUE TITLE
Battle simulation Abilities Cloud Nine should still display status of the weather

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown#2802]
When I run `npm test`, this happens:

  `1) Battle simulation Abilities Cloud Nine should still display status of the weather:`
     `Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

**Comment by panpawn** [comment]
[Relevant code](https://github.com/Zarel/Pokemon-Showdown/blob/67da1a122140794ed26b7a465e8d83d33e81d2af/test/simulator/abilities/cloudnine.js#L85-L96)

**Comment by UkokuSZ** [comment]
Is this already fixed? I didn't see this message when running npm test.

**Comment by Zarel** [comment]
I also haven't found a way to recreate this. Closing.
