### ISSUE TITLE
Team Validation Doesn't Validate Natures

### ISSUE THREAD

**Issue by Antar1011** [Zarel/Pokemon-Showdown#2815]
http://replay.pokemonshowdown.com/ou-450612221

Might need to pull up the server log to see it, but that Amoonguss' nature is "Love". I assume this gets parsed by PS as equivalent to Hardy. But seems like it should be getting checked.

Does anything else not get checked? Can I set happiness to Blue?

**Comment by Antar1011** [comment]
Looks like if you have give an invalid value to happiness it gets parsed as null. http://replay.pokemonshowdown.com/ou-450631801

**Comment by Antar1011** [comment]
Looks like IVs/EVs get sanitized.

**Comment by Antar1011** [comment]
I also found a log from April where the Pokemon didn't have an ability, but I can't reproduce that now.

**Comment by Zarel** [comment]
This explains the crashes we just had... apparently the validation still isn't perfect.

**Comment by acz13** [comment]
Is this solved?

**Comment by Zarel** [comment]
Yep
