### ISSUE TITLE
1 issues and 1 question.

### ISSUE THREAD

**Issue by Ericpro06** [Zarel/Pokemon-Showdown#2869]
Today, I am really excited because I can make my own server of Pokemon-Showdown. But there is 2 things that I wanted to talk about. First, how can I be an Administrator? I followed what the file said, but in my 'config' folder there is no 'usergroups.csv'. And the second thing is not an issue, it's a question. How to add a new Pokemon in my server? (I know it's possible but I don't know how to add the texture)

**Comment by AustinXII** [comment]
1. Read ''readme.me''
2. You'd have to add it in the relevant data server code (start with ''/data:pokedex.js'') then you'd have to add the sprite on your custom client (if you have one set up)

**Comment by Zarel** [comment]
The issue tracker is not meant to be used for tech support.

**Comment by Ericpro06** [comment]
What should I do with the '/data:pokedex.js'? Sorry for late reply, I had to go to

**Comment by panpawn** [comment]
>To become an Administrator, **create** a file named config/usergroups.csv

**Comment by Zarel** [comment]
You could if you found a bot to play against; we don't provide bots built-in.

**Comment by AustinXII** [comment]
@Ericpro06 by "it" I meant "new Pokemon data."

**Comment by Ericpro06** [comment]
@panpawn I noticed it already. @AustinXII Yeah, I know what it is. What I want to know is how do I install it.
