### ISSUE TITLE
HTML displayed during pokémon battle.

### ISSUE THREAD

**Issue by arp001** [Zarel/Pokemon-Showdown#2876]
![screen shot 2016-11-05 at 3 48 57 pm](https://cloud.githubusercontent.com/assets/15954001/20033100/9eb40958-a36f-11e6-9c94-157edc1574cc.png)

As you can see, the HTML code is being displayed during the battle. This is a specific case when **the opposing pokemon has shadow tag and the user tries to switch.**

**Comment by panpawn** [comment]
I think this might be a client issue, as opposed to a server issue, although I am not certain

**Comment by SecT** [comment]
> I think this might be a client issue, as opposed to a server issue, although I am not certain

You're probably right, there has been a change just yesterday in this fragment of the code:

https://github.com/Zarel/Pokemon-Showdown-Client/commit/84e69bf1e8bd0f72879efd06ce92d094a3678cb4

**Comment by Zarel** [comment]
Already fixed.
