### ISSUE TITLE
Duplicated moves in random battles

### ISSUE THREAD

**Issue by omegablitz** [Zarel/Pokemon-Showdown#2879]
It seems that it's somehow possible for moves to be duplicated in random battles - I tried searching for the bug but couldn't find:
![screenshot from 2016-11-01 01-18-44](https://cloud.githubusercontent.com/assets/7580561/20034514/d55a3b68-a396-11e6-8e55-a956d4e0416d.png)

**Comment by arp001** [comment]
I've created a pull request for this defect. 

[https://github.com/Zarel/Pokemon-Showdown/pull/2880](url)

**Comment by TheImmortal** [comment]
This was accidentally caused by bc49845604fe14770337b8f5a5437721f5c66c20 and fixed as soon as it was reported in 21cd59d2f8a250cb6b02bfa36d5cbc323e533ebf.
