### ISSUE TITLE
Sockets: Golang rewrite and optimization

### ISSUE THREAD

**Issue by Morfent** [Zarel/Pokemon-Showdown#2943]
1. The array of sockets is already stored internally in Golang as `map[string]*sockjs.session`, and I don't want to duplicate that internal map, considering it has the exact shape as what I wanted. Since Golang has the "unsafe" module, the alternative is get the raw pointers for `sockjs.session` and `sockjs.handler` and make them free for me to use. Which is the better way of handling this?

2. Unit tests are provided by `go test`. The also allows benchmarking, which is imperative considering I'll need to compare whether or not `sockets.go` can handle server load better than the current implementation of `socket.js` 

3. Why don't the static servers support hosting over HTTPS? If there's no problem with it, I could implement it, since Golang can host it using both protocols.

**Comment by Zarel** [comment]
1. I would prefer to duplicate that map, but if you want to do it yourself, it's not a huge deal.

2. ...ok?

3. they can if you want I guess, we just don't use it for anything

**Comment by Morfent** [comment]
> I would prefer to duplicate that map, but if you want to do it yourself, it's not a huge deal.

I didn't want to keep the additional map since i don't want to risk a desync between the two at any point. 

>they can if you want I guess, we just don't use it for anything

Ok. I'll keep it, on the rare chance it ends up being used. If not, it's a one-liner to remove.

**Comment by Morfent** [comment]
This would probably work better as a way to discuss what, if anything could be improved or fixed from the old implementation, considering this issue as is isn't much more than asking for help as it stands.

**Comment by Zarel** [comment]
Basically the only improvement is to fix bugs in SockJS-node or whatever else is likely to be the problem.

**Comment by Morfent** [comment]
I think if there are any problems with channels/sockets/subchannels, they should quickly end up apparent. When I wrote the socket multiplexer without mutex, I ended up with sockets deleted before channels, crashing since the `socketID` it was given didn't exist. With mutex, that stopped happening. That makes me wary of the current implementation, given it seems to ignore that, say, multiple messages being parsed by a worker at the same time might not always give the right answer.

...though I should really unit test that to check

**Comment by Morfent** [comment]
The way I thought of dealing with sockets/channels/subchannels ended up working out pretty badly, since only two workers at best could mutate the struct containing them concurrently. Creating a map using the parent's mock worker IDs and the structs I used would allow all workers to run concurrently while still keeping that behaviour when it comes to the structs themselves, which should be a pretty large improvement over coupling them to the workers like they were in sockets.js.

Internally, Node cluster uses a net server to deal with IPC. In our case, it was using TCP handles, so I'll be using that as well unless there are better alternatives that work cross-platform. In sockets.js, I'm putting the workers map and the net server in a `WorkerManager` class, which alongside `Worker` will keep track of all state in the module. This also makes it possible to unit test sockets.js, since neither the net server nor the child process are created until `Sockets.listen` is called.

**Comment by Morfent** [comment]
SockJS will only be supported on IE8 or IE9 if cookies are enabled, since sockjs-go doesn't support XDR streaming. RFC6455 is the only standard of Websocket protocol supported, so IE6-9, Chrome 6-13, Firefox <10, Safari 5, Opera <12.10, and Konqueror cannot use Websockets for SockJS connections. I may add support for these myself if this becomes a problem.

Config.ssl.options will need to be modified. In Go, HTTPS servers are launched using the paths to the cert and key files, rather than their contents like in Node.

**Comment by Zarel** [comment]
None of those tradeoffs sound unacceptable. The real question is if it'll fix our major problems.

**Comment by Morfent** [comment]
What are the major problems you're thinking of?

So far, I've only encountered two problems: race conditions related to Users/Rooms methods that send messages to the child process out of order, and connections not being properly closed if the child process panics. Both are relatively straightforward to solve, though.

**Comment by Zarel** [comment]
Our biggest problem is probably random disconnections, and also `websocket-raw` connections that don't close because they have no keepalive system.

**Comment by Morfent** [comment]
This should fix the deal with `websocket-raw` connections, since websocket connections in sockets-go use hearbeat messages like every other transport does.

As for the random disconnects, I'm not positive what may be causing them. It could be sockets being prevented from sending heartbeat messages on time because of its worker's IO being starved, `raw-websocket` transport sockets receiving invalid JSON messages and killing themselves (which they actually do), or just a bug in certain sockjs-node transports.

**Comment by Morfent** [comment]
I'm thinking of splitting sockets.go into a package of a few files for the modularity the file needs pretty badly at the moment and the boost in server startup time from the way Go handles compiling packages compared to compiling sockets.go every time the server launches. Would it be fine to do this?

**Comment by Zarel** [comment]
Sure.

**Comment by Morfent** [comment]
- The rewrite causes some race conditions that were either already present, but failed silently before, or are caused directly by the rewrite because of slight differences in IPC timing. I'm using this as an excuse to write proper unit tests for more of `Connection`/`User`/`Room`-related code so I can try to catch them before this would go into production
- I don't want to leave it to the user to manually deal with Go dependency management, since they have no reason to need to care about sockets.js so much just to run PS. I'm thinking of creating scripts to run on `postinstall`/`postupdate` hooks to handle that automatically, rather than cramming it all in the launch script to deal with every time. On the other hand, I could create an npm package to handle that on its own since it's not something PS would ideally concern itself with. What would be more preferable?
- I'm referring to sockets/channels/subchannels as socket muxing from here

**Comment by Morfent** [comment]
>- I don't want to leave it to the user to manually deal with Go dependency management, since they have no reason to need to care about sockets.js so much just to run PS.
Never mind, this can be worked out for the most part using [vendoring](https://blog.gopheracademy.com/advent-2015/vendor-folder/). I still want a `postinstall` script to fetch Go dependencies for the first time, but it shouldn't install Go itself. The launch script can check if any updates to the `sockets` and `main` packages I'm splitting sockets.go into are needed.

**Comment by Zarel** [comment]
I would strongly prefer for your code to be able to handle either Go or Node.js sockjs-server processes. We could then default to Node, and then we wouldn't need to support installing Go dependencies automatically.

**Comment by Morfent** [comment]
That's sounds more reasonable. I'll add a config setting for that

**Comment by scheibo** [comment]
Is this still something still being worked on, or can it be closed?

> SockJS no longer has the perf issues that were plaguing us when I suggested this, making this migration overall no longer worth it.

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/issues/2444#issuecomment-481981699_

**Comment by scheibo** [comment]
Please reopen if this is still being worked on.
