### ISSUE TITLE
Validate egg moves for Pre-Bank formats

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2954]
[00:16] CelesteelaVGC: http://pastebin.com/Dy5a5JYC
[00:16] CelesteelaVGC: these egg moves aren't legal on cart until pokebank is released

**Comment by Slayer95** [comment]
Maybe we can have new learnset source categories, since the Pokebank / pentagon business is probably here to stay, say:

``7E``: Can be learnt through breeding, no restrictions.
``7EP``: Can be learnt through breeding, requires Pokebank parents (or, in general, forward gen trade)

**Comment by Zarel** [comment]
Nah, we just need to interpret "no valid parent" as "not a valid egg". Not really that hard afaik.

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/1d6ac79158e13506434c58b53353bc82c3d0959e/team-validator.js#L792

This line just needs to be replaced with a rejection (i.e. `continue`) in the case of tiers with the possibility of unavailable egg moves.

**Comment by Slayer95** [comment]
Isn't that the expensive way?

**Comment by Zarel** [comment]
That's more expensive, you can cache a list but it should probably exist outside of learnsets.js

**Comment by Slayer95** [comment]
Fixed in eed37b63b27bf and badbc1f193
