### ISSUE TITLE
Add a way to identify status moves run in their Z variants

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2955]

**Comment by Slayer95** [comment]
Possibly

```js

let zMove = this.getMoveCopy(move);
zMove.isZ = true
```

**Comment by Zarel** [comment]
That was my solution, yes.

**Comment by Slayer95** [comment]
What about ``.id`` and ``.name``?

In a semi-related note, should ``Tools.getMove('zbatonpass')`` return something of the form ``{isZ: true, exists: true, ...}`` ?

**Comment by Zarel** [comment]
I see no reason to support that in `getMove`

**Comment by Slayer95** [comment]
This is fixed. The getMove() issue can be discussed in a different context.
