### ISSUE TITLE
Oricorio's dancer: bug on petal dance

### ISSUE THREAD

**Issue by linkzeldagg** [Zarel/Pokemon-Showdown#2974]
Oricorio will can only use petal dance after using a copy of petal dance by other pokemon (like Lilligant).
In Sun/Moon, oricorio could use other move after using a copy of petal dance.

e.g.
Lilligant's petal dance!
Oricorio->dancer: petal dance!
Oricorio's Hurricane!

==Next turn

You can only select 1 move named "petal dance" on Oricorio (which she cannot learn).
(In Sun/Moon, oricorio could use something other here, like hurricane etc.)

**Comment by Zarel** [comment]
Do you have a YouTube video or something proving that's how it works?

**Comment by linkzeldagg** [comment]
I'm sorry that I cannot provide you a YouTube video or something else to prove that.
But I think that this problem could be easily reproduced by creating a team with oricorio and a lilligant, then using petal dance on lilligant and see what happened.

I'll post here as soon as I could provide something to show how it works.

Thank you =D
(im really like oricorio lol)

**Comment by Wendit** [comment]
I see what linkzeldagg meant. Basically Oricorio get locked in petal dance move after triggering petal dance with its ability. In actually sun/moon game, Oricorio will not get locked in it. 

Video to these behaviors:

PS: https://youtu.be/4E8gISYmsJU
Sun/Moon: https://youtu.be/v9XZPqjpPEE

**Comment by acz13** [comment]
I realized that the way that Showdown handles `dancer` is pretty broken. I'm busy right now and without a 3DS to check mechanics but I think there are more interactions with dancer and locking moves (see bulbapedia)

**Comment by Tigerball890** [comment]
@acz13 working on testing taunt and dancer right now, yeah, it is pretty broken (should use `runMove` instead of useMove)

**Comment by Zarel** [comment]
It occurs to me that `runMove` and `useMove` are named entirely backwards. :/

Maybe they should be named `useMove` and `useMoveEffect` or something.

**Comment by Zarel** [comment]
`tryMove` and `useMove`?

**Comment by acz13** [comment]
Dancer interaction with locking moves is still not totally fixed...

**Comment by Zarel** [comment]
You're going to need to be way more specific and provide a replay or something.
