### ISSUE TITLE
If you run /data in a format it doesn't always give the correct data

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Zarel/Pokemon-Showdown#2980]
By this I mean if you are in a game mode (let's say gen 1 randoms for fun) and you run the command /data it will give the data for the most recent gen.  It would make more sense if it would return the relevant data for the game mode that is being played.

**Comment by Slayer95** [comment]
This is a [client-side](https://github.com/Zarel/Pokemon-Showdown-Client/) issue.

The [/data commands](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/battledata.js#L470) should probably call the ``renderXRow`` functions in [search.js](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/search.js) somehow,

The gen number can be read as ``room.battle.gen``, where ``room`` is an instance of ``BattleRoom``, but we don't currently pass that as an argument to ``parseChatMessage``...

**Comment by Zarel** [comment]
No, this is a server-side issue.

The server should render the data tables instead of making the client render them as is currently the case. Would clean a lot of unnecessary code out of client and also offer better compatibility in general (`!dt` currently fails in replays because replays don't load data table code).

**Comment by asgdf** [comment]
If only the server should render the data, how would the teambuilder show move/item/pokemon data?

**Comment by Zarel** [comment]
...using search.js?

I'm saying the server should render the data separately. There are enough differences between teambuilder rows and `!dt` entries anyway (the latter should have links, for instance)

**Comment by Zarel** [comment]
#3378 fixes this, I presume

**Comment by Zarel** [comment]
#3378 did, in fact, fix this
