### ISSUE TITLE
Gen7 Random Battle: Kangaskhan with power-up punch

### ISSUE THREAD

**Issue by Wendit** [Zarel/Pokemon-Showdown#2984]
Kangaskhan cannot learn power-up punch in Gen7. However Kangaskhan with power-up punch still shows up in Gen7 random battle.

**Comment by Slayer95** [comment]
PuP Kangaskhan is just unreleased due to the current absence of Pokebank.
We are fine with unreleased and even some illegal movesets (due to incompatibilities) in Random Battle.
