### ISSUE TITLE
Unable to continue battle after fainting (Pursuit/Mega bug)

### ISSUE THREAD

**Issue by chtref** [Zarel/Pokemon-Showdown#3010]
http://replay.pokemonshowdown.com/gen7pokebankou-494453294

What happens is the following:

> Turn 1

> Opponent Mega Evolves his Charizard into Mega Charizard Y, then Solar Beam on the Rotom
> Rotom lives the hit and uses Volt Switch, goes to Metagross

> Turn 2

> Metagross Mega Evolves and uses Pursuit on the Mega Charizard Y, who decides to stay in and lives the hit
> Mega Charizard Y goes for Fire Blast, KOing Mega Metagross.

Afterwards, the Metagross player is left with exactly two options: Skip turn, and Skip to end. Both buttons do absolutely nothing and the room is stuck. In other words, this is a game-breaking bug.

**Comment by Zarel** [comment]
This is something my choice refactor will eventually fix, but I don't see a need to keep this issue open since there's not really enough information in this issue to do anything with.

**Comment by Slayer95** [comment]
Fixed in 16a6de258c6fdacac4
