### ISSUE TITLE
Gen 1 Tox status attributed to current opponent, instead of actual source

### ISSUE THREAD

**Issue by leviroth** [Zarel/Pokemon-Showdown#3028]
If Pokémon A uses Toxic on Pokémon X, and then Pokémon A is switched out for Pokémon B, the subsequent combat log will say:

>Pokémon X is hurt by the opposing Pokémon B's tox!

…where it should say:

>Pokémon X is hurt by the opposing Pokémon A's tox!

This can be seen, for example, in turns 34 and 35 of [this battle](https://gist.github.com/leviroth/cbf55d5cd08043caa7c439f145482af3). One Chansey has been badly poisoned by another Chansey. However, after the poisoner has been switched out for a Gengar, the log message is "Chansey is hurt by the opposing Gengar's tox!"

I just noticed this, so I'm not sure if it applies to other status effects.

I am interested in fixing this, if I can find my way around the codebase.

**Comment by Zarel** [comment]
...you need to save a replay and link to a replay. Battles expire after ten minutes.

**Comment by leviroth** [comment]
D'oh.

Replay can be found [here](https://gist.github.com/leviroth/cbf55d5cd08043caa7c439f145482af3).

**Comment by Zarel** [comment]
@Marty-D 

Here's the replay hosted online: http://watchman-paula-74646.bitballoon.com/

Those messages can't be accurate, can they?

**Comment by leviroth** [comment]
I'm still seeing the bug when I run the latest source.
