### ISSUE TITLE
Custom Game: Fix imprison bug

### ISSUE THREAD

**Issue by Tigerball890** [Zarel/Pokemon-Showdown#3067]
In Custom Game, if you have more than one of the same moves, and you use it while it is disabled by Imprison, instead of saying "_Pokémon_ can't use its sealed _move_!", it will wait until the move is executed to say it can't be used, as if the opposing Pokémon just used Imprison that turn.

**Comment by Zarel** [comment]
1. do you have proof that the games don't work this way?
2. you shouldn't use "fix" in the issue title unless you are the one doing the fixing

**Comment by Zarel** [comment]
I'm going to close until someone provides video (e.g. YouTube) proof that this is how it works, or someone like @Marty-D confirms that this is how it works.

**Comment by Tigerball890** [comment]
Ok, sorry if I'm being kind of annoying. Don't mean to, just thought this was something that should be fixed.
