### ISSUE TITLE
Bottle caps

### ISSUE THREAD

**Issue by TheImmortal** [Zarel/Pokemon-Showdown#3073]
Bottle caps are an important part of the game and should be near the top of the todo list. They affect event Pokemon, transforming, moves that copy other moves (Copycat -> Hidden Power), and possibly other stuff that I don't know.

Client: I think the best thing is for the teambuilder to have a column next to IVs to set bottle caps. There just needs to be a check box next to each IV because you can only maximize them.

**Comment by Zarel** [comment]
What specifically is wrong with the current implementation? Can you be much more specific?

Also: I was told that you could set IVs to anything. You can only maximize them?

**Comment by TheImmortal** [comment]
Bottle caps don't change IVs. They just trigger a flag which makes stat calculations use 31. Your IVs remain intact and bottle caps only maximize.

**Comment by Zarel** [comment]
Are your original IVs relevant to anything in-battle other than Hidden Power?

**Comment by Zarel** [comment]
From https://www.smogon.com/forums/threads/hidden-type.3591194/#post-7168256 -

> Is this really relevant to non-mods, though? Just set any 30 IV to 31 for your OM. I don't really think something that will never come up outside of mods (i.e. this isn't even relevant to AG or Hackmons) should be worth modding the teambuilder for.

I think I'd rather have a Hidden Power type selector than a checkbox next to every IV, anyway.

**Comment by ascriptmaster** [comment]
Sounds good to me. However, because bottle caps only max the stat, we need to update the validator to check hidden power legalities if the IV is below 31

**Comment by Zarel** [comment]
We already do...?

**Comment by TheImmortal** [comment]
They are only relevant to Hidden Power as far as I know. The Hidden Power type selector sounds fine.

**Comment by ascriptmaster** [comment]
@Zarel no, we don't. I can absolutely set a Pokemon to have 30 in all IVs (IVs should make it HP Fighting) and still have any other Hidden Power when I waltz into OU. This link is using HP Fire but with 30-all. http://replay.pokemonshowdown.com/gen7pokebankou-510856243

**Comment by TheImmortal** [comment]
Also event Pokémon with fixed IVs don't work correctly because of your current implementation. Once you have this HP type selector implemented, I will update the validator to fix events.

**Comment by Zarel** [comment]
What's wrong with my current implementation re: event pokemon?

**Comment by TheImmortal** [comment]
You allow any IVs with any Hidden Power... Fixed IVs means fixed Hidden Power.

**Comment by Broken-Phobias** [comment]
I thought this was Fixed though. I have fought with Pokemon with certain Iv's and it all turns out to be Dark HP even though in team builder it said HP Electric for example.

**Comment by HoeenCoder** [comment]
Yeah ive seen that working, but for bottle caps this could be a bit tricky. A few ideas:

- Like TI said have a way to mark a IV as `maxed by bottle cap`. When validating HP type, legends needing 3 perfect IVs use the selected IVs, otherwise use `31` (possibly just switch the IV to 31 after validating)

- Refactor the HP validator to check to see if the HP is legal with the IVs marked `31` allowed to be any number (0-31). If the HP type selected is legal, use it, if not use the current setup to select a valid HP type (asusme no bottle caps)

**Comment by Zarel** [comment]
Okay, so, for the packed team:

I kind of want to implement it the dumb way, by adding HP type and ball after the EVs.

So the EVs which are currently, say,

`|4,252,,,,252|`

would become

`|4,252,,,,252,flying,quickball|`

The main advantage of doing it this way is to be backwards-compatible with old official implementations of `fastUnpackTeam`. The main disadvantage is that it's weird to look at, but honestly, packed teams will always look weird.

**Comment by Zarel** [comment]
We could also have them as comma-separated after happiness, or even `|`-separated after happiness, which would still be backwards compatible but would require more code for backwards compatibility.

**Comment by Zarel** [comment]
Comma-separated after happiness would be relatively simple and readable code, backwards compatible, and not being complete "wtf" material the way stuffing things after EVs would be, while trading off a small amount of performance that's probably unnoticeable. I think I'll do it that way.

**Comment by Zarel** [comment]
402bb7bd84b7d

I ended up doing comma-separated after happiness. Feel free to code-review.

**Comment by Zarel** [comment]
Mostly done in 2d6bd87c0bcca657

**Comment by architdate** [comment]
I think this issue is fixed with the oras validator + allowing 31 in any stat right? Or am I missing something here?

**Comment by Zarel** [comment]
This issue is fixed for all official formats. It's not fixed for OMs, where someone might want to specify a Hidden Power type separately from IVs.
