### ISSUE TITLE
Bug with Illusion

### ISSUE THREAD

**Issue by Tigerball890** [Zarel/Pokemon-Showdown#3089]
Two replays as source: http://replay.pokemonshowdown.com/gen7mixandmega-515426963 and http://replay.pokemonshowdown.com/gen7balancedhackmonssuspecttest-515429157, plus Quite Quiet can verify. 

In BH Replay: Swampert has illusion, mega evolves into Mega Swampert, illusion doesn't wear off. (Permanent illusion) Plus, when Swampert fainted, it showed Solgaleo as being dead. 

In MAM Replay: Zoroark has illusion, mega evolves into Gyarados, illusion wears off. 

IDK if this is intended or not, but definitely not real game mechanics.

**Comment by Zarel** [comment]
Unfortunately, we can't do anything without

1. a description of real game mechanics
2. proof of some sort, such as a link to Smogon Research, a YouTube video, etc

**Comment by Zarel** [comment]
If you can provide those things, though, we will of course reopen this issue!

**Comment by Zarel** [comment]
In the future, you might want to use Bug Reports, where our staff can assess real game mechanics for you: http://pokemonshowdown.com/bugreports

It's just GitHub where we don't allow incomplete bug reports.

**Comment by Tigerball890** [comment]
I'll look into this, or ask Marty to see if this is the real mechanics.

**Comment by Tigerball890** [comment]
@Zarel is bulbapedia regarded as a reliable source for bugs because if so I just found another one

**Comment by Zarel** [comment]
Bulbapedia is not regarded as a reliable source for bugs, but can sometimes be a useful starting point. If you're going to cite Bulbapedia, though, do it in Bug Reports rather than here.
