### ISSUE TITLE
Don't use status moves successfully when taunted

### ISSUE THREAD

**Issue by Tigerball890** [Zarel/Pokemon-Showdown#3101]
Pokemon with Dancer can use status moves successfully even when taunted if copied through dancer. According to http://bulbapedia.bulbagarden.net/wiki/Dancer_(Ability), this should not happen. Also, http://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/page-9 post 204 confirms this. I have fixed this, and will create a pull req for it after my current one is closed.

**Comment by Tigerball890** [comment]
Line 88 of scripts.js in my copy of Showdown: 
		```
if (pokemon.volatiles["taunt"] && move.category === "Status") {
			this.add('cant', pokemon, 'move: Taunt', move);
			return;
		}
```

**Comment by Marty-D** [comment]
Fixed in https://github.com/Zarel/Pokemon-Showdown/commit/920006281950e44e34c6da40785a3d923533a096
