### ISSUE TITLE
Reference formats by unique identifier 

### ISSUE THREAD

**Issue by Antar1011** [Zarel/Pokemon-Showdown#3201]
When Pokebank was released and gen7pokebankou was renamed gen7ou (ced6a88ddea26748d24e7c42b7ed35f699d6c92e),  it made it extremely difficult to figure out which battles of format "gen7ou" are pre- and post-bank. 

This is probably the most important example, but there are also cases where one would want to know whether a log is from before or after a tier shift, suspect test or new release. None of that is possible when the only thing that denotes the battle's format is the format name.

Luckily, this is a solved problem: basically, every variation on every format should be given a unique ID. That is, something gets banned, it gets a new ID. Tier gets renamed, totally new ID. It's way easier to combine than to separate. 

How this ID gets generated, and how it's looked up, I leave as implementation details (if you want suggestions, I'll be happy to provide), but yeah, this goes near the top of my "want" list.

**Comment by Zarel** [comment]
in theory, you can generate it yourself from datestamp and format ID, right?

**Comment by Antar1011** [comment]
But I have no way of knowing precisely when a format switched over. PS doesn't auto-restart when you commit changes to master, does it?

**Comment by Zarel** [comment]
In theory just look for the last gen7pokebankou game, and that's a pretty good timestamp to use.

You can also look for hotpatches around that time.

**Comment by xfix** [comment]
I wonder if it would be feasible to have a version field for each format, like:

```
version: 1,
```

which gets incremented each time a change is made, and is included with all replays.

**Comment by Antar1011** [comment]
Formatid + version would indeed define a unique identifier. 

I'd actually suggest instead of numerical version use either timestamp of last format change or--better--commit hash. 

To simplify further, just include the PS version (commit hash) in the logs! That also accounts for changes resulting from bugfixes or mechanics changes.

**Comment by xfix** [comment]
Commit hash is feasible, but I want to point out that main server doesn't have the same commit hashes as the Showdown repository itself, due to changes that aren't in repository proper. 

The question I assume is that you want to know if a given commit is before or after commit where certain big change occurred. For this question to be answerable, you need to know the entire tree of commits (which is completely different to the one in repository, due to changes that weren't pushed).

I suppose this can be handled, I just wanted to point a small issue out.

**Comment by yuzeh** [comment]
I want to add my support for adding some sort of versioning mechanism to the replays.

Right now, I'm trying to reconstruct gen7randombattle matches from the seeds. This is definitely doable by guestimating a commit based on the timestamp, but it'd be much nicer if the server hash (or the hash of the most recent common ancestor of the server with the PS repo) were provided.

**Comment by Zarel** [comment]
Commit hash is not a bad idea, honestly...

**Comment by yuzeh** [comment]
I'm happy to take the lead on this.

Where are good places to put the hash? I can think of:
* server logs (key-value pair "version": "<hash>")
* replays (hidden input field?)

**Comment by Zarel** [comment]
I'm in the middle of refactoring PS's sim to the new Streams API, at which point I would put the replay log and the input log in separate places.

One idea would be to put it above the log, prefixed by `>` rather than `|`.
