### ISSUE TITLE
Networking tests are noisy and flaky

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#3215]
See e.g. https://travis-ci.org/Zarel/Pokemon-Showdown/builds/198710235 [[Gist](https://gist.github.com/Slayer95/914c1b7577023163a8baaa42e34ce1fc)]

**Comment by Zarel** [comment]
Let's disable them?

**Comment by Morfent** [comment]
I'll make them get skipped until I work out a way to make the workers both shut up while the tests are running. I think closing workers' stdout pipes might work. I'll look into why the tests that require IPC for eval are crashing so the crashlogger can shut up as well.

**Comment by Zarel** [comment]
Fixed in #3235

**Comment by Morfent** [comment]
It seems like this is related to what version of Node's being run. Using v6.2.2 like Travis was, the messages finally showed up, but I haven't been able to get them to appear on v7.5.0. I'll need to look into what changes have been made between those versions to find out what's causing this.

**Comment by Zarel** [comment]
That explains it; I was on Node 6.0.0
