### ISSUE TITLE
Apparently Surge Surfer is broken

### ISSUE THREAD

**Issue by uar-matias-laino** [Zarel/Pokemon-Showdown#3217]
It's been quite a few times that I tried the duo Tapu Koko + Raichu, if you lead with Koko in the back then switch it in, Raichu doesn't double it's speed until next turn I think. This doesn't happen in the actual game, is there a bug?

**Comment by ascriptmaster** [comment]
Do you have a video of proof?

**Comment by ascriptmaster** [comment]
@Marty-D paging to confirm or deny

**Comment by uar-matias-laino** [comment]
@ascriptmaster no, I don't at the moment but I can have a friendly battle with a friend and upload the replay, it happened at least 3 times to me, all when having raichu on the field and switching to koko.

1. Non Scarf Garchomp was able to use earthquake before Raichu's move, when Koko was switched in (Raichu should have attack first as electri terrain was kicked in)
2. Salazzle faked out before Raichu when Koko was switched in (Raichu should have attack first as electri terrain was kicked in) (this happened 2 times)

I can probably replicate both scenarios later today.

**Comment by uar-matias-laino** [comment]
@ascriptmaster maybe I missunderstood, do you need proof on the console? Or on showdown?

**Comment by ascriptmaster** [comment]
I want both. Or at least console verification.

Also Fake Out always goes first, so no speed change from Electric Terrain will ever change that.

**Comment by uar-matias-laino** [comment]
I know that, but Raichu's fake out should go first since it becomes the fastest on the field. I will provide proof today.

**Comment by Marty-D** [comment]
This is false; you just don't understand how turn order works. Under no circumstances will turn order change when a weather/terrain effect starts _during the turn_. Please do not make issues on GitHub for unverified claims, that's what the [bug reports thread](http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/) is meant to weed out.

**Comment by uar-matias-laino** [comment]
@Marty-D although you are correct that my issue is invalid (something I've verified a couple of hours ago) it is not entirely true, given prankster abilities grants priority on the turn order and switching to lele voids that priority, so please, be more gentle when rejecting an issue. Having said that, I apologize for the missinformation.

**Comment by ascriptmaster** [comment]
Psychic Terrain negates the attack itself due to having priority, and does not "void the priority" as if it changes the turn order, so it's different. It's more like how switching in a Pokemon with Insomnia "voids" a sleep move that is used against it.

**Comment by Zarel** [comment]
Correct me if I'm wrong, but Tapu Lele prevents Prankster moves on its switch-in turn, right? That would only be possible if the move's priority was still +1, which means its priority hasn't been voided at all.
