### ISSUE TITLE
Switching to HTTPS

### ISSUE THREAD

**Issue by FelixRilling** [Zarel/Pokemon-Showdown#3224]
While this is not directly related to this repo, I could not find a better place to post this.

Are there plans to move the main server and the website to HTTPS? SSL certificates can be gotten for free using [letsencrypt](https://letsencrypt.org/) for example. While security might not be the biggest issue for Pokemon Showdown, a lot of browsers started treating unencrypted connections with lower priority. Additionally, [HTTPS tends to be faster](https://www.httpvshttps.com/).

I could help with the transition as I have some experience with switching from HTTP to HTTPS.

**Comment by kotarou3** [comment]
We already support HTTPS: https://play.pokemonshowdown.com/ - it's just not the default.
For some reason, Zarel doesn't want to make it the default

**Comment by Zarel** [comment]
(The reason is that HTTPS drastically decreases the amount of ad revenue we have – to only 30% of HTTP revenue – and we are barely affording our bandwidth as-is.)

**Comment by Zarel** [comment]
One thing we could do is use HTTPS on the login page specifically. This would require weird tricks, though. Feel free to contribute said weird tricks: the client repository is open-source and available at:

https://github.com/Zarel/Pokemon-Showdown-Client
