### ISSUE TITLE
Accuracy boosts aren't correctly capped to 255 in 1gen/2gen

### ISSUE THREAD

**Issue by FredrIQ** [Zarel/Pokemon-Showdown#3226]
For 2gen, relevant for Brightpowder. For 1gen, relevant due to the 1/256 miss chance.

**Comment by Zarel** [comment]
@Marty-D, can you confirm/deny?

**Comment by FredrIQ** [comment]
GSC's code for reference, confirming this is what the game does: https://github.com/pret/pokecrystal/blob/master/battle/effect_commands.asm#L2001

Also note how checking Brightpowder is performed after applying stat changes (this makes sense since GSC's Brightpowder is additive)

**Comment by Marty-D** [comment]
Fixed in https://github.com/Zarel/Pokemon-Showdown/pull/3926.
