### ISSUE TITLE
GSC confusion damage doesn't apply damage boost from type boosting items

### ISSUE THREAD

**Issue by FredrIQ** [Zarel/Pokemon-Showdown#3229]
It does in the original game: confusion damage calls HitSelfInConfusion which sets up attack/defense after Reflect/level/move power, then calls the normal DamageCalc routine. This routine will, among other things, look at the move type of the currently used move and potentially apply type boosting items (despite the damage originating from a confusion self-hit!). Note that only type boosting items are affected by this quirk; the only other thing DamageCalc looks at that confusion shouldn't apply is critical hits, but CriticalHit isn't set at this point.

**Comment by Zarel** [comment]
@Marty-D, if you can confirm, add this to Mechanics Bugs?

**Comment by FredrIQ** [comment]
Also, one thing I wasn't sure if I read correctly from this engine's source code, but something PO did incorrectly in a similar bug on their end was apply damage rolls (which is incorrect in at least 2gen) and also ignored Reflect (which is wrong). I found this engine's code a bit less straightforward to follow here so I'm not sure how PS handles it, but just to make it clear: GSC confusion accounts for Reflect in defense, stat changes, type boosting items, but not damage rolls.
