### ISSUE TITLE
Multiple forme changing abilities can be copied or overwritten but shouldn't be

### ISSUE THREAD

**Issue by asgdf** [Zarel/Pokemon-Showdown#3230]
Battle Bond, RKS System, Shields Down and Power Construct can currently be copied by Trace and overwritten by Entrainment and the like. As per [the research thread](http://www.smogon.com/forums/threads/3586701/page-51#post-7112730) I'm reasonably confident that this behavior is faulty. Doing this as an issue instead of a PR since I'm not really sure which abilities exactly shouldn't be copied and which ones shouldn't be overwritten, sources seemed to disagree.

**Comment by acz13** [comment]
More research needed on this one?

**Comment by Zarel** [comment]
@Marty-D

**Comment by Marty-D** [comment]
Research is "happening" in https://github.com/Zarel/Pokemon-Showdown/pull/3245

**Comment by asgdf** [comment]
Any updates on this? Jc since I still occasionally get reports about these abilities being overwritten. Is it worth doing a preliminary fix for the cases where we already know that can't happen?
