### ISSUE TITLE
Spore causes Sleep in Electric Terrain/Misty Terrain

### ISSUE THREAD

**Issue by Honoo** [Zarel/Pokemon-Showdown#3238]
The user was a dry skin Parasect targeting a Prankster Murkrow.

Example: http://replay.pokemonshowdown.com/gen7vgc2017-534259158

**Comment by Zarel** [comment]
Terrains only affect grounded Pokémon. Murkrow is not normally a grounded Pokémon.

In the future, please use Bug Reports for game mechanics you don't understand: http://psim.us/bugs

This repository is not meant to be used for unresearched game mechanics. If you do not have research (in the form of Smogon Research threads or YouTube videos), please do not submit issues to our repository.

**Comment by Honoo** [comment]
Ok, thanks for the clarification.
