### ISSUE TITLE
Moves that bypass Dig will still not bypass Fly in GSC when locked on

### ISSUE THREAD

**Issue by FredrIQ** [Zarel/Pokemon-Showdown#3307]
Showdown doesn't reflect this.

**Comment by Marty-D** [comment]
You'll have to be way more specific. As far as I know Fly and Dig already behave the same way with Lock-On and Mind Reader.

**Comment by FredrIQ** [comment]
Sorry, I misread Showdown completely then, the issue is actually the exact reverse -- Showdown is being too lenient.

Basically, in GSC, moves that bypass Fly still bypass Dig when locked on, but not the other way around -- Earthquake/Magnitude/Fissure will still always miss against someone using Fly.

**Comment by Marty-D** [comment]
Oh I see, thanks!
