### ISSUE TITLE
New Sheer Force and Shield Dust mechanics

### ISSUE THREAD

**Issue by Marty-D** [Zarel/Pokemon-Showdown#3339]
- Sheer Force boosts Anchor Shot, Genesis Supernova, Sparkling Aria, Spirit Shackle, and Throat Chop and removes their effects despite not having a secondary effect/chance in their move data.

- Shield Dust prevents Anchor Shot, Spirit Shackle, and Throat Chop's effects (but not the others mentioned above).

There are probably a number of ways to accomplish this so let's discuss the best ones.

**Comment by ascriptmaster** [comment]
We could just throw them into the secondaries with 100% proc rate using the `onHit` handler like Tri Attack, and add some sort of flag for Sparkling Aria and Genesis Supernova so Shield Dust doesn't block it. Unless they have some sort of different priority such that Poison Touch always activates before/after it, guaranteed.

**Comment by Zarel** [comment]
Clarify "despite not having a secondary effect/chance in their move data"?

**Comment by Marty-D** [comment]
@ascriptmaster Ah yes, I forgot Tri Attack already set a precedent for this kind of thing. Thanks, that sounds like the simplest option then. (Tempted to name the flag `dustproof` though!)

@Zarel I was referring to the game data for moves. Looking again, I guess Throat Chop might have a case, but partial-trapping moves are also categorized as "Damage + secondary effect" with 100% chances and those aren't affected by either Sheer Force or Shield Dust. I'm suspecting some hardcoding happened for these, and that's kind of strange since it couldn't have been done by accident. Why start deviating now?

![](https://cloud.githubusercontent.com/assets/1645989/23595899/8fd3141e-01f3-11e7-8724-1efdf1491a98.png)
