### ISSUE TITLE
King's Rock in GSC

### ISSUE THREAD

**Issue by FredrIQ** [Zarel/Pokemon-Showdown#3343]
Contrary to what Bulbapedia claims, and what Showdown does (inherited by gen3), King's Rock in GSC isn't merely restricted to moves without secondary effects. GSC move effects in general are implemented as "move scripts" with different commands doing different things. One of these is (in pret) labeled kingsrock, which allows King's Rock to proc for said move. This seems to be placed rather arbitrarily, so I will just list the attacking move effects that doesn't do this (Doing the reverse would list quite a lot of things...):

* Attacks that poison (not Twineedle which does proc King's Rock), burn, freeze, paralyze, including Tri Attack, Flame Wheel, Sacred Fire, Thunder
* Dream Eater
* Attacks that increase your or decrease target stats
* Moves that flinch, including Twister but not Snore
* Moves that confuse
* Hyper Beam
* Partially trapping moves
* Earthquake
* Future Sight
* Gust

Moves affected by King's Rock that might seem odd
* Bide
* Counter/Mirror Coat

Other things to consider:
* Multi-hit moves (including Twineedle) only has a single roll for King's Rock
* King's Rock's flinch rate is 30/256
* If the target is asleep (or frozen, but GSC unfreeze is an endturn effect), you can't flinch the target. This doesn't apply to King's Rock which can still flinch as usual

To see for yourselves which moves this concerns, in case something is unclear -- https://github.com/pret/pokecrystal/blob/master/battle/moves/move_effects.asm

**Comment by FredrIQ** [comment]
After discussing with people over at Bulbapedia and consulting other sources, this is in fact not merely limited to GSC -- King's Rock before 5gen in general relied on move flags (not flags per se in at least GSC, but it can effectively be treated as one). See http://upcarchive.playker.info/0/upokecenter/content/pokemon-ruby-version-sapphire-version-and-emerald-version-list-of-moves.html for 3gen (there's also a page for 4gen for similar reasons).

**Comment by asingh04** [comment]
can this issue be taken up as a first/starting issue for me? is anyone working on it?

**Comment by bgsamm** [comment]
How does Snore interact with King's Rock in Gen 2, since it already has a chance to flinch? Is the rate from King's Rock added on to Snore's?

**Comment by Marty-D** [comment]
Fixed in https://github.com/Zarel/Pokemon-Showdown/pull/4916!
