### ISSUE TITLE
Validation Glitch?

### ISSUE THREAD

**Issue by MelonShooter** [Zarel/Pokemon-Showdown#3393]
So, I was fooling around with combining egg moves and rby moves and so i made a new team with Bulbasaur that had light screen and petal dance which is valid.

Meganium can pass light screen (lvl up move) and petal dance(an event move) to Bulbasaur

but when i add an RBY TM (body slam or swords dance etc.) which Bulbasaur can only learn in RBY which I don't think should be valid, the validator suddenly says
- Bulbasaur's past gen egg moves Light Screen, Petal Dance do not have a valid father. (Is this incorrect? If so, post the chainbreeding instructions in Bug Reports)

 So is this a bug? I believe the validator should be saying that body slam is incompatible with one or more moves because it can learn light screen and petal dance, but not body slam with those moves.

Sorry about me closing and reopening. That was an accident.

EDIT: Also, how can bulbasaur learn light screen and skull bash at the same time, there are no valid fathers for both of those moves.

**Comment by Marty-D** [comment]
This issue seems to have been fixed at some point, since:
![bulba](https://user-images.githubusercontent.com/1645989/31476783-566120be-aed6-11e7-9a33-7bad0e54fec7.png)

Also re: getting a Bulbasaur with Light Screen and Skull Bash, pretty sure it's just
```
Get a male Ledyba which learns Light Screen by level up
Breed that with a female Paras
Trade male Paras with Light Screen to RBY and teach it the Skull Bash TM
Breed male Paras with Light Screen and Skull Bash with female Bulbasaur
