### ISSUE TITLE
is Simple useless to Z-moves?

### ISSUE THREAD

**Issue by Kanbe-Kotori** [Zarel/Pokemon-Showdown#3405]
my opponent use Gardevior and trace my Bibarel's simple, it uses Z-hypnosis and its speed raised by 1, which i think should be 2. It is a bug?or just a rule?

**Comment by sparktrain** [comment]
This is the correct mechanic. Abilities like Simple or Contrary do not have an effect on boosts given by Z status moves.

**Comment by Zarel** [comment]
Please do not use the Issues repository for unresearched mechanics questions. We have a Help chatroom and a forum for things like that.

If you do this again, we will need to block you from the repository.
