### ISSUE TITLE
Lum Berry Late Activation

### ISSUE THREAD

**Issue by DanielNestor** [Zarel/Pokemon-Showdown#3414]
http://replay.pokemonshowdown.com/gen7randombattle-554825651

On turn 14 of this match after being burned by Regigigas, the Haxorus used outrage and then the Haxorus's burn was cured. The lum berry should have activated once burned, not at the end of a turn. The lum berry should activate once status is afflicted, not at the end of the turn. 
![lumberrylateactivation](https://cloud.githubusercontent.com/assets/14047510/24524514/d59483fa-1564-11e7-97c5-be95ff26a1af.jpg)

**Comment by Zarel** [comment]
Your Haxorus was burned by Pyroar, not Regigigas. Pyroar has the ability Unnerve, which prevents Haxorus from using berries.

This is why we do not allow mechanics bug reports to be submitted to this repository without full duplication in a YouTube video. Our Bug Reports page, http://psim.us/bugreports, is the right place for that sort of thing.

If you submit another incorrect bug report here, you will be banned from this repository.
