### ISSUE TITLE
GreenKeeper?

### ISSUE THREAD

**Issue by AlainDuhHero** [Zarel/Pokemon-Showdown#3439]
For avoiding PRs and Commits by Regular Users updating packages. GreenKeeper Bot is a good tool as it auto updates the ``node_modules``. This will avoid making a user a  'Contributor' by just change a version of the ``module``. But The Problem Before was GreenKeeper Worked on OAuth and used a GitHub profile but recently It was updated to v2.0 and it solves the problem previously mentioned. GreenKeeper now works as a <a href="https://github.com/integration/greenkeeper">GitHub integration</a>

P.S - Visit <a href="https://greenkeeper.io/"> This Web Site </a> For more info

This Can Avoid PRs like #3396

**Comment by Zarel** [comment]
Can you stop randomly capitalizing words? English has relatively consistent capitalization rules and you're not following them...

**Comment by AlainDuhHero** [comment]
@Zarel Also U need to manually install the integration

**Comment by Zarel** [comment]
I don't think we have enough dependencies for this to be worth it.
