### ISSUE TITLE
Optimizing unit tests

### ISSUE THREAD

**Issue by Morfent** [Zarel/Pokemon-Showdown#3453]
I think we can reduce the amount of time it takes for Mocha to finish running our tests. On my machine, it takes 20-30 seconds, which I feel is longer than it should be. While writing unit tests for a while, I've run into cases where users/rooms aren't properly cleaned up in `after`/`afterEach` hooks, or are created/destroyed more often than really necessary in `beforeEach`/`afterEach` hooks. This can and has broken tests unrelated to those I was writing. I haven't looked at the simulator unit tests yet, but I suspect there are improvements that could be made to those as well.

This isn't a very serious issue, but I don't think tests should be ok to write sloppily when that leads to issues when making changes to them later on. Being able to test more quickly would help speed up debugging code as you write it and getting code ready to run in production faster (if you follow TDD for what you're doing, at least). Fixing problems with tests piecemeal as you modify them would probably be the easiest way to do this gradually before needing to look into Mocha config and how PS is bootstrapped for the tests in `test/main.js` if they're still slow by then.

**Comment by Zarel** [comment]
Not cleaning up users/rooms should not have a significant effect on test running time.

Main thing that takes up test running time is battle simulation, which isn't really easy to optimize...

**Comment by Zarel** [comment]
I've made several tries to make battle simulation faster, but it's really not easy. :/

**Comment by Morfent** [comment]
>Not cleaning up users/rooms should not have a significant effect on test running time.

I wasn't very clear. I was taking into account both test running time and the time spent debugging tests unrelated to what I'm writing because a battle wasn't destroyed. When they do work right they aren't much of a problem

>Main thing that takes up test running time is battle simulation, which isn't really easy to optimize...

Even though I haven't looked over the simulator much, I can see what you mean. The way function parametres are handled there wouldn't make me surprised if inline caching might be partially at fault. Tools has similar issues with performance from my experience as well, and the two are not things that look very pleasant to optimize... Maybe I'll give it a shot once I finish dealing with sockets and the global room

**Comment by Zarel** [comment]
It looks like cutting down on the randbats tests noticeably speeds up the testing process.

**Comment by Slayer95** [comment]
> It looks like cutting down on the randbats tests noticeably speeds up the testing process.

Done in 3b4d8b3ff0a020ca578d6d007cb785bfbe3813b0#diff-f2ea20a51696bb5c0059cb5208f3aac7

> Not cleaning up users/rooms should not have a significant effect on test running time.
Main thing that takes up test running time is battle simulation, which isn't really easy to optimize...

It doesn't seem that there is much more actionable here.
