### ISSUE TITLE
Z-Conversion does not correctly work with Simple

### ISSUE THREAD

**Issue by spixi** [Zarel/Pokemon-Showdown#3481]
Expected result
If a Pokémon with Simple uses Z-Conversion, each stat should be raised by 2 stages

Actual result
In this case Porygon-Z had Simple, but Z-Conversion only rose the stats by 1 stage. This is not correct.

Replay
http://replay.pokemonshowdown.com/gen7vgc2017-566773294

**Comment by Marty-D** [comment]
You're wrong; please do at least 5 seconds of research before opening an issue here. And even then you should be posting in the [Bug Reports thread](http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/) instead. Boosting effects from Z-Power aren't normal stat stage changes, so they're not affected by Contrary or Simple.
