### ISSUE TITLE
need Chinese

### ISSUE THREAD

**Issue by tangbaobao** [Zarel/Pokemon-Showdown#3502]
To help more freshmen in China, I think that provide Chinese is a necessary thing in Pokemon-Showdown.
I can help to translate.
After reviewing the code, I found that the language and the codes are combined very closely. So could you provide some ideas to start this huge project?

**Comment by Zarel** [comment]
Language support is currently tracked in:

https://github.com/Zarel/Pokemon-Showdown-Client/issues/247

**Comment by Zarel** [comment]
It's true that language is a bit tightly coupled right now. :/ I've been meaning to fix that but I've gotten lost in other refactors...
