### ISSUE TITLE
[Request] View Battle Videos from 3DS

### ISSUE THREAD

**Issue by thatsmyface** [Zarel/Pokemon-Showdown#3562]
It would be cool if you could implement a Battle Video viewer from the 3DS games. So someone could type in the battle code from an uploaded video (something like M3QW-WWWW-WWW7-5PYW) and then watch the replay of the battle. It is my understanding that these codes correlate to a text file on the server that says the moves and stats of each Pokemon, rather than just a video file. This functionality would make it so someone could see a battle video that their friends send them without needing to pull out their DS and connecting to the internet. The reason I'm suggesting this for Pokemon Showdown is that it requires a battle simulator, since the battle video only contains the data of what happened in the battles, and Showdown seems to be in the best position to reenact that battle using the data. The main issue that comes to mind would be obtaining the battle file from Nintendo's server using the code; I'm not sure how that can be done. 

I know that this is a large feature to request for a small pay-out but it would certainly be helpful for people sharing strategies and such.

**Comment by Zarel** [comment]
project-pokemon did it for Gen 5 (they made a converter from battle videos to PS replay format).

They didn't use the simulator, though – PS isn't RNG-accurate enough that we'd generate the same battle given the same seed.

If someone knows a way to obtain replay data and can give me a few samples with corresponding video, though, I can work on RNG-accuracy.

**Comment by architdate** [comment]
it is possible to extract a battle video from a given code. The data itself is stored as as hex values of every turn if i remember correctly. The video itself can be extracted via BootNTR once the code is inserted.

**Comment by scheibo** [comment]
Duping this to #4804.
