### ISSUE TITLE
Critical hit escalates to 4 times the normal damage

### ISSUE THREAD

**Issue by arp001** [Zarel/Pokemon-Showdown#3581]
<img width="396" alt="screen shot 2017-06-03 at 12 08 32 pm" src="https://cloud.githubusercontent.com/assets/15954001/26802443/82915492-4a0e-11e7-8fac-070c52d57737.png">

Pretty sure this is not intended. As a user, I was pretty upset by the exponential rise in damage. 

Preconditions: [Not a 100% sure about these but pretty confident]

- The attacker had 4 x Sp. Attack and 4 x Sp. Defense and 4 x Speed
- The receiver had 4 x Sp. Attack and 4 x Sp. Defense

**Comment by Nineage** [comment]
This is not a bug. Critical hits ignore the opponent's defense boosts and factor in the attacker's attack boosts as normal, so the masquerain was using the same move with the same power against a foe with 1/4 the special defense.

**Comment by Slayer95** [comment]
As @Nineage said

**Comment by Zarel** [comment]
As a warning, this repository is not meant for reporting any mechanics bugs that have not first been verified to work differently on cartridge.

If you do this again, you will be blocked from this repository.
