### ISSUE TITLE
Uno: Cannot play two Wild +4 cards in a row

### ISSUE THREAD

**Issue by xfix** [Zarel/Pokemon-Showdown#3713]
If you play Wild +4 card draw, pick color you don't have, and then Wild +4 card draw again, the game will reject it, even if you don't have any other card options. This is because top card color is Wild which means game sees "alternative" ways to play other than than Wild +4 card.

I mostly put this bug as a reminder for myself.

**Comment by jumbowhales** [comment]
my bad, oversight from my commit
