### ISSUE TITLE
Illegal Gligar in Random Battles

### ISSUE THREAD

**Issue by Storm-Eagle20** [Zarel/Pokemon-Showdown#3741]
https://github.com/Zarel/Pokemon-Showdown/blob/a4e1b2692a5a00459b4a32345a198cbe6be3c0b6/data/formats-data.js#L2055

In this line of code, Gligar learns Defog, however in Random Battles his ability can also be Immunity, which is Hidden, while Defog is Gen 4 TM.

https://image.prntscr.com/image/zuMBEBGvSVi9N4nN_xQakw.png

Here is an example picture. Not a necessarily big issue, but I just wanted it in your attention.

**Comment by Slayer95** [comment]
Random Battles' allowing move incompatibilities is intended.

**Comment by Storm-Eagle20** [comment]
I apologize then. Could you kindly add this to the Contributing Guidelines? I'm sure this will help you avoid future issues with this. I've looked to see if this was intended and I never saw anything anywhere.

I hope I'm not wasting your time.

**Comment by Slayer95** [comment]
A similar issue is #2984, but it was probably hard to find (it took me a while), so no blame for you.

I think this is a bit too specific for the ``CONTRIBUTING.md``. However, I believe this was once documented in the OP of the bugs report thread (http://pokemonshowdown.com/bugs) -no there anymore for some reason...

Also, that thread *should* be linked from ``CONTRIBUTING.md`` as the go-to place for battle-related bugs, right, @Zarel?

**Comment by Zarel** [comment]
Yes, probably. `CONTRIBUTING.md` is for developers, but we should probably also have instructions for bug reporters.
