### ISSUE TITLE
Replays do not show type icons for Reflect Type

### ISSUE THREAD

**Issue by SadisticMystic** [Zarel/Pokemon-Showdown#3882]
Here are a couple replays of test battles, in which type-changing mechanics are used:
https://replay.pokemonshowdown.com/gen7doublesou-583055003
http://replay.pokemonshowdown.com/gen7doublesuu-616500730

In battle 1, Shuckle becomes Ice type at turn 1, and the replay shows this correctly. Smeargle becomes Ice type at turn 6 (also shown correctly). Noivern gets Grass added to its types at turn 9 (shown correctly), just ahead of Smeargle taking the whole Flying/Dragon/Grass shebang for its own types, but in this instance the replay only puts the "+Grass" part in its status bar.

In battle 2, the operations are done the other way around: Smeargle acquires just two types on turn 24, which are not shown in the replay at all, and the third type is added on turn 26, which is shown correctly.

This is only a bug with respect to the replay; the types were shown perfectly well while the battle was playing out originally. It's probably a rather low priority, then...but it's something I was at least in position to notice, due to the unusual nature of these test battles.

**Comment by Slayer95** [comment]
Pokémon types are not loaded at all in replays for faster load times, which is what creates this sort of issues.

However, that predates most type change mechanics as well as the tooltips, so <i>maybe</i> we can consider fixing this? Alternatively, Reflect Type can be ignored if ``pokemon.types`` doesn't exist (i.e. in a replay).

**Comment by Slayer95** [comment]
There are two reasons why this happen.

Pokémon types are not loaded at all in replays for faster load times, so the replay viewer doesn't know that Noivern is Dragon nor that Stunfisk is Ground/Electric. However, that predates most type change mechanics as well as the type hints, so maybe we can reconsider this.
As far as the replay viewer is concerned, the Reflect Type target could actually be a Zoroark in disguise, so it wouldn't be certain to show the Smeargle as Dragon/Grass, when it could actually be Dark/Grass. For this, we would need some sort of GUI indicator specific to Reflect Type.

**Comment by SadisticMystic** [comment]
Reflect Type's type icon *does* show up, even in a replay, as long as it's being used on a Pokemon whose type has already been overwritten by some other effect in the battle previously (as happens in battle 1 turn 6). 

I can confirm that in the actual game, if you Reflect Type an opponent's Zoroark while their illusion is still intact, clicking for your Pokemon's summary screen does correctly show that you are Dark type (even as the opponent's summary shows their disguised form and type), and of course using your own Zoroark against a wild Ditto that's transformed into your Reflect Type user shows them with the correct Dark typing as well. Replays should therefore be able to look up exactly what type combination is being granted by each instance of Reflect Type, with no worries of leaking undue information to either side.

**Comment by Zarel** [comment]
@SadisticMystic can you confirm which generations show that in the summary screens?

**Comment by SadisticMystic** [comment]
The summary screen is something that was only introduced in 7, so a Reflect Type under 5 or 6 rules wouldn't give the user any feedback to let you know you're facing an illusion or the types you're actually receiving.

**Comment by Slayer95** [comment]
Even if both players know that a Pokémon is or isn't Zoroark, we might not want to publish that sort of information in replays, since it could be a privacy violation regarding Zoroark usage.

**Comment by Marty-D** [comment]
Just to clarify, you guys are referring to two different things. The summary screen Zarel is talking about is what comes up when clicking "Summary" on this screen:
![](http://i.imgur.com/aWhO1qf.png), and tells you your _original_ stats, types, moves, and Ability. This kind of thing has existed since Gen 1, but it was called the "Stats" screen until Gen 3.

The new thing in Gen 7 is what you get by clicking your or your opponent's minisprite icons while selecting actions.
![](http://i.imgur.com/KBiv3GA.png)
This info box never lies to you about your own Pokemon, even if you wouldn't otherwise have any idea about certain information due to Transform or other such effects in any other gen. Stuff it won't reveal when clicking opposing Pokemon is their Ability or item, even if you definitely know what they are because you Skill Swapped or Tricked them.

**Comment by Zarel** [comment]
I think the protocol should send this information (including to spectators) even if it's not visible to spectators under normal conditions.

**Comment by Zarel** [comment]
I'm pretty sure modern PS versions send this information, now, so this is fixed.
