### ISSUE TITLE
Says I've reconnected when my opponent disconnects or reconnects

### ISSUE THREAD

**Issue by Ads20000** [Zarel/Pokemon-Showdown#3901]
Maybe this is supposed to be against the client repository, not sure. In my battle log, I get messages saying that I've reconnected when I haven't disconnected in the first place - but my opponent has disconnected or reconnected.

http://replay.pokemonshowdown.com/gen7ou-619661887

![screenshot from 2017-08-19 15-52-38](https://user-images.githubusercontent.com/3178485/29487820-76468c1a-84f7-11e7-9108-9d1d4fc19a9c.png)

Firefox 55.0.2 on Ubuntu 17.04 64-bit

**Comment by Zarel** [comment]
This is definitely a server bug.

**Comment by Dialga204** [comment]
I have been getting this reconnect bug a lot during battles.

**Comment by Zarel** [comment]
Fixed in 2cdbea7de59
