### ISSUE TITLE
My server won't start because of this.

### ISSUE THREAD

**Issue by SD-Vegalius** [Zarel/Pokemon-Showdown#3916]
![screenshot_2](https://user-images.githubusercontent.com/30198772/29731170-10c5c958-89a9-11e7-8c5f-0b285e6ba3f9.png)

**Comment by bumbadadabum** [comment]
Update your node.js version. Look in the readme to see the minimum required version.

**Comment by Zarel** [comment]
Why are you running `node app.js`? Who told you to? It doesn't say `node app.js` anywhere in the README or anywhere else.

**Comment by AustinXII** [comment]
He must be used to the old way but still you should read the updated README before trying to develop a server.

**Comment by Zarel** [comment]
Maybe we should rename `app.js` to `server.js`, as is I think the standard these days.

**Comment by Slayer95** [comment]
``node app.js`` is still what ``npm start`` does https://github.com/Zarel/Pokemon-Showdown/blob/master/package.json#L22

**Comment by Zarel** [comment]
@Slayer95 should that be changed to `node pokemon-showdown` or `pokemon-showdown`?

**Comment by Slayer95** [comment]
For Windows support, the first option.
For Debian support, the second option (since the binary is named ``nodejs``).

**Comment by Zarel** [comment]
........................................................................

**Comment by Zarel** [comment]
Can't npm figure it out on Windows? :|

**Comment by Slayer95** [comment]
No, that invokes the file as a JScript executable :[

**Comment by Zarel** [comment]
Windows it is; Debian needs to get their shit together I guess

**Comment by Slayer95** [comment]
Goods news is: Debian is getting fixed!
https://lists.debian.org/debian-devel-announce/2017/07/msg00006.html
