### ISSUE TITLE
Convert for...length loops to for...of loops

### ISSUE THREAD

**Issue by Zarel** [Zarel/Pokemon-Showdown#3918]
For-of arrays are finally performant!

https://github.com/Zarel/Pokemon-Showdown/commit/eda7ab5c93da0fdc329a0fbc34849f4b1f345827

We should replace our old-style arrays. Hunt them down with a non-multiline `for .*\.length` regex:

```
rg "for .*\.length"
```

Or if you don't have ripgrep (you should really just install it)

```
git grep "for .*\.length"
```

**Comment by Zarel** [comment]
(I'm really only adding this so everyone knows to use `for..of` in the future. Converting old loops can happen as slow as we want.)

**Comment by acz13** [comment]
There's currently 470 of these... holy ****

**Comment by acz13** [comment]
Partially converted some files acz13/Pokemon-Showdown@4dfb191054c22109ef6b4d8f7ac63c7126e26e11

**Comment by Zarel** [comment]
There's no perf gain, it's just a readability gain.

**Comment by Zarel** [comment]
Thanks!

**Comment by acz13** [comment]
There's quite a few reverse loops (`for .*\.length - 1.*--`) left that could possibly be changed.

**Comment by Zarel** [comment]
Reverse loops usually do something that makes them hard to refactor out, afaik.
