### ISSUE TITLE
The 'Save' Button on the 'Import/Export' Feature is functioning properly.

### ISSUE THREAD

**Issue by Vegalius** [Zarel/Pokemon-Showdown#3929]
The 'Save' Button on the 'Import/Export' Feature is functioning properly. Neither the Pokemon Showdown Desktop Application nor on the official website does it work.

I found out while trying to import a team I found on Smogon.
Figured I might as well mention this.

EDIT: It's only when you want to import a team; The importing individual sets / Pokemon works fine.
EDIT 2: It seems to work only after you import individual sets for Pokemon. Not entirely sure if you have to do that for the rest of the 5 Pokemon though.

**Comment by Zarel** [comment]
Works fine for me. Maybe a browser issue?

**Comment by Vegalius** [comment]
I realized what the problem. I was trying to import to different Hidden Power Types on the same line.  I delete one and it worked. Apologies for the user error.

**Comment by Zarel** [comment]
Could you give an example? That's something I might want to fix anyway.
