### ISSUE TITLE
Team status icons get confused if lead is same species but different form as Pokemon #1 in team preview

### ISSUE THREAD

**Issue by SadisticMystic** [Zarel/Pokemon-Showdown#3982]
https://replay.pokemonshowdown.com/gen7anythinggoes-615620719

In this battle, I have a Rotom-Normal in slot 1, which is also my most common lead with this team, but here I decided to start with something else. Similarly, the opponent shows Landorus-I in slot 1, when they also have a Landorus-T on the team and decided to lead with the latter.

This causes the sidebar status icons to get confused and duplicate the lead form into slot 1, without having those slots switch places, so there are two Rotom-Frost icons and two Landorus-T icons starting on turn 1, and no Rotom-Normal or Landorus-I at all. Of course, those Pokemon still exist on the teams, and can be sent out later; as it turns out both of them make their first appearance on the same turn. In my case, the icons single out Wash (slot 3) to be spliced out of the team entirely, with everyone else moving up a slot and the normal icon being padded onto the end in what's now slot 6. For the opponent, Volcanion (slot 5) gets pulled out instead.

Later on, when Rotom-W and Volcanion finally do show up in battle for themselves, there is no compensatory adjustment to the icons whatsoever; they're just active in battle without being accounted for by the sidebar.

Some Pokemon like Arceus and Silvally can have ambiguous forms, where the one that appears in team preview isn't necessarily the same form that gets sent out, but Rotom and Landorus have no such ways to fool the preview, so the engine should definitely be capable of tracking which one is which.

**Comment by Slayer95** [comment]
Sounds like possibly a regression due to https://github.com/Zarel/Pokemon-Showdown-Client/pull/996 ?

**Comment by QuiteQuiet** [comment]
Since I've been looking into exactly what Illusion is doing to the client recently that make it so confused, Zarel/Pokemon-Showdown-Client#996 may only have exposed the problems with `newPokemon` discussed in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1010.
