### ISSUE TITLE
Mega Evolve and Z-Move on 1 Mon

### ISSUE THREAD

**Issue by skewbed** [Zarel/Pokemon-Showdown#4028]
Mega Rayquaza can use hold a Z-Crystal and still mega evolve if it knows Dragon Ascent.

It will not let you do both, or even one and then the other.

Here is a replay of me trying to do this to reck someone with Z-Celebrate to boost all of my stats: [http://replay.pokemonshowdown.com/gen7anythinggoes-638630917](http://replay.pokemonshowdown.com/gen7anythinggoes-638630917)

**Comment by Marty-D** [comment]
No, it can't; please do not use GitHub to report issues, especially ones that aren't real.
