### ISSUE TITLE
Power Split doesn't affect the stat overlays during battle

### ISSUE THREAD

**Issue by alaserdolphin** [Zarel/Pokemon-Showdown#4029]
When hovering over a pokemon, changes made by Power Split aren't shown.

**Comment by Marty-D** [comment]
This is intentional; it's an information leak if you use it on an opponent since you would know their actual attacking stats, which the games never show you.

**Comment by Zarel** [comment]
We should probably make a note of it, though.

**Comment by Zarel** [comment]
Maybe show Power Split as a volatile.

**Comment by alaserdolphin** [comment]
In theory, if someone had the time and accuracy, "reverse engineer" it down to a range based on the damage before and after activating it? In other words, damage the opponent for A-B%, activate Power Split, hit them for X-Y%, and run values through the calc until the result is the same?
I'm not saying it's feasible for someone to do, but it's definitely not impossible.
