### ISSUE TITLE
Marshadium Z And Darkinium Z

### ISSUE THREAD

**Issue by leder73** [Zarel/Pokemon-Showdown#4052]
Marshadow can't learn soul stealing seven star with or without Marshadium Z and darkria can't learn black hole eclipse with or without Darkinium Z so can you fix it

**Comment by Marty-D** [comment]
"You can use one Z-Move per battle. To do so, teach a Pokémon a move and give it a Z-Crystal of the same type (e.g. Fire Blast and Firium Z).The Z-Move will either be physical or special, depending on the base move. To check how powerful a Z-Move will be, or what the effects of a Z-Status Move are, type /dt name and it will appear at the bottom. Some Z-Moves, like Sinister Arrow Raid, are exclusive to certain Pokémon and base moves; /dt name will list their conditions."

" Z-Crystal: Marshadium Z |  User: Marshadow |  Required Move: Spectral Thief"

Please never open an issue here again for things you can just ask the [Help room](https://play.pokemonshowdown.com/help).
