### ISSUE TITLE
(Proposal) Hidden Rooms visible on rooms list to % and up; likewise with Secret Rooms with & and up

### ISSUE THREAD

**Issue by DeathlyPlays** [Zarel/Pokemon-Showdown#4097]
I believe if Hidden Rooms are "visible to % and up" any Driver and above should be able to literally see it on the rooms list, likewise with Secret Rooms with Leaders and up.

**Comment by Zarel** [comment]
No

**Comment by Zarel** [comment]
This repository really isn't the right place for suggestions. The Dev room exists and http://psim.us/suggestions exists.

**Comment by DeathlyPlays** [comment]
Ah

**Comment by DeathlyPlays** [comment]
I just saw other proposals in the issues
