### ISSUE TITLE
mime.lookup is not a function

### ISSUE THREAD

**Issue by DiscordCSS** [Zarel/Pokemon-Showdown#4134]
my os is windows 8.1 64 bit
this is the following error

```
CRASH: TypeError: mime.lookup is not a function
    at Server.respond (C:\Users\inky\Music\pokemon-showdown\node_modules\node-st
atic\lib\node-static.js:348:28)
    at C:\Users\inky\Music\pokemon-showdown\node_modules\node-static\lib\node-st
atic.js:64:22
    at FSReqWrap.oncomplete (fs.js:155:5)

Additional information:
```

here is the following logs

```
inky@Shousto4 MINGW64 ~/Music/pokemon-showdown (master)
$ node pokemon-showdown
NEW GLOBAL: global
NEW CHATROOM: lobby
NEW CHATROOM: staff
Worker 1 now listening on 0.0.0.0:8000
Test your server at http://localhost:8000

CRASH: TypeError: mime.lookup is not a function
    at Server.respond (C:\Users\inky\Music\pokemon-showdown\node_modules\node-st
atic\lib\node-static.js:348:28)
    at C:\Users\inky\Music\pokemon-showdown\node_modules\node-static\lib\node-st
atic.js:64:22
    at FSReqWrap.oncomplete (fs.js:155:5)

Additional information:
``` 
it happended when i went on http://localhost:8000

**Comment by Zarel** [comment]
My best guess is that this is a bug in `node-static`'s Windows support?

**Comment by Zarel** [comment]
Looking further, it seems like either you're missing a subdependency, or you have the wrong version of `mime`.

Try deleting `node_modules` and trying again?

**Comment by Zarel** [comment]
(Feel free to reopen if that doesn't work)

**Comment by DiscordCSS** [comment]
@Zarel changing `mime.lookup` to `mime.getType` in the code worked thanks anywayws

**Comment by Zarel** [comment]
That definitely means you have the wrong version of `mime`. Are you using a third party `npm` implementation? The default one should install mime 1, not mime 2...

**Comment by DiscordCSS** [comment]
i just did `npm install` i belive npm is installing the lastest version but after i restarted my pc it stopped showing that error so i think its a web error or something

**Comment by Zarel** [comment]
Let's just chalk it up to a one-time npm glitch.

**Comment by HoeenCoder** [comment]
Are you using c9? I've expirienced this in the past trying to connect (link didnt redirect to psim.us) its easily fixed by adding -80.psim.us to the normal link (if it dosent already have it)

**Comment by Morfent** [comment]
What versions of node, npm, node-static, and mime are installed if this happens for you, out of curiosity?

>Are you using c9? I've expirienced this in the past trying to connect (link didnt redirect to psim.us) its easily fixed by adding -80.psim.us to the normal link (if it dosent already have it)

The only reason that prevents the crash is because using the psim.us URL skips having to get index.html from the server to get redirected. Any requests to the server outside of `/showdown/*` should still crash

**Comment by hawm** [comment]
lookup() renamed to getType() in mime version 2. https://www.npmjs.com/package/mime
