### ISSUE TITLE
use PRNG to roll Pokemon gender

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown#4364]
Is there a reason that `Math.random` is being used on this line?

https://github.com/Zarel/Pokemon-Showdown/blob/99d682ca26fb184f10a788bf7c5406dad8e951af/sim/pokemon.js#L119

**Comment by Zarel** [comment]
No, this should definitely be changed to PRNG.

**Comment by yuzeh** [comment]
Cool! This is actually where the roll should happen, I believe:

https://github.com/Zarel/Pokemon-Showdown/blob/e8d8a6f/data/random-teams.js#L498

**Comment by Zarel** [comment]
We support random gender with customized teams. It's actually the default setting.

**Comment by Zarel** [comment]
![image](https://user-images.githubusercontent.com/551184/35197455-eeedf4d8-fea4-11e7-99d1-b6467deb66dd.png)

See the "Random" setting?

**Comment by yuzeh** [comment]
Okay, sounds like this should happen at the first callsite then.

**Comment by Zarel** [comment]
It should be replaceable with `this.battle.random()`

**Comment by yuzeh** [comment]
While we're here, I think this calls should also be changed to use the PRNG:

https://github.com/Zarel/Pokemon-Showdown/blob/aae46ffd4669d47cbdf47798ab21120f21f6f98a/sim/side.js#L187

https://github.com/Zarel/Pokemon-Showdown/blob/aae46ffd4669d47cbdf47798ab21120f21f6f98a/sim/battle.js#L489

https://github.com/Zarel/Pokemon-Showdown/blob/aae46ffd4669d47cbdf47798ab21120f21f6f98a/sim/battle.js#L542

Does this sound right?

**Comment by Zarel** [comment]
Agreed, there should be no `Math.random()` in `sim/`.

**Comment by yuzeh** [comment]
Fixed in #4365
