### ISSUE TITLE
Move choices with `ultra` are showing up as `mega` in replay logs

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown#4380]
See:

https://github.com/Zarel/Pokemon-Showdown/blob/9c37960ab645b69ff6ca3e7beddc729221bae8ac/sim/side.js#L449

https://github.com/Zarel/Pokemon-Showdown/blob/9c37960ab645b69ff6ca3e7beddc729221bae8ac/sim/side.js#L126

I'm guessing this behavior is intentional for client compatibility. Are there any plans to make the client recognize `ultra`?

**Comment by Zarel** [comment]
Replay logs should honestly not have move choices at all, at least not in the present format. I'll refactor the whole thing sooner or later.

**Comment by Zarel** [comment]
Fixed; PS no longer has move choices in replay logs. Our replacement is the inputlog, which still appears in replay sources.

**Comment by yuzeh** [comment]
This is excellent!

When did the changes go live?

**Comment by Zarel** [comment]
Aug 2, apparently:

https://github.com/Zarel/Pokemon-Showdown/commit/8c6852c72dc49499264629079afc69ca81be9539#diff-8e7de5adf598c3773e176809c74c0217

**Comment by Slayer95** [comment]
fwiw, ``inputLog`` still had this same issue due to #5294 (fixed in 47111ac).
