### ISSUE TITLE
Learnset.js does not have all the legal moves

### ISSUE THREAD

**Issue by Wodki** [Zarel/Pokemon-Showdown#4426]
It appears the leanset.js does not have all the legal movies available (eg: Politoed encore.) On the site they normally appear as legal movies, which its somewhat weird consider they are missing, but its correct.

**Comment by Zarel** [comment]
`learnsets.js` does not include moves only learned by pre-evolutions. For instance, Politoed can only learn Encore from a Poliwag egg move.

All relevant parts of the site will manually search through pre-evolutions for learnable moves.
