### ISSUE TITLE
Magikarp's Revenge not classified as a healing move

### ISSUE THREAD

**Issue by Zrp200** [Zarel/Pokemon-Showdown#4432]
I only bring this up because it is a fictional move only used in Custom Battles, so there isn't (to my knowledge) an official version of the move, especially given that it was changed when gen 7 was added. This would just make it usable with Triage, which it should work with due to having the same properties as other draining moves that do work with it. Can this be changed so that it does work?

**Comment by Zarel** [comment]
@Marty-D?

**Comment by Marty-D** [comment]
Sure? If it's a draining move it should have the `heal` flag.
