### ISSUE TITLE
Teambuilder Glitch?

### ISSUE THREAD

**Issue by MBC1215** [Zarel/Pokemon-Showdown#4463]
I don't have any screenshots atm, but I found that occasionally one of my moves will disappear when I enter a battle, and then I can check my teambuilder and all my moves are there. I can delete all my moves, put them back in and the glitch will sort itself out, but this is definently a quality of life issue.

**Comment by scheibo** [comment]
The Teambuilder is part of https://github.com/Zarel/Pokemon-Showdown-Client, so this bug should be filed there instead. However, without accurate steps to reproduce the bug there's not a whole lot we can do.
