### ISSUE TITLE
failed 

### ISSUE THREAD

**Issue by Kanbe-Kotori** [Zarel/Pokemon-Showdown#4469]

**Comment by Kanbe-Kotori** [comment]
to use other skills after using magic room but holding a choice scarf

**Comment by Kanbe-Kotori** [comment]
http://replay.pokemonshowdown.com/gen7ou-714820566

**Comment by Zarel** [comment]
你是中国人吗？讲中文会不会更容易？

**Comment by Zarel** [comment]
I'm not sure why you closed this, but it's a duplicate of #4470 so we should probably use that for further discussion

**Comment by Kanbe-Kotori** [comment]
。。对不起手机屏幕太小误操作了，大概就是带着专爱道具开了magic room以后，用其他技能，技能会使用失败，实际上magic room下专爱是无效的
