### ISSUE TITLE
Choice items and Magic Room

### ISSUE THREAD

**Issue by 3pi-Q** [Zarel/Pokemon-Showdown#4470]
It seems that  pokemon with choice scarf/band/specs will be failed to use different moves in magic room.Here is tthe replay
http://replay.pokemonshowdown.com/gen7ou-714820566

**Comment by Zarel** [comment]
你是中国人吗？讲中文会不会更容易？

**Comment by Zarel** [comment]
Are you related to @Kanbe-Kotori?

**Comment by Zarel** [comment]
@Marty-D will need to confirm, but I believe choice items lock you in when you make the move, and if you're already locked, the lock doesn't go away in Magic Room.

**Comment by Marty-D** [comment]
What @Zarel said is correct, and as of Gen 7 the lock will also cause the locked move to be the only move you can use successfully, even if your item is being ignored. Using any other move will have it fail, but you don't lose PP for it. Blame Dancer's existence!

**Comment by 3pi-Q** [comment]
No！Sir！！I have tesed on 3ds Ultra Moon.my Scarfed lele successfully use psychic after Magic Room！！！@Marty-D

**Comment by 3pi-Q** [comment]
对，我是中国人。@Zarel

**Comment by 3pi-Q** [comment]
对，我是中国人。@Zarel

**Comment by Marty-D** [comment]
Okay, then they fixed it in the Ultra versions. Thanks for notifying us, it'll be fixed soon™!

**Comment by Marty-D** [comment]
https://github.com/Zarel/Pokemon-Showdown/commit/c678014580fe0ee32a7ab6410c4571addb4ddeb6
