### ISSUE TITLE
Data/abilities -> aerilate, pixilate and refrigerate multiplier display issue

### ISSUE THREAD

**Issue by dubstroke** [Zarel/Pokemon-Showdown#4485]
Hello. First off thank you for making this simulator; it clearly took a lot of time and effort. Anyway I'll get right into it.
When choosing the abilities aerilate, pixilate or refrigerate; description says "if the move is normal type; it will change to (flying, fairy or ice) type (respectively) and it's power is multiplied by 1.2"
Whereas it should be "multiplied by 1.3"
I glanced over the codes and i think the actual multiplier in calculating is correct; and it's only the description that has a mistake.
With thanks.

**Comment by KrisXV** [comment]
The multiplier for those abilities is 1.2x in USUM
