### ISSUE TITLE
Battle identifiers may be reused on server restart

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#4520]
If the server is restarted while there are pending writes of ``lastbattles.txt`` due to [throttle](https://github.com/Zarel/Pokemon-Showdown/blob/3bf1aeb79fbab07a4c6afa42582a17ee3ec8dfa3/rooms.js#L495-L499)

This is a regression introduced in #4145.
The previous mechanism preventively wrote a higher battle count than needed, thus safely performing updates per each N battles. On the other hand, the new one ensures that we won't write the file more than once per 10 seconds.

Do we want a more advanced throttle mechanism to ensure an <em>average</em> throttle of 10 seconds according to the battle creation rate? Otherwise, we could just go back to the old mechanism, but using the new ``FS`` tools, like so (declarations omitted)...

```js
	writeNumRooms() {
		// Batch-write for every 10 battles
		if (this.lastBattleSaved >= this.lastBattle) return;
		this.lastBattleSaved = this.lastBattle + LAST_BATTLE_WRITE_THROTTLE;

		FS(LAST_BATTLE_PATH).writeUpdate(() => `${this.lastBattleSaved}`);
	}
```

**Comment by Zarel** [comment]
A new advanced throttle would be nice, sure, let's do that.

**Comment by Zarel** [comment]
Or we could just increase the number of battles to write between, 10 seems way too low.

Apparently we average 2 battles per second right now. So every 10 battles is every 5 seconds.

I guess that's not _that_ low. We can just change it to batching every 20 battles, to roughly match my timed throttle. But the main advantage of my timed throttle is that it's always exactly correct for intentional restarts (restarts in which you use `/lockdown` so no new battles in the last 10 seconds before restart), and that's a property I'd like to keep.

**Comment by Slayer95** [comment]
> no new battles in the last 10 seconds before restart

That's only if the restart is performed by the automatic mechanism. If the restart is manual, by a ``/lockdown`` followed shortly thereafter by ``/kill``, it would be possible for a quick 1v1 replay to be uploaded, and then it could be overriden after the battle is created again when the server goes back up.

<details>
<summary>The mechanism I have in mind is as follows:</summary>
- Read from throttle options, the expected average time as ``average = 10000ms``
- On first call of ``.writeUpdate()``, write to disk. Then, start a time window according to a given or preset parameter, say ``window = 10000ms``.
- If by the end of the window, there was at least a second call to ``.writeUpdate()``, estimate the battle creation rate as ``rate = #battles / window``. Otherwise, wait until ``.writeUpdate()`` is called again, and estimate the battle creation rate as ``rate = 1 / window'``.
- On the next ``.writeUpdate()`` call onwards, preventively write to disk ``lastBattle + ceil(rate * time)``. Store the date of this write.
- On each successful write to disk afterwards, calculate the time since the previous write (``time_eff``, and correct the rate as ``rate' = ``.writeUpdate()`` call afterwards, , and store in memory only the time between the last two writes. Correct the value of the rate as ``rate' = 0.5 * rate * (1 + time/time_eff)``.
</details>

On the other hand... 

> batching every 20 battles

Although I like the algorithm I thought of, but it's only applicable to files with a content of a linearly increasing number, IMO it's better to just adjust the number on the go and keep it simple.

**Comment by Zarel** [comment]
Fixed, but I suspect the throttle is premature optimization...
