### ISSUE TITLE
Edit/Change News

### ISSUE THREAD

**Issue by PaulCodeDisaster** [Zarel/Pokemon-Showdown#4523]
Where is the place of the code who the CODES for NEWS CONTAINER are...
it onlyne for Private playing with friends...

If you dont post it for all send a email pls...
Paul.leon.reiski@gmail.com

**Comment by Slayer95** [comment]
Pokémon Showdown's newsfeed is handled [client-side](https://github.com/Zarel/Pokemon-Showdown-Client), and is therefore unavailable for edition by third party servers.

However, it's possible to work around it and (ab)use PMs as if they were news boxes, which is what some third party servers do as you might have seen. However, further details are out of scope here.

(Also, modded out e-mail)

**Comment by Zarel** [comment]
You are allowed to comment on closed issues, you know. I would _much_ prefer that to you making a new issue.
