### ISSUE TITLE
Doenst work Offline?

### ISSUE THREAD

**Issue by PaulCodeDisaster** [Zarel/Pokemon-Showdown#4524]
Hi i have only a litte bits at the day Internet....

And Showdown will doenst work in my Local Area Network (LAN), why???

Please help, i need to have it online for LAN-Partys

**Comment by Zarel** [comment]
Offline LAN support is something that is semi-possible in the desktop client, if I did some major restructuring. It's not something that I want an open issue for, though, nor will it get done anytime soon.

**Comment by Zarel** [comment]
Issue trackers are not meant to be tech support channels. Anything that you say "Please help" for, this is going to be the wrong place for it.
