### ISSUE TITLE
A question about the ladders and accessing them through web requests

### ISSUE THREAD

**Issue by Favna** [Zarel/Pokemon-Showdown#4571]
Hi there,
Over the past hours I've been planning a new feature in my [Discord bot](https://github.com/favna/ribbon) that would allow users to get the top5/10 (undecided) of a leaderboard. The first phase for me is to determine supported games and while brainstorming I stumbled on the idea of supporting the Showdown leaderboards.

Introduction out of the way I have 2 questions

1. Does Showdown provide any form of API to get the latest data from a ladder?
2. Is there any sort of command throttling that I should take into account to prevent people potentially overloading the requests? I know Showdown itself has tons of users as it is but I figured I'd ask to be sure.

While technically I could request the entire HTML page of say `https://pokemonshowdown.com/ladder/gen7ou` and use something like [Cheerio](https://cheerio.js.org/) to scrape the data this is extremely hacky and not favorable thus I prefer APIs. Based on [this node package](https://github.com/ilikebits/pokemon-showdown-api) and [this users endpoint](https://pokemonshowdown.com/users/api) it would seem Showdown does have some approachable API but I cannot find anything about the ladders section of the site.

**Comment by Zarel** [comment]
You can add `.json` to most pages containing data people might want to scrape.

For instance:

https://pokemonshowdown.com/ladder/gen7ou.json

**Comment by Favna** [comment]
thanks! That's perfect!
