### ISSUE TITLE
If a Pokémon has maximum affection, its chance of critical hit is doubled

### ISSUE THREAD

**Issue by vincentrolfs** [Zarel/Pokemon-Showdown#4656]
If a Pokémon has maximum affection, its chance of critical hit is doubled, see https://bulbapedia.bulbagarden.net/wiki/Critical_hit#Generation_II_onwards.
Note that this refers to the affection in Pokémon-Amie (in Generation VI) or Pokémon Refresh (in Generation VII).

I just checked the code at "/sim/battle.js" and believe this is not implemented right now. My apologies if I am mistaken.

**Comment by Marty-D** [comment]
Affection has no effect in Wi-Fi Battles, just like badge boosts never affected Link Battles in the old days.
