### ISSUE TITLE
Graphical glitch on hover over Pokémon

### ISSUE THREAD

**Issue by penpexgit** [Zarel/Pokemon-Showdown#4707]
I have a team with two Necrozma with the same moves (not items or stats). I start with one of them, use Prismatic Laser, then Showdown shows me that I have 15/16 left of this move with this given Necrozma when I hover over it, but also shows me that the other one has 15/16 Prismatic Laser left when I hover over that one, which shouldn't happen.

Then I switch to the other Necrozma (after the recharge turn of Prismatic Laser of the first one), to use Photon Geyser, and after its use, when I hover over the current Necrozma in use, it shows as if I didn't use Photon Geyser, which is a bug. And it also stills shows me the current Necrozma with 15/15 Prismatic Laser left when I hover over it, even though it has 16/16.

Note that this is purely a graphical bug of the hover over feature, since moves have their respective counts right where they are displayed to be clicked.

It seems there are two bugs:
-  the wrong Pokémon is deducted moves when it shouldn't
- some moves are not deducted

Here are the pics:
1) [situation after Prismatic Laser](https://i.imgur.com/XuAocnv.png)
2) ['first' Necrozma hover over](https://i.imgur.com/WgYBh1T.png)
3) ['second' Necrozma hover over](https://i.imgur.com/90I2S1t.png)
4) [situation after Photon Geyser](https://i.imgur.com/NZQ9ue7.png)
5) ['second' Necrozma hover over](https://i.imgur.com/4xn2AQQ.png)
6) ['first 'Necrozma hover over](https://i.imgur.com/UOl7euJ.png)

And the replay [http://replay.pokemonshowdown.com/gen7anythinggoes-756937150](http://replay.pokemonshowdown.com/gen7anythinggoes-756937150)

**Comment by Zarel** [comment]
Oh, yeah, PS in its current form has some trouble telling apart Pokémon that are not publicly distinguishable (same species + same gender + same level + same nickname). That's something my client rewrite will hopefully fix.

**Comment by scheibo** [comment]
Moved to client.
