### ISSUE TITLE
When a Pokemon with an -ate ability has their ability disabled by Core Enforcer, Normal-type moves still appear as their respective types when selecting a move.

### ISSUE THREAD

**Issue by Storm-Eagle20** [Zarel/Pokemon-Showdown#4749]
I assume this is a bug as when a Pokemon has Normalize, all of their moves except for a select few (Revelation Dance) appear as Normal-type moves. However, when an Aerilate Pokemon gets it's ability disabled by Core Enforcer, their moves still appear as Flying-type moves when they're really Normal-type moves. I assume this is true for the other types like Fairy and Pixilate as well.

**Comment by ascriptmaster** [comment]
This is likely a client bug. https://github.com/Zarel/Pokemon-Showdown-Client

**Comment by Zarel** [comment]
I'm honestly not too worried about client bugs being here.

**Comment by Zarel** [comment]
But sure, this is now tracked in:

https://github.com/Zarel/Pokemon-Showdown-Client/issues/1132
