### ISSUE TITLE
tournament message type undocumented

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#4771]
There is no mention of the tournament messages on https://github.com/Zarel/Pokemon-Showdown/blob/master/PROTOCOL.md.

**Comment by Zarel** [comment]
@sirDonovan, do you want to do it? I have no clue how tours work.

**Comment by sirDonovan** [comment]
@Zarel yeah, I'll be able to in a few days.

**Comment by Zarel** [comment]
@sirDonovan?

**Comment by sirDonovan** [comment]
Whoops, forgot to finish this up. I'll put it at the top of my to-do list.

**Comment by Zarel** [comment]
Fix pullreq reference: #4917
