### ISSUE TITLE
Sticky Webs doesn't boost Speed if a Contrary Pokemon is phazed in.

### ISSUE THREAD

**Issue by Storm-Eagle20** [Zarel/Pokemon-Showdown#4783]
http://replay.pokemonshowdown.com/gen7balancedhackmonssuspecttest-785156451

Very last turn. Sticky Webs did not boost my Mega Mewtwo Y's Speed like it should have. Whether this is intentional or a bug, I'm uncertain.

**Comment by Zarel** [comment]
@Marty-D?

**Comment by SadisticMystic** [comment]
When you used Entrainment to give the opponent Mold Breaker, that of course means they now have Mold Breaker. If a Mold Breaker Pokemon uses a phasing move to bring the opponent in on hazards, regardless of what ability the hazard-setter had back when it set those hazards, those hazards will ignore the opponent's ability, such as Levitate, Magic Guard, or (for the purses of Sticky Web) Contrary. This isn't a bug.

**Comment by Marty-D** [comment]
This isn't a bug; you gave the Mega Aggron Mold Breaker, and then it used Dragon Tail to drag out your Mega Mewtwo Y. Mold Breaker continues ignoring Abilities while the new Pokemon is being dragged out.

**Comment by Storm-Eagle20** [comment]
Sorry then.
