### ISSUE TITLE
Riskware is detected by Malwarebytes on load

### ISSUE THREAD

**Issue by Pokecreeper** [Zarel/Pokemon-Showdown#4816]
Every time I go on Pokemon Showdown, Malwarebytes detects riskware and blocks it.
Here's the info for the detection:
Domain: my.mixtape.moe
Type: Outbound Connection
IP Address: 206.81.100.131
Port: 56483

**Comment by Zarel** [comment]
Um, my best guess is that a roomintro is loading an image from mixtape.moe? And Malwarebytes thinks this is bad?

Anyway you should be reporting this as a bug to Malwarebytes I guess? It's not anything we care about. There's no actual risk here.
