### ISSUE TITLE
Bug in Shadow Force and incorrect description

### ISSUE THREAD

**Issue by Deathmage777** [Zarel/Pokemon-Showdown#4830]
According to Shadow Force's Bulbapedia it no longer deals double damage without an accuracy check on Minimize users. It says that it does in the description and on testing it does that in game. I doubt this was intentional and only that it wasn't updated for gen 7

**Comment by Zarel** [comment]
This is entirely the wrong place to report bugs in Bulbapedia. You should tell them, not us.

**Comment by Deathmage777** [comment]
To confirm, Penpexgit is correct and I mispoke

**Comment by HoeenCoder** [comment]
@Marty-D ?

**Comment by KrisXV** [comment]
We tend not to trust wikis like Bulbapedia and Serebii for mechanics information due to how easily they can be edited, by the way. It never hurts to bring up concerns though if you’re able to test and believe PS has something incorrectly implemented (even if you can’t test, too).

**Comment by Marty-D** [comment]
VioletPumpkin is a great researcher, would trust her on this. I tested Shadow Force anyway and it's the same deal. Thanks for bringing this to our attention, @Deathmage777!
