### ISSUE TITLE
Is there a programmatic API to simulate a battle (without GUI)?

### ISSUE THREAD

**Issue by jamesqo** [Zarel/Pokemon-Showdown#4841]
Hey, I'm writing a machine learning program that predicts the best next move given the current state of the game, so that it can be used as a competitive battling AI. Does Pokemon Showdown offer a programmatic API to simulate a battle / do damage calculations without the GUI? Thanks.

**Comment by Zarel** [comment]
Yes, see:

https://github.com/Zarel/Pokemon-Showdown/tree/master/sim
