### ISSUE TITLE
Showdown Desktop App not saving Teams

### ISSUE THREAD

**Issue by FusselTeddy** [Zarel/Pokemon-Showdown#4850]
I just got into Showdown again. But Showdown doesn't want to save my Teams...
I can create a Team, battle with it, even change some Moves on **older Teams** (they get saved btw), BUT I can't save any new Teams... Every time I close Showdown they are gone...
I already tried to uninstall/reinstall it but with no success...

**Comment by Zarel** [comment]
Works fine for me. We'd probably need to TeamViewer to figure out the specific thing that doesn't work for you. If you want to set up TeamViewer (it'd let me see/control your computer).

If you do, we'd need to coordinate the ID/password privately. `zarel@pokemonshowdown.com` might be good for this.

**Comment by FusselTeddy** [comment]
I fixed it ^^" My AntiVirus blocked showdown from writing new files...
