### ISSUE TITLE
Viewable Side Server IP Address & Port Number

### ISSUE THREAD

**Issue by Vegalius** [Zarel/Pokemon-Showdown#4945]
I was editing ``custom.css`` on my side server [Premier](https://pokemonshowdown.com/servers/premier) and sometimes it seems when you reload the CSS with the corresponding button, changes are not made to the server. Well, I've begun to use [this link](http://play.pokemonshowdown.com/customcss.php?server=premier) to view my CSS and reload it as well. Well I click the back button and noticed something strange when I was on another of my usernames, one that wasn't an owner of my server. I was able to view my servers IP Address and Port Number. I reloaded hoping it was just a browser issue, but it appears I CAN view those attributes as another server. 

I've found out that if you use the following format, regardless if you are an owner of that side server or not, you can view their Server's IP Address and Port Number: ``http://play.pokemonshowdown.com/customcss.php?server=SERVER_NAME&invalidate``

The only requirement is to replace ``SERVER_NAME`` with the name of the server you would like to view those previously mentioned aspects.

Ex.: [China](https://pokemonshowdown.com/servers/china) has theirs' set up as ``http://47.94.147.145:8000/`` with their IP Address being ``47.94.147.145`` and their Port Number being ``8000``

It only displays partial information if they've set it up as a URL.

Ex.: [Destiny](https://pokemonshowdown.com/servers/destiny) has theirs' set up as ``http://sim.destinyshowdown.net:8080/`` with their Port Number being ``8080``

I don't really know if this is an actual issue or not, but I feel like it could be. Therefore, I decided to open an Issue.

**Comment by panpawn** [comment]
As we discussed in PMs on main, this is a non-issue.

[22:15] Vegalius: yo, panpawn
[22:16] @panpawn: hi
[22:16] Vegalius: are the IP Addresses and Port Numbers suppose to be publicly viewable?
[22:16] Vegalius: of side servers
[22:16] @panpawn: for what
[22:16] @panpawn: i mean, yeah?
[22:17] Vegalius: I mean like for outsiders to view
[22:17] Vegalius: ?
[22:17] @panpawn: yes
[22:17] @panpawn: how else are they supposed to make a connection to your server
[22:17] Vegalius: wait so I opened a useless issue?
[22:17] @panpawn: link me the issue?
[22:17] Vegalius: yeah
[22:17] Vegalius: https://github.com/Zarel/Pokemon-Showdown/issues/4945
[22:17] Vegalius: sorry...
[22:19] Vegalius: As I said within the issue, I wasn't exactly sure if this was a problem

**Comment by Zarel** [comment]
It sounds like you don't know what an IP address is. Never fear, I'm here to help!

It should help to think of your server as a store, and the IP address as the store's address.

If you want people to play games at your server, they need to know where your server is. The IP address tells them where the server is. People can't actually join your server without the IP address.
