### ISSUE TITLE
Challenge message type undocumented

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#5005]
I do not see anything on https://github.com/Zarel/Pokemon-Showdown/blob/master/PROTOCOL.md

**Comment by Zarel** [comment]
`|updatechallenges|JSON`

> `JSON` is a JSON object representing the current state of who the user is challenging and who is challenging the user.

in the "Global messages" section

**Comment by Zarel** [comment]
Were you looking for documentation of the `JSON` object specifically? Or did you want the entire challenge process documented?

**Comment by davidstone** [comment]
I mean the format of what the user sends: `|/challenge username, tiername` is as far as I've gotten from the console. I also see that sending a challenge first sends `|/utm null`, and I have no idea what that is for and whether my client needs to do the same thing.

**Comment by Zarel** [comment]
Here you go:

https://github.com/Zarel/Pokemon-Showdown/blob/master/PROTOCOL.md#battles
