### ISSUE TITLE
Error in Challenge dcoumentation

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#5007]
The documentation states: "SPECIES is left blank if it's identical to NICKNAME". The messages I have seen have it the other way around: NICKNAME is left blank if it is identical to SPECIES. For instance, I received this message:

|/utm |jirachi|leftovers||stealthrock,wish,ironhead,bodyslam|Impish|252,8,216,,,32|||||]|machamp|leftovers|1|dynamicpunch,rest,sleeptalk,stoneedge|Adamant|252,220,36,,,|M||||]|tyranitar|choiceband||pursuit,earthquake,stoneedge,crunch|Adamant|252,244,,,,12|M||||]|blissey|leftovers||thunderwave,softboiled,flamethrower,hiddenpowerground|Calm|,,252,80,176,||,,,30,30,|||]|celebi|leftovers||grassknot,hiddenpowerice,recover,thunderwave|Bold|252,,220,,4,32||,30,30,,,|||]|starmie|leftovers|1|surf,icebeam,thunderbolt,recover|Timid|252,,32,,4,220||,0,,,,|||

**Comment by Zarel** [comment]
I just checked both client and server:

https://github.com/Zarel/Pokemon-Showdown/blob/9e5e67ad92aee619235f57a95b7e54480e37b9bb/sim/dex.js#L1132-L1137

https://github.com/Zarel/Pokemon-Showdown-Client/blob/1f24e93c907db07ce157f8ca07052b4de2b1220f/js/storage.js#L634-L639

Species is left blank if it's identical to name. If you've received a team that was the other way around, it was not generated by PS (maybe that's from the third-party Android client?)

PS _does_ support doing it the other way around, but it's not the intended format.

(btw, you don't need to create new tickets for everything – I _do_ see comments on closed tickets.)

**Comment by Zarel** [comment]
Oh, I see, the client does things differently. That's a mistake on my part.

**Comment by Zarel** [comment]
This is actually a good catch. Unifying the format will save some strain on the validator process.
