### ISSUE TITLE
Both Scyther models for sprites/xyani are shiny

### ISSUE THREAD

**Issue by SirSkaro** [Zarel/Pokemon-Showdown#5011]
http://play.pokemonshowdown.com/sprites/xyani/scyther.gif
and
http://play.pokemonshowdown.com/sprites/xyani-shiny/scyther.gif
are both the shiny variant, except the wings on the "non-shiny" are transparent. But I believe the legs for the non-shiny are more tan, and the legs for the shiny are more pink.

**Comment by Ntonio36** [comment]
Just a minor rectification, according to [pkparaiso](https://www.pkparaiso.com/xy/sprites_pokemon.php?cid=22#shinygroup22), even the wings in the non-shiny variant are blue-ish. You're correct regarding the body color, nevertheless.
Proof of what I'm saying:
![scyther](https://user-images.githubusercontent.com/32229257/50406495-7f2fb080-07ce-11e9-9f22-ef6c33a8f864.gif)
This is "regular" scyther..
![shiny scyther](https://user-images.githubusercontent.com/32229257/50406497-81920a80-07ce-11e9-9da3-543e02d9bdf4.gif)
...while this is the shiny scyther.
Both are available at the following links : https://www.pkparaiso.com/xy/sprites_pokemon.php?cid=22#shinygroup22 (that's for the non-shiny)
https://www.pkparaiso.com/xy/sprites_pokemon_variocolores.php?cid=22#shinygroup22 (for the shiny).

**Comment by Zarel** [comment]
> according to pkparaiso

@Ntonio36 ...the wings are transparent. pkparaiso screenshots them on a blue background, which is why they look blue.

**Comment by scheibo** [comment]
The images linked in https://github.com/Zarel/Pokemon-Showdown/issues/5011#issue-387301358 appear different to me, I'm assuming this has been fixed.
