### ISSUE TITLE
Muted users doesn't show its profile flag when you click them.

### ISSUE THREAD

**Issue by DanielProGames** [Zarel/Pokemon-Showdown#5022]
### How to replicate the issue:
Click on the muted user's name, it will display his profile, but without the "Muted (!)" badge.
https://drive.google.com/open?id=1aTdg_sBaDPLfFObHFELtljpwX6lylB9V
I reacted with "Hooray" because, I'm glad I can contribute to Pokémon Showdown.

**Comment by Zarel** [comment]
The symbol shown on messages is the symbol at the time of the post. The user wasn't muted when they sent the message, so it doesn't appear there.

**Comment by DanielProGames** [comment]
I didn't mind that. Yes, you're right.
