### ISSUE TITLE
Two sleep messages from Rest

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#5023]
When a Pokemon uses Rest, the server sends the following messages:

|move|p2a: Giratina|Rest|p2a: Giratina
|-status|p2a: Giratina|slp
|-heal|p2a: Giratina|100/100 slp|[silent]
|-status|p2a: Giratina|slp|[from] move: Rest

It seems that the first message is redundant.

**Comment by Zarel** [comment]
Yes, honestly, server messages are a huge mess right now, which I learned when writing the new message parser.

**Comment by Zarel** [comment]
Do you have a replay link, by any chance?

**Comment by erlandfauzan** [comment]
omo shiroi

**Comment by davidstone** [comment]
https://bitbucket.org/davidstone/technical-machine/issues/attachments/31/davidstone/technical-machine/1554995847.27/31/battle-gen4randombattle-2202.log.json

Turn 9:

||
|move|p1a: Cresselia|Psychic|p2a: Bibarel
|-damage|p2a: Bibarel|3/100
|move|p2a: Bibarel|Rest|p2a: Bibarel
|-status|p2a: Bibarel|slp
|-heal|p2a: Bibarel|100/100 slp|[silent]
|-status|p2a: Bibarel|slp|[from] move: Rest
|-enditem|p2a: Bibarel|Chesto Berry|[eat]
|-curestatus|p2a: Bibarel|slp|[msg]
||

**Comment by scheibo** [comment]
`slp` in `data/*/statuses.js` and `rest` in `data/*/moves.js` both `this.add('-status', 'slp', ...)`. I've reworked it such that only the status logic is responsible for the message. I'm sure there are other places outside of Rest that send redundant messages though.
