### ISSUE TITLE
Portierung to the 3DS (Homebrew/CFW)

### ISSUE THREAD

**Issue by Volti-p** [Zarel/Pokemon-Showdown#5041]
Hey, I have a Idea, but i don´t know if this is possible, Maybe we can port the Pokémon Showdown Client to the 3DS with a Homebrew /CFW Project? ^^  This would be really great to use this for the 3DS directly, but that would be a lot of work  :)

**Comment by Zarel** [comment]
I usually leave interesting feature ideas open even if none of the current devs want to do it, in case a future dev thinks it's an interesting project.

But in this case, it's just very unlikely that anyone would have the skills and inclination to do it, and anyone who does probably doesn't need the PS issue list for inspiration.
