### ISSUE TITLE
Add LGPE audio

### ISSUE THREAD

**Issue by Kalaxe** [Zarel/Pokemon-Showdown#5066]
New Pokemon Let's go audio that is not in the repository. Cries have been recorded by me and the battle trainer by [Bliitzit](https://www.youtube.com/watch?v=mxmqux7xNWo)

[removed link]

**Comment by Zarel** [comment]
I'm not sure what I'm supposed to do with this.

**Comment by Zarel** [comment]
PS doesn't currently have separate cries for each generation; we just use the latest gen's cries.

**Comment by Kalaxe** [comment]
I dont understand that you dont understand, the file has meltan and melmetal cries that are not in the repository (play.pokemonshowdown.com/audio) and adds the new crie of eevee that has been introduced  in LGPE (as pikachu in 6generacion). In addition to the battle music coach of LGPE.

**Comment by Zarel** [comment]
Oh, I understand now.

Anyway, for a variety of reasons, including that Git isn't designed for resource files, we don't keep audio files in the repository in the first place, but these will be uploaded to the file.

**Comment by Zarel** [comment]
Anyway, for the music, I'll need loop timings.

**Comment by Zarel** [comment]
i.e. the sample index to jump back from and to, to form the loop for the music.

**Comment by Kalaxe** [comment]
3:00 is the end of the song  and you jump back to 0:15

**Comment by Zarel** [comment]
Your music is 44 KHz.

I need it in 1/44000s of a minute.

**Comment by Kalaxe** [comment]
I dont understand you. 44.1Khz = 1 / 44,100 hz
If my music is at 44.1 Khz (checked) that means  every second there are 44100 hz. I dont know what problem you have

**Comment by Zarel** [comment]
Yes. 0:15 isn't accurate enough. I want to know: 15 seconds and how many of the 44100 Hz do you need to jump to?

**Comment by Kalaxe** [comment]
Now I understand, I have been checking and its: 0.15.175 secs or 669.249 hz and 3.01.175 secs or 7.989.818 hz
