### ISSUE TITLE
/invite reveals alts

### ISSUE THREAD

**Issue by TapoCollino** [Zarel/Pokemon-Showdown#5118]
when you /invite someone and he is on another name, it invites the alt. idk if it's intended

**Comment by Zarel** [comment]
So does every other command. :|

**Comment by Zarel** [comment]
Yes, it's intended; it even warns you when you change name that everyone will be able to see you changed name, and you should log out and back in if you don't want that.

**Comment by TapoCollino** [comment]
my bad
