### ISSUE TITLE
Investigate alternatives to `tsc` for compiling Typescript files

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5199]
> Fast feedback loops are important for quick development. Especially since there's no real tradeoff I'm no fan of using tsc for compilation; it's not particularly featureful as a compiler, as you seem to be discovering.

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/issues/3278#issuecomment-466585834_

Opening up this issue to track switching from `tsc` to a faster compiler, as the compile time of `tsc` is deemed to be a blocker for migrating to native Typescript (#3278). @Zarel suggests https://github.com/swc-project/swc as one option, but we should investigate to see if there are any other alternatives as well.

**Comment by Zarel** [comment]
To be fair, "switch" is not the right term; we don't use a compiler at all right now.

**Comment by Zarel** [comment]
The main alternative I've heard is:

https://github.com/alangpierce/sucrase

**Comment by Zarel** [comment]
It looks like sucrase preserves lines by default, which saves us a lot of work in practice. I'm pretty impressed so far.

**Comment by Zarel** [comment]
sucrase apparently defines a separate init function for each class field, though, which can't be good for performance:

![image](https://user-images.githubusercontent.com/551184/53278414-a0c5ef00-36ce-11e9-8985-73397d72017d.png)

**Comment by scheibo** [comment]
To make sure I understand: sucrase/swc/??? would be used for compiling the `.ts` files, but we would still be using `tsc` in the `npm run test` step to actually check the types?

sucrase benchmarks for compile speed certain make it look good, but yeah, the generated code doesn't look ideal. I might try to see how easy they are to set up and then run them through my random simulation harness to get an idea of how it would effect performance numbers.

**Comment by scheibo** [comment]
> sucrase apparently defines a separate init function for each class field.

Looks like that's because you used an initializer - if you set the member in the constructor instead you avoid that. Still, I agree, somewhat worrisome.

> You should think carefully before using Sucrase in production. Sucrase is mostly beneficial in development, and in many cases, Babel or tsc will be more suitable for production builds.

> Sucrase is an experiment

> There may also be breaking changes in Sucrase

Taken from the sucrase documentation. Doesn't inspire a ton of confidence unless we wanted to use it simply in development as it was intended and actually use `tsc` to emit in prod (which could result n odd bugs from divergence). Or, if we're willing to embrace a separate compilers for dev (optimized for compile speed) vs. prod (optimized for runtime speed), we could try using something like [tsickle](https://github.com/angular/tsickle) in a prod build setup. *Note: actually setting up tsickle is out of scope for this bug, just wanted to point out that if we have seperate dev and prod build processes then there are potential benefits (I have a lot of experience with the Closure compiler, but none with tsickle so I'd need to play around more with it to understand its pain points, `bazel` already seems like it would be one of them).*

So - my question is: **how do you feel about a setup that has different builds for dev vs. prod?** Its a fairly common practice (for example, using different optimization flags in prod with C++), but is more of a departure from what we're currently doing. If you're onboard with it, then sucrase looks like a good choice for the development compiler  because the key factors we would care about are correctness and compile speed, and sucrase's benchmarks seem to place it on top. If we want one build solution across the board I'd lean towards swc.

**Comment by Zarel** [comment]
Different builds for dev and prod is unfortunately doesn't make sense for PS, which doesn't really distinguish the two – we essentially run prod in dev mode at all times – every debugging tool is available to us at all times. Even if it did, I don't want to maintain two build pipelines, either.

But even leaving aside considerations specific to PS, I don't think the trade-off makes sense in general: it's not like a crash becomes less of a problem when it happens in prod than when it happens in dev. I want as much information as possible in either case.

**Comment by scheibo** [comment]
> Different builds for dev and prod is unfortunately doesn't make sense for PS, which doesn't really distinguish the two – we essentially run prod in dev mode at all times – every debugging tool is available to us at all times. 

Having a different build pipeline for dev vs. prod does not preclude you stripping away debugging tools.

> Even if it did, I don't want to maintain two build pipelines, either.

This is fair, that's why I asked. In that case I think swc is probably the better choice at the moment.

> But even leaving aside considerations specific to PS, I don't think the trade-off makes sense in general: it's not like a crash becomes less of a problem when it happens in prod than when it happens in dev. I want as much information as possible in either case.

I think youre misinterpreting what a prod build is/can be. It doesn't mean you turn off stack traces or warnings or whatever, in fact you could have the compiler do extra correctness passes. It *can* mean you strip certain debug or dev only tools, but doesn't need to. For C++ it might mean just building at `-O3` with all optimizations instead of the usual fast build. It's whatever you define it to be. My proposal would be to use `sucrase` to compile in prod and `tsc` (or if it becomes viable,`tsc` + `tsickle` in the future). No debug information would be stripped, and source maps would ensure you still get line numbers in the stack traces which make sense. The maitenance burden is having an extra config around, and adding a `--prod` or `--dev` flag to `./pokemon-showdown`, maybe some scripts to `package.json`. But yeah, thats more than just using swc solely for both environments, so I can understand if you'd be opposed.

**Comment by Zarel** [comment]
Yeah, swc sounds like the better choice.

Part of it's the mental overhead of deciding when you should use `--prod` or not. I already have enough indecision with `./build` vs `./build full` on client. If swc is performant and doesn't have many negative trade-offs, why not?

**Comment by scheibo** [comment]
Because I want to have my cake and eat it to. If sucrase gives better compile times for dev and tsc/tsickle could produce more optimized code in prod, it seems like a win-win. 

Still, let's go with swc for now.

**Comment by scheibo** [comment]
Alright, I finally got native typescript to work, so now I'm trying these compilers!

Trying to use `swc` and to begin with its not very ergonomic. https://swc-project.github.io/docs/usage-cli is all you get, no globs etc. It also seems to have trouble with `sim/battle-stream-example.ts` and `sim/battle-stream.ts`, it spits out the other files fine.

```
$ npx swc sim -d sim
error: Expected Comma, got Some(Arrow)
  --> sim/battle-stream-example.ts:97:11
   |
97 | (async () => {
   |           ^^

[Error: failed to parse module]
```

Next up: sucrase:

`$ npx sucrase ./srcDir -d ./outDir --transforms typescript,imports`

Works pretty much instantly and does exactly what I want. The generated code doesn't look bad at all, and I think it keeps line numbers. Color me impressed. I've changed my mind. For now, I think I'll recommend sucrase unless I can prove it has significant runtime performance disadvantages. 

I'm going to close this out, because I was using this bug for investigation. Feel free to reopen, but for now I think we've got our compiler.
