### ISSUE TITLE
Zoroark's illusion mis-reveals moves of team mates

### ISSUE THREAD

**Issue by Veluga** [Zarel/Pokemon-Showdown#5219]
As can be seen in [this](http://replay.pokemonshowdown.com/gen7randombattle-868798103) battle from the first turn onwards, Zoroark uses Nasty Plot while disguised as Celebi. When its illusion breaks (turn 3), the simulator believes that Celebi also carries the move Nasty Plot. This does not reflect its true moveset.

**Comment by Zarel** [comment]
The amount of code required to determine which moves are real and which are fake is just way too complicated. Keep track of it in your own head, unless you want to write the code to track it yourself.

**Comment by Zarel** [comment]
The point of Illusion is to lie to you about what Pokémon it is. As far as I'm concerned, if it displays incorrect information, that's just Illusion doing its job.
