### ISSUE TITLE
Add more `-hint`s to the simulator

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5242]
> PS generally needs more hints.

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5226_

This bug will track improving our `-hint` coverage. As a rule, I think there should be hints for unintuitive/glitchy mechanics that occur *infrequently* or are a common source of misfiled bugs. *Infrequently* is key - mechanics that are showing up every game in a generation are probably not `-hint`-worthy. Another important requirement on top of not being spammy is that a `-hint` must not leak information.

I'm going to go by generation and see where `-hint`s, what already has `-hint`s, and behavior which is glitchy but which we likely do not want `-hint`s for. I don't know if all of these glitches are even implemented correctly in PS currently, but in the process of adding hints for them I'm surely we'll find out ;)

# Gen I

**Unintuitive/bugged behavior that should probably have `-hint`s:**
- [x] Toxic counter glitch (Leech Seed / Rest)
- [x] 1/256 miss glitch
- [x] Struggle bypassing glitch (ie. Wrap PP underflow)
- [x] Substitute + confusion / (Hi) Jump Kick glitch
- [x] Substitute + Explosion / Self-destruct glitch
- [x] Hyper Beam + Sleep move glitch
- [ ] Haze thawing Pokemon frozen during Hyper Beam recharge
- [x] HP recovery move failure (255 / 511) glitch

**Other incongruencies we might possibly consider adding `-hint`s for:**
- Substitute not blocking status
- Counter mechanics
- Bide mechanics

**Mechanics which seem too fundamental/common to explain with `-hint`:**
- Hyper Beam skipping recharge glitch
- Crit Rate
- Borked type chart (Bug, Poison, Ghost)
- Status + modify stat reapplication glitch

**Sources:** [Bulbapedia: Glitches I](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_I), [Smogon: Important RBY Differences](https://www.smogon.com/rb/articles/differences)

# Gen II

**Unintuitive/bugged behavior that should probably have `-hint`s:**
- [x] Draining moves missing against Substitute
- [x] Belly drum when below half HP
- [x] Pursuit faint + switch continuing
- [x] Toxic counter glitches (Baton Pass / Heal Bell)
- [x] 1024 rollover (Thick Club / Light Ball, Reflect / Light Screen, Metal powder increasing damage)
- [x] 1/256 miss for 100% secondary effects
- [x] Present mechanics

**Other incongruencies we might possibly consider adding `-hint`s for:**
- Lock On / Mind Reader + Fly / Dig
- Confusion damage + items/Explosion
- Defense being lowered as a secondary effect after Substitute is broken
- Beat Up mechanics (King's Rock / Substitute / 1 Pokemon left)

**Sources:** [Bulbapedia: Glitches II](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_II), [pokecrystal: Bugs and Glitches](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md)

# Gen III

**Unintuitive/bugged behavior that should probably have `-hint`s:**
- [x] Pursuit faint + switch continuing
- ~Nightmare + Shed Skin behavior~ (Ruby / Sapphire only?)

**Sources:** [Bulbapedia: Glitches III](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_III)

# Gen IV

**Unintuitive/bugged behavior that should probably have `-hint`s:**
- [x] Pursuit faint + switch continuing
- [x] U-turn + Substitute + Intimidate
- [x] Fire Fang hits through Wonder Guard

**Sources:** [Bulbapedia: Glitches IV](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_IV)

# Gen V / VI / VII

**Unintuitive/bugged behavior that should probably have `-hint`s:**
- [x] Locked move (non struggle) + no PP

**Other incongruencies we might possibly consider adding `-hint`s for:**
- Type-changing Curse glitch (Doubles / Triples = Gen VI, Protean  = Gen VI/VII)
- Choice item lock glitch
- Confusion damage + pinch item activation interplay

**Sources:** [Bulbapedia: Glitches V](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_V) [VI](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_VI)  [VII](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_VII)

# Common 'Not Bugs'

- [x] Species specific moves (Dark Void + Darkrai, Hyperspace Fury + Hoopa Unbound)
- [x] Fake Out / First Impression / Mat Block + first turn out
- [x] Dark Types + Prankster

Possibly more that could be added without leaking information based on the thread.

**Sources:** [Smogon - Pokemon Showdown Bug Reports](https://www.smogon.com/forums/threads/bug-reports-v3-0-read-op-before-posting.3634749/)

---

I don't think adding these hints are high priority, so I'm going to let this bug sit for now and hopefully some discussion comes out of it (should we have hints for these? are all these glitches accurate/valid for PS's implementation of each generation? maybe there are additional hints we could be adding?).

**Comment by scheibo** [comment]
From simply poking around the code, its not clear to me where some of these are implemented, if at all (in which case it maybe should be added to #2367)? Gen II Beat Up mechanics are already a known issue, but not sure about the following:

- [Gen I: Haze thawing Pokemon frozen during Hyper Beam recharge resulting in the thawed Pokemon never being able to move again](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_I#Haze_opponent_crippling)
- [Gen II: Lock On / Mind Reader + Fly / Dig interaction with moves like Transform, Spider Web, etc](https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_II#Lock-On.2FMind_Reader_oversight)
- [Gen II: Confusion damage is affected by type-boosting items and Explosion/Self-Destruct doubling](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md#confusion-damage-is-affected-by-type-boosting-items-and-explosionself-destruct-doubling)
  - *I would expect this maybe [here](https://github.com/Zarel/Pokemon-Showdown/blob/master/data/mods/gen2/scripts.js#L522-L535)?* 
- [Moves that lower Defense can do so after breaking a Substitute](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md#moves-that-lower-defense-can-do-so-after-breaking-a-substitute)
  - *I would expect this maybe [here](https://github.com/Zarel/Pokemon-Showdown/blob/master/data/mods/gen2/scripts.js#L404-L429)?*

@Marty-D @DaWoblefet

**Comment by Marty-D** [comment]
Yeah, none of those are implemented yet except the type-boosting item part of Gen 2 confusion damage, which is where you linked it to. I'll try to clean up Known Mechanics Bugs this weekend.

**Comment by scheibo** [comment]
Cools, copied that over there so I can close this out. I'll probably look into implementing them, but I don't want to commit that that right now :)
