### ISSUE TITLE
Add a BasicEffect.isAvailable(format) method

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5243]
Follow up after the 8289374 bug fix.

```
>> Dex.mod('gen1').getTemplate('hydreigon').isNonstandard
<< false
>> Dex.mod('gen1').getTemplate('hydreigon').tier
<< "OU"
```
Is unintuitive. @HoeenCoder suggests it could be useful for OM's, but @TheImmortal claims it isn't. I think its worth fixing.

Somewhat related: shouldn't CAP Pokemon have a generation associated with them? 
I think for CAP (depending on how you treat the prevos) it would be:
```
- Gen IV: [-1, -2, -3, -4, -5, -6, -7,  -8, -9, -10, -11] + [-101, -102, -103, -104, -116, -117, -118, -119]
- Gen V: [-12, -13, -14, -15, -16, -17] + [-106, -107, -108, -109, -110]
- Gen VI: [-17, -18, -19, -20, -21, -22] + [-111, -112, -113, -114, -115]
- Gen VI: [-23, -24, -25, -26, -27] + [-120]
```

Neither of these changes would have prevented the bug 8289374 fixed, but the way `Dex` works was revealed to be less obvious/intuitive due to the bug.

**Comment by Zarel** [comment]
I'd say to set `isNonstandard` to `true` (it was probably originally set to `true` but lost at some point), but otherwise keep it around.

**Comment by Zarel** [comment]
`tier` as well can be set to `Illegal`.

**Comment by Slayer95** [comment]
IIRC, Crystal had a server with a Gen 1 OM with Gen 2 Pokémon, so evidence shows it's useful.

I'd suggest changing ``isNonstandard`` to a string: ``'CAP' | 'Glitch' | 'Hack' | 'Future'``. That would also simplify work on rulesets. See e.g. this unintuitive line https://github.com/Zarel/Pokemon-Showdown/blob/cfb1cf1731eb5273ecc3796ff2a5b7bd92896a4a/data/rulesets.js#L162

**Comment by Slayer95** [comment]
Rather than forcing every generation to get its own deep clone of each data entry, it would be better to have a ``BasicEffect#isAvailable()`` method that reads the ``isNonstandard`` flag as well as the ``gen`` in order to find out the relevant data.

Sort of like how old gens use ``getCategory(move)`` rather than checking ``move.category``

**Comment by Zarel** [comment]
I disagree with `.isAvailable`. We already make a deep clone for every gen.
