### ISSUE TITLE
Gen 2 - Antic Power did extremely small damage

### ISSUE THREAD

**Issue by BarbzYHOOL** [Zarel/Pokemon-Showdown#5268]
At one point, (in the first half of the game), Dewgong gets hit by Antic Power from Marowak and it does only 3% dmg while it's super effective

http://replay.pokemonshowdown.com/gen2randombattle-872522454

**Comment by Zarel** [comment]
lol, we're just in the middle of adding a hint for this behavior, too.

Anyway, PS simulates Pokémon Crystal for Gen 2 games, and this is how it works in Crystal. Blame Game Freak.

(You're not supposed to use Swords Dance more than once on Marowak, or else its Attack gets too high and the damage calculations fail.)

**Comment by Zarel** [comment]
https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_II#Stat_rollover_glitch

Here's the Bulbapedia page on it.

**Comment by Zarel** [comment]
In the future, remember that the issue tracker is not meant to be where you report mechanics bugs. Mechanics bugs should be reported to https://psim.us/bugs

We have people who are intimately familiar with games mechanics who can tell us if this behavior is correct, before putting it on the issue tracker here.

**Comment by BarbzYHOOL** [comment]
Ok thank you. I'm not surprised that you decide to reimplement bugs, that's the same stuff in wow emulation. Not that I agree with that though

**Comment by Zarel** [comment]
The problem with _not_ implementing bugs is that you need to decide what does and doesn't count as a bug, and people will disagree with that.

"We simulate the games exactly" is just the fairest and least-argument way to draw the line.

There are plenty of projects that _don't_ simulate the game exactly, such as NEXT. You're also free to create your own.

**Comment by BarbzYHOOL** [comment]
If there was a login server, I would be more interested. Looks like we can't exactly create our own game before that.

**Comment by Zarel** [comment]
What do you mean?

**Comment by Zarel** [comment]
Everything relevant is open-source.

**Comment by BarbzYHOOL** [comment]
In the client readme (I quickly read it), it kind of talks about the login server that needs to be coded from scratch, no?

**Comment by HoeenCoder** [comment]
You don't need to setup your own client or login server to create your own formats. For something like this, you would want to setup a server and create a mod. A mod allows you to modify the default functions of a battle (default being current gen). All past generations are mods, and you can even have a mod inherit another mod (use that mod as the base that you build yours on, this is done for past gens as well, 4 inherits 5, 3 inherits 4, ect).

**Comment by Zarel** [comment]
The client readme also doesn't say the login server needs to be coded from scratch. I just Ctrl+F'ed and the word "scratch" doesn't appear at all.

What it says is:

> It does NOT include instructions to run a full Pokémon Showdown login server

> If you make a mistake hosting a login server, your users' passwords can get stolen, so we do not want anyone to host a login server unless they can figure out how to do it without help.

In other words, it includes all the code for the login server, it just doesn't include instructions because I don't want people doing it if they can't figure it out without help.

And also what Hoeen said – you don't need your own client to modify game mechanics; the server is enough.

**Comment by BarbzYHOOL** [comment]
Ah ok! thank you guys


Well about client etc, I had gone into crazy thinking like "what if you create a different version of pokemon that is fun to play, and then you change all the assets too, it's now a real game with no copyright infringement".
