### ISSUE TITLE
Side#getChoice() does not recover `ultra` flag

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#5294]
Since ChosenAction.mega is boolean and there is no .ultra

Related: #4380

**Comment by Zarel** [comment]
This is, to an extent, intentional. We can manually detect the held item and use that to determine whether or not the flag is `mega` or `ultra`, if it's that important.

**Comment by Slayer95** [comment]
Sounds like a good enough solution
