### ISSUE TITLE
Recoil damage isn't handled properly

### ISSUE THREAD

**Issue by Jackinev** [Zarel/Pokemon-Showdown#5356]
A few bugs regarding recoil damage have popped up ever since the 4 player refactor.
The server in the following replays is running an unedited version of this repository.

- https://replay.pokemonshowdown.com/sports-gen7ou-6269
Recoil damage seems to be consistently doubled. 
Crobat deals 370HP of damage to Chansey and takes 244HP of recoil (aka x0.66 recoil).
Sudowoodo and Scyther have the exact same HP stat.

- https://replay.pokemonshowdown.com/sports-gen7ou-6265
Recoil damage from abilities and items triggers on multiple hits even after the Pokemon has fainted.

**Comment by Slayer95** [comment]
Fixed by 6adc779a19553
