### ISSUE TITLE
Multi-hit moves keep hitting fainted opponent

### ISSUE THREAD

**Issue by Jackinev** [Zarel/Pokemon-Showdown#5367]
Referencing #5356, I'm still getting the second bug. My fault for grouping two different issues together.

https://replay.pokemonshowdown.com/sports-gen7ou-6265

It seems like multi-hit moves aren't checking if the opponent has fainted on every hit, resulting in multiple triggers from abilities and items such as Aftermath and Rocky Helmet.

**Comment by scheibo** [comment]
Hi Jackinev - I think #5360 should handle this?

**Comment by Zarel** [comment]
On the off chance #5360 doesn't fix this, feel free to comment and I'll reopen.
