### ISSUE TITLE
Remove non-enumerable flatMap hack

### ISSUE THREAD

**Issue by xfix** [Zarel/Pokemon-Showdown#5369]
See https://github.com/Zarel/Pokemon-Showdown/commit/d71a5c90a4d65a568d1d0c2725d3fc90a87656ce

**Comment by scheibo** [comment]
What's the gameplan for this? Can this hack be removed already? We have our linter now checking for `for-in` on arrays, and you can probably run `node test/simulate exhaustive -5` for a while to provide some confidence after removing the hack to ensure it wont break things.
