### ISSUE TITLE
Static sprites never display gender changes.

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown#537]
Should be important for Jellicent/Pyroar where changes are obvious. Seem to work fine for animations.

**Comment by Layell** [comment]
Is there some marker for gender alts I don't know about?

https://i.imgur.com/DJkM3c4.png

**Comment by Layell** [comment]
This should be good now

https://github.com/Zarel/Pokemon-Showdown-Client/compare/a7595aaa8d94...2454e2d44bd9

**Comment by Zarel** [comment]
Unfezant is still a problem.
