### ISSUE TITLE
Imprison should reveal all the affected moves when choosing a sealed move

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#5401]

**Comment by Zarel** [comment]
How does it work on cart?

**Comment by Slayer95** [comment]
> If a Pokemon tries to pick one of the moves sealed by Imprison, the player will be shown all the moves that are sealed at once. E.g. X can't use the sealed {Move 1} (press A) X can't use the sealed {Move 2} (press A) X can't use the sealed {Move 3}

**Comment by Marty-D** [comment]
That's the worst possible way to describe what I assume is what that person actually tried in-game. There's no alternative explanation other than them intentionally spreading misinformation.

A Bronzong with Safeguard/Tackle/Confusion/Hypnosis against a wild Bronzong with Imprison/Tackle/Confusion/Hypnosis. The wild Bronzong uses Imprison; next time I click Fight and then click Tackle: Bronzong can't use the sealed Tackle! I click Confusion: Bronzong can't use the sealed Tackle! I click Hypnosis: Bronzong can't use the sealed Hypnosis! I click Safeguard and the turn plays out.

**Comment by Slayer95** [comment]
Sorry for the noise, and thanks for the clarification Marty!

Though maybe that was the case back during BW when it was posted?

**Comment by Marty-D** [comment]
> Though maybe that was the case back during BW when it was posted?

Nah, I saw it was posted in 2011 and my summary above was a test from BW; hasn't changed since.
