### ISSUE TITLE
randbat replays between Jan 2018 and Aug 2018 extremely hard to reconstruct

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown#5408]
I'm not sure where the best place to raise this issue is, so here goes.

I've been trying to reconstruct replays of old gen7randombattles so that I can find out what the player sees during the battle (rather than "spectator" view, which is the replay). The way I've been doing this is to find
* a version of the server and
* an RNG sequence (I monkeypatch `Math.random` for older replays where we hadn't completely moved off of it)

that would generate the exact sequence of logs the spectator sees.

In Jan 2018, there was a change that removed `|choice|` from the logs, so that makes it extra hard to perform the search I do above, because it got rid of action boundaries (places in the log where one or both players have to make a decision). It also got rid of the actual choices the player made, though that probably isn't hard to intuit from the replay log itself. This wasn't remedied until Aug 2018, when `inputLog` started showing up in `replay.json` files.

My question is: is there an easier way to reconstruct replays in this time period? Perhaps the inputLogs for the battles in question are still lying around somewhere. If not, is there anything else you can do to help me with this?

Thanks in advance!

**Comment by yuzeh** [comment]
Example replays:

* 2018-08-01 -- has inputLog: https://replay.pokemonshowdown.com/gen7randombattle-784620338.json
* 2018-01-27 -- has `|choice|`: https://replay.pokemonshowdown.com/gen7randombattle-695187152.json
* Somewhere in between those two dates -- https://replay.pokemonshowdown.com/gen7randombattle-754606294.json

**Comment by Zarel** [comment]
I mean, this was fixed in Aug 2018; idk what you want from me here, but it's probably impossible. :/

**Comment by Zarel** [comment]
> My question is: is there an easier way to reconstruct replays in this time period? Perhaps the inputLogs for the battles in question are still lying around somewhere. If not, is there anything else you can do to help me with this?

No. I'm not aware of any way available to reconstruct these replays.

**Comment by yuzeh** [comment]
I mostly imagined that the inputlogs might still be available (but not
public), but if not that’s fine. Thanks again!
