### ISSUE TITLE
|request|'s REQUEST object should include a rqid

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5420]
SIM-PROTOCOL.md documents a `rqid` field, but the `rqid` is actually implemented in `server/roombattle.js` instead of in the `sim`, so its not really part of the protocol. The logic should be moved into `sim` so that clients/middleware doesn't need to track it and so that it could be used in the simulator logic (eg. https://github.com/Zarel/Pokemon-Showdown/pull/5418#issuecomment-480553928)

**Comment by Zarel** [comment]
It was previously in `sim`, which is why it was documented in `SIM-PROTOCOL`. It was moved to `roombattle` because `sim` has no use for it and I wanted it to be cleaner. How useful is it for simulator logic?

**Comment by Zarel** [comment]
What would be the benefit of including an `rqid`? As of #5418 it looks like choices are still stateless, which is how I'd prefer them to be, too.

**Comment by scheibo** [comment]
@Slayer95 suggested it, maybe he can chime in. Otherwise I'll remove it from the SIM-PROTOCOL doc and close this out

**Comment by Slayer95** [comment]
I simply said to use the ``rqid`` feature, not to put it in the sim request object :|

FWIW, @Zarel 's suggestion there to send ``|error|`` and ``|request|`` should automatically update the ``rqid`` as I said.

**Comment by scheibo** [comment]
I think the argument for `rqid` in the `REQUEST` object is to obviate the need for clients to count requests in order to be able to undo. But since TCP is lossless and in order I guess we don't need to worry about the client not being able to have the same count as the simulator.

**Comment by Zarel** [comment]
Clients do get `rqid`, though. It's not so much about packet loss/ordering as about being able to display a "too late to undo" rather than a "can't undo" message, if undo is received after your opponent makes a move.

I'm just saying the sim itself doesn't need `rqid`. It's purely for whoever makes a client-server system around the sim, hence why it's implemented in `room-battle`.

**Comment by scheibo** [comment]
> Clients do get `rqid`, though.

`RandomPlayerAI` is a client and does not get a `rqid`.

**Comment by Zarel** [comment]
_Remote_ clients do get `rqid`. `RandomPlayerAI` is synchronous and doesn't need to worry about race conditions. It also doesn't use `undo` at all.
