### ISSUE TITLE
Rework User settings + |updateuser| protocol

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5424]
> I also wonder if we should start bundling user settings together, instead of having them on the top level of `User`. We have a bunch more (although most of them probably shouldn't be sent here).

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5422_

> I'm not entirely sure I want settings in `|updateuser|`
> there's an argument to be made that we don't want to resend all user information whenever a setting is updated
> it's fine right now but we might regret this one day when we have like fifty settings
> although I guess if that happens we can revisit then
> and probably just send the JSON object as a delta

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/df4d16cc206cad234762e30d76ce19f1a6b5c7d4/server/users.js#L493-L500

There's also `specialNextBattle` which should probably be promoted to an official setting instead of relying on `@ts-ignore` (or, well, it's an unsafe cast in the matchmaker now).
