### ISSUE TITLE
Multiple `-mustrecharge` messages

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5462]
`node tools/simulate multi 1 --seed=1,2,3,8 --output` (discovered in #5427)

```
|turn|21
|
|move|p1a: Venomoth|Stun Spore|p2a: Articuno
|-fail|p2a: Articuno|par
|move|p2a: Articuno|Hyper Beam|p1a: Venomoth
|-damage|p1a: Venomoth|156/256
|
|upkeep
|turn|22
|-mustrecharge|p2a: Articuno
|-mustrecharge|p2a: Articuno
|-mustrecharge|p2a: Articuno
|
|move|p1a: Venomoth|Psychic|p2a: Articuno
|-crit|p2a: Articuno
|-damage|p2a: Articuno|206/286 par
|-unboost|p2a: Articuno|spd|1
|-unboost|p2a: Articuno|spa|1
|cant|p2a: Articuno|recharge
|
|upkeep
```

`Pokemon#getRequestData` calls `Pokemon#getLockedMove` which runs the `LockMove` event and the `recharge` `onLockMove` calls `this.add(...)`.

I think you should be able to build the request without adding to the battle log at all. Its entirely possible theres a similar thing happening with #5023.

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/commit/d80f788f97ec150a08192676c78d6608030b06c0

It looks like this is from ages ago.

**Comment by Zarel** [comment]
I definitely think the `mustrecharge` tag should just appear on move use. It should also probably be changed to `|-movestatus|...|mustrecharge`.

**Comment by Zarel** [comment]
I'm guessing the reason @Marty-D made it stop appearing on move use was because of issues with Power Herb? But I think with the modern implementation of movestatus, the naive solution shouldn't be a problem.

**Comment by Zarel** [comment]
(I'd also guess that this has nothing to do with the Rest bug.)

**Comment by Marty-D** [comment]
There was a client change to go with that: https://github.com/Zarel/Pokemon-Showdown-Client/commit/49376fcd2b91f328f0daa5df6aeea469a8c867b1. I feel like I asked if this was an okay thing to do at the time. I think the issue was the tag would appear anyway if the target avoided damage other than when the move missed?

**Comment by scheibo** [comment]
> I definitely think the `mustrecharge` tag should just appear on move use.

This would make more sense to me. (thats actually what I thought was happening when I first saw it - I thought maybe the AI was choosing the wrong move multiple times = multiple messages)

> It should also probably be changed to `|-movestatus|...|mustrecharge`.

`|-movestatus` does not appear to be a thing? movestatus is a client concept, no? https://github.com/Zarel/Pokemon-Showdown-Client/commit/49376fcd2b91f328f0daa5df6aeea469a8c867b1 looks like it would handle the `-mustrecharge` on move anyway?

**Comment by Zarel** [comment]
Sorry, it's `|-singlemove|`. I call volatile statuses with single-move duration movestatuses, so I got that mixed up.

**Comment by Zarel** [comment]
> There was a client change to go with that: [Zarel/Pokemon-Showdown-Client@49376fc](https://github.com/Zarel/Pokemon-Showdown-Client/commit/49376fcd2b91f328f0daa5df6aeea469a8c867b1). I feel like I asked if this was an okay thing to do at the time. I think the issue was the tag would appear anyway if the target avoided damage other than when the move missed?

I'm fine with adding an explicit activation message, but it should have been at the start of the `mustrecharge` volatile instead of the end of the turn.
