### ISSUE TITLE
[Custom Game] Remove "Pokemon" Clause from Gen I-III

### ISSUE THREAD

**Issue by Tmi489** [Zarel/Pokemon-Showdown#5477]
So that future Pokemon/Moves/Abilities, and 24 Pokemon, can be used in Generation I-III Custom Game. Moves already change category on the teambuilder, so the only things I can potentially see going wrong are certain moves I'm not accounting for (Secret Sword?), or abilities (restrict for Gen III).

**Comment by Zarel** [comment]
I'd support this. Do you want to pull request this yourself? It's a pretty simple change.

**Comment by Tmi489** [comment]
I would but i have no idea how to do it

**Comment by Tmi489** [comment]
nevermind figured it out

**Comment by Zarel** [comment]
We removed the 32-bit cap in custom games, for level 9999. But all other caps are still there. I bet it's some other code which causes that.

**Comment by Zarel** [comment]
Fixed in #5478
