### ISSUE TITLE
Which issues from the "Mechanics Bugs" project are still open?

### ISSUE THREAD

**Issue by jmclemo6** [Zarel/Pokemon-Showdown#5520]
Been looking at a few of them and haven't been able to repro either https://github.com/Zarel/Pokemon-Showdown/projects/3#card-18663149 or https://github.com/Zarel/Pokemon-Showdown/projects/3#card-18662948.

I guess there's a chance I'm doing something wrong here, but can't figure out what it may be.

**Comment by Marty-D** [comment]
Sorry about that, I forgot those were already fixed when moving stuff from the issue into cards. I've chucked them in the done pile and linked them to their fixes now.
