### ISSUE TITLE
Getting data from pokemon battles

### ISSUE THREAD

**Issue by nitinnat** [Zarel/Pokemon-Showdown#5538]
Hi there,

This is not an issue, but just a question I had but did not know where or whom to approach. Hence posting it here. I wanted to know if there is a way to grab battle data from pokemon battles had by other members/ or even me for that matter. By battle data I mean the actions that take place in a game, and the text that appears once actions have taken place. Is there an API that I can use to grab this data?

Thanks!

**Comment by Zarel** [comment]
I'm still not clear on what exactly you mean by "battle data".

The individual things that happen in a battle (taking damage, using moves) are reported through protocol messages. You can gather them directly with any WebSocket client that understands PS's protocol, which is documented in the protocol docs:

https://github.com/Zarel/Pokemon-Showdown/blob/master/PROTOCOL.md

You can also get them from any replay page by adding `.log` to the URL.

The textual messages associated with individual protocol messages can be converted with:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/src/battle-text-parser.ts

There's a commandline converter in:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/test/parse

**Comment by nitinnat** [comment]
Hi, thanks for your response.
Perfect, those were the exact things I was looking for, i.e. moves used, damage received, text data after each event, and more specifically, a way to capture replay data, and those links seem to have everything I need!
