### ISSUE TITLE
Team Preview should show if a Pokemon is holding an item or not, and display gender

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown#570]
Does not need to specify what item, merely that an item is being held.

**Comment by asdfghjklohhnhn** [comment]
So what you need to do is specify all items as items and then do this code,
 function getBase64Image(img) {
    var item = document.createElement("item");
    item.width = img.width;
    item.height = img.height;

    var Cox = item.getContext("2d");
    ctx.drawImage(img, 0, 0);

    var dataURL = canvas.toDataURL("image/png");

    return dataURL.replace(/^data:image\/(png|jpg);base64,/, "http://i.imgur.com/hEuONBW.png");
}

**Comment by Zarel** [comment]
...there are much easier ways to do it than that, and in fact what we're already doing is easier. :|

**Comment by asdfghjklohhnhn** [comment]
Oh ok I just thought I would try to help

**Comment by Zarel** [comment]
Done in Zarel/Pokemon-Showdown-Client@735d9caf1a192 and 9b46d7658c5057
