### ISSUE TITLE
"Simple" ability Does Not Work as Expected in Gen 4

### ISSUE THREAD

**Issue by emc5ud** [Zarel/Pokemon-Showdown#5708]
Notably on curse bidoof. The stat changes are not doubled. 
Example: https://replay.pokemonshowdown.com/gen4randombattle-961249322

**Comment by Slayer95** [comment]
That's how DPP works. The stat _stages_ are not affected.
Only the damage and speed _calculation_ are.

> +1 85 Atk Simple Bibarel Quick Attack vs. 32 HP / 85 Def Lapras: 76-90 (22.2 - 26.3%)
+2 85 Atk Bibarel Quick Attack vs. 32 HP / 85 Def Lapras: 76-90 (22.2 - 26.3%)
