### ISSUE TITLE
BattleTextStream broken

### ISSUE THREAD

**Issue by yjp20** [Zarel/Pokemon-Showdown#5760]
commit 7e4929a breaks BattleTextStream
On commit 5c222ae, running `./pokemon-showdown simulate-battle` then entering
```
>start {"formatid":"gen7randombattle"}
>player p1 {"name":"Alice"}
>player p2 {"name":"Bob"}
>p1 move 1
>p2 move 1
```
gives us data for the shared stream, but it fails to do so after 7e4929a.

Considering that it went five months without notice, I might be the only user of this feature... XD, but still, it seems like a relatively easy fix.

**Comment by Zarel** [comment]
Weird, I'm pretty sure I've used it to test mechanics bugs since then. It might only apply to some uses?

**Comment by scheibo** [comment]
I'm confused at to what exactly the issue is? What is the 'shared stream'? `./pokemon-showdown simulate-battle` still seems to provide all sides of the split?:

Before:
```
|start
|split
|switch|p1a: Hawlucha|Hawlucha, L80, M|100/100
|switch|p1a: Hawlucha|Hawlucha, L80, M|256/256
|switch|p1a: Hawlucha|Hawlucha, L80, M|100/100
|switch|p1a: Hawlucha|Hawlucha, L80, M|256/256
|split
|switch|p2a: Crabominable|Crabominable, L89, F|100/100
|switch|p2a: Crabominable|Crabominable, L89, F|100/100
|switch|p2a: Crabominable|Crabominable, L89, F|317/317
|switch|p2a: Crabominable|Crabominable, L89, F|317/317
|turn|1
```

After:
```
|start
|split|p1
|switch|p1a: Mawile|Mawile, L80, M|211/211
|switch|p1a: Mawile|Mawile, L80, M|100/100
|split|p2
|switch|p2a: Relicanth|Relicanth, L89, F|323/323
|switch|p2a: Relicanth|Relicanth, L89, F|100/100
|-ability|p1a: Mawile|Intimidate|boost
|-unboost|p2a: Relicanth|atk|1
|turn|1
```

**Comment by yjp20** [comment]
You're right... I could've sworn this was broken for me for some reason where the update functionality wasn't working. It seems to be user error on my part. Sorry about that.
