### ISSUE TITLE
Insufficient documentation for natures in packed team format

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#5919]
https://github.com/Zarel/Pokemon-Showdown/blob/master/PROTOCOL.md#team-format

There is no entry for "Nature" in that list, and the example shows it as being blank. I'm assuming no nature means that some default nature is picked, but a brief look at the reference implementation did not reveal anything to me. Running `Dex.fastUnpackTeam` is also not helpful, as it says the nature is `''`, which is obviously not a nature.

**Comment by Slayer95** [comment]
In fact, PS accepts empty nature as a valid neutral nature in any generation.

That's arguably wrong behavior though.

**Comment by Zarel** [comment]
A Nature of `""` is assumed to be Serious, but yes, this should probably be documented.

**Comment by Slayer95** [comment]
@Zarel , nothing in the sim code makes it Serious as opposed to Hardy, Docile, Bashful or Quirky.

**Comment by Zarel** [comment]
@Slayer95 The client will display it as Serious. Nothing in the sim code makes it _not_ Serious.

**Comment by Zarel** [comment]
Fixed in 1376cd1bea3ca7a797e514630bfa5a32acec24d1

**Comment by Zarel** [comment]
In other words: The sim doesn't contain any code that needs to treat Serious differently from other natures, but if it did, it would treat `''` as Serious.

The client does contain code that treats Serious differently from other natures, and it does treat `''` as Serious.

**Comment by Slayer95** [comment]
@Zarel , an event-only move may be restricted to Pokémon with Serious nature, but empty nature won't be accepted by the validator.

**Comment by Zarel** [comment]
That should probably be fixed in-sim, then.

**Comment by davidstone** [comment]
Also berries like https://www.smogon.com/dex/sm/items/aguav-berry/ . They cause confusion based on whether the nature subtracts from some state, and all of the neutral natures are +Stat -Stat for purposes of confusion berries (at least I believe that was the behavior in Generation 4, not sure if that was maintained in later generations).
